README.md, libs/api/ebpf_api.cpp
HVCI requires the guest OS to enforce it so doesn't apply to Linux
=> Fix README.md

README.md
Just a tiny error: there's a missing `)` in `README.md`, under "Architectural Overview".
=> Fix README: Add missing close parenthesis

libs/execution_context/ebpf_program.c
Document why we disable bounds check when using uBPF
See: https://github.com/iovisor/ubpf/issues/68 for details
=> Document why we disable bounds check when using uBPF

libs/ubpf/kernel/ubpf_kernel.c, libs/ubpf/user/ubpf_user.c
Increase stack size for eBPF programs to 512 bytes
=> Increase stack size for eBPF programs to 512 bytes

ebpfsvc/rpc_api.cpp, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/execution_context/unit/execution_context_unit_test.cpp, rpc_interface/rpc_interface.idl, tests/client/rpc_client.cpp, tests/sample/droppacket_unsafe.c, tools/netsh/programs.cpp
The IDL was generating MIDL2279 because it used const on an [out] param,
which is warned against since RPC marshaling copies the result into new
memory.  See https://marc.info/?l=ms-dcom&m=103440617317922 for some
discussion.
Other changes should hopefully be obvious.
=> Clean up compiler warnings

libs/api/Verifier.cpp, tests/end_to_end/end_to_end.cpp, tools/netsh/elf.cpp
Since the native program type changed from int to GUID the display has been
broken (it displays a useless pointer value).  This fix makes it display
the string name of the type.
=> Fix netsh display of program type

.github/workflows/update-docs.yml, include/ebpf_api.h
"git commit -am" only adds changes to existing files, not new files
and so was missing adding docs when new headers were added, resulting
in a failure.
Also some params were missing from doxygen which resulted in
a bunch of warnings.
The issues this addresses can be seen at 
https://github.com/microsoft/ebpf-for-windows/runs/2671854760
=> Fix doxygen errors

.github/workflows/update-docs.yml
Previously the script worked when there were changes and
generates an error when there's actually nothing to do
because "git commit" returns exit code 1 when there's nothing to do.
This updates the github workflow to only commit when there's something
to commit.  For more discussion see
https://stackoverflow.com/questions/5139290/how-to-check-if-theres-nothing-to-be-committed-in-the-current-branch
=> Fix doxygen error when there are no changes to commit

include/ebpf_api.h, libs/api/Verifier.cpp, libs/service/verifier_service.cpp, tests/end_to_end/end_to_end.cpp, tools/netsh/elf.cpp
For now, create a type ebpf_api_verifier_stats_t that mirrors the verifier's ebpf_verifier_stats_t struct.
Fixes #193
=> Make netsh "show verification" command display max instruction count

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_epoch.c, libs/platform/ebpf_epoch.h, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_object.c, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_platform.h, libs/platform/ebpf_program_types.c, libs/platform/ebpf_trampoline.c, libs/platform/kernel/ebpf_extension_kernel.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_extension_user.c, libs/platform/user/ebpf_platform_user.cpp, libs/ubpf/kernel/ubpf_kernel.c, netebpfext/net_ebpf_ext.c
Remove allocations from executable memory pool
Resolves: #237 
=> Remove allocations from executable memory pool

libs/api/api.vcxproj, libs/service/api_service.cpp, libs/service/service.vcxproj
eBPF supports helper IDs in the range [0, MAXUINT32]
uBPF jitter only supports helper IDs in the range [0,63]
This fix works around the issue by remapping helper_ids that are used in the program to the permitted range.
Resolves: #204 
=> Remap helper_ids to range [0,63]

ebpfcore/ebpf_drv.c, include/ebpf_result.h, libs/api/ebpf_api.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_epoch.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_serialize.c, libs/platform/ebpf_trampoline.c, libs/platform/kernel/ebpf_extension_kernel.c, libs/platform/kernel/ebpf_handle_kernel.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_extension_user.c, libs/platform/user/ebpf_handle_user.c, libs/platform/user/ebpf_platform_user.cpp, libs/service/api_service.cpp, libs/service/verifier_service.cpp, netebpfext/net_ebpf_ext.c, tests/client/main.cpp, tests/end_to_end/end_to_end.cpp
* Remove `_ERROR_` for consistency
* Combine EBPF_INVALID_HANDLE and EBPF_INVALID_OBJECT so that the latter is returned by ebpfapi not the former since handles are an internal implementation detail
* Rename EBPF_ERROR_NOT_FOUND to EBPF_KEY_NOT_FOUND for consistency with the associated description.
* Change code that returned EBPF_ERROR_NOT_FOUND for a case other than a key, to use a different appropriate result, so the description stays correct.
* Rename EBPF_VALIDATION_FAILED to EBPF_VERIFICATION_FAILED for consistency with the associated description.
Fixes #212
=> Simplify names of some ebpf_result codes

include/ebpf_core_structs.h, libs/execution_context/ebpf_core.c, libs/platform/ebpf_serialize.c, libs/platform/ebpf_serialize.h, libs/platform/unit/platform_unit_test.cpp
This PR addresses a couple of comments from merged PR https://github.com/microsoft/ebpf-for-windows/pull/246
- arrange header includes alphabetically in serialize.h
- rename ebpf_core_map_information_t to ebpf_map_information_internal_t
=> Code review comments from PR 246

netebpfext/net_ebpf_ext.c
Net eBPF extension must use SynchronizationEvent for synchronization
Resolves: #262 
=> Net eBPF extension must use SynchronizationEvent for synchronization

docs/GettingStarted.md, docs/vm-setup.md, ebpfapi/ebpfapi.vcxproj, ebpfsvc/eBPFSvc.vcxproj, libs/api/api.vcxproj, libs/api_common/api_common.vcxproj, libs/execution_context/kernel/execution_context_kernel.vcxproj, libs/execution_context/unit/execution_context_unit_test.vcxproj, libs/execution_context/user/execution_context_user.vcxproj, libs/platform/kernel/platform_kernel.vcxproj, libs/platform/unit/platform_unit_test.vcxproj, libs/platform/user/platform_user.vcxproj, libs/service/service.vcxproj, libs/ubpf/kernel/ubpf_kernel.vcxproj, libs/ubpf/user/ubpf_user.vcxproj, netebpfext/netebpfext.vcxproj, scripts/deploy-ebpf.ps1, scripts/install-ebpf.bat, tests/api_test/api_test.vcxproj, tests/client/ebpf_client.vcxproj, tests/end_to_end/end_to_end.vcxproj, tests/libs/common/common_tests.vcxproj, tests/libs/util/test_util.vcxproj, tools/dnsflood/dnsflood.vcxproj, tools/encode_program_information/encode_program_information.vcxproj, tools/netsh/ebpfnetsh.vcxproj, tools/port_leak/port_leak.vcxproj, tools/port_quota/port_quota.vcxproj
* Create an install script rather than having to manually do lots of steps
* Make Debug build use vcruntime as static libs to avoid adding another prerequisite on a machine before installing eBPF.  This isn't required for Release builds as vcruntime release DLLs are part of Windows, unlike vcruntime debug DLLs.  
https://github.com/vbpf/ebpf-verifier/pull/236 was recently merged that makes the same change in the PREVAIL verifier project.
Fixes #248
=> Add VM setup scripts and docs

rpc_interface/rpc_interface.idl
Without the annotation, clang-format would convert
`uuid(6bef171d-7205-4b63-a1e5-d00f01e6a0c1)`
to
`uuid(6bef171d - 7205 - 4b63 - a1e5 - d00f01e6a0c1)`
which would be invalid.
Fixes #269
=> Annotate IDL GUID so clang-format will not interfere

include/ebpf_program_types.h, include/ebpf_structs.h, libs/api/Verifier.cpp, libs/api/Verifier.h, libs/api/windows_platform.cpp, libs/api_common/api_common.cpp, libs/api_common/device_helper.cpp, libs/api_common/windows_helpers.cpp, libs/api_common/windows_platform_common.cpp, libs/service/verifier_service.cpp, libs/service/verifier_service.h, libs/service/windows_platform_service.cpp, tests/client/main.cpp
Remove duplicate types:
* ebpf_helper_return_type_t
* ebpf_helper_argument_type_t
* ebpf_context_descriptor_t
This PR requires https://github.com/vbpf/ebpf-verifier/pull/238 to be merged first.
Fixes #153
=> Merge eBPF types with the types in ebpf-verifier

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_extension_kernel.c, libs/platform/user/ebpf_extension_user.c
* Make a couple of `_In_` arguments be const
* Add `_opt_` to a number of arguments that can be NULL
* Add SAL annotation to a few more APIs that were missing it
* Remove annotations like `_Pre_readable_byte_size_(hash_table->key_size)` since they just give code analysis warnings such as:
```
c:\git\dthaler\ebpf-for-windows\libs\platform\ebpf_platform.h(445): warning C28230: The type of '_Param_(1)' has no member 'key_size'.
c:\git\dthaler\ebpf-for-windows\libs\platform\ebpf_platform.h(445): warning C28285: For function 'ebpf_hash_table_delete' '_Param_(2)' syntax error in 'SAL_readableTo(byteCount(__formal(0,hash_table)->key_size))' near 'key_size))'.
```
=> Add some more SAL annotations and clean up some code analysis warnings

tests/end_to_end/end_to_end.cpp
Add a test that JITs the bindmonitor.o eBPF program and runs it.
Blocked on: https://github.com/iovisor/ubpf/pull/78
Resolves: #241 
=> end_to_end test should have a JIT version of bindmonitor.o

libs/api/Verifier.cpp, libs/ebpfnetsh/elf.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tests/end_to_end/test_helper.hpp, tests/unit/test.vcxproj, tests/unit/test.vcxproj.filters
Add tests for "show verification" and a minimal test for "show programs"
Fix a couple bugs that the tests uncovered
Remove duplicate "error: error:" prefix in messages on verification
Fixes #240
=> Add additional netsh tests

CONTRIBUTING.md
Proposed changes to contributing guide.
Triage issue in weekly meeting.
Request input from filer as appropriate
There will be a waiting period of 2 weeks for information from filer and if there is no response the issue will be closed.
=> Update CONTRIBUTING.md to include notes on closure of bugs 

Analyze.default.ruleset, external/Analyze.external.ruleset, libs/api/Verifier.cpp, libs/api/api_internal.h, libs/api/crab_verifier_wrapper.hpp, libs/api/ebpf_api.cpp, libs/api/elfio_wrapper.hpp, libs/api/windows_platform.cpp, libs/api_common/api_common.cpp, libs/api_common/ebpf_verifier_wrapper.hpp, libs/api_common/windows_platform_common.cpp, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_platform.h, libs/platform/unit/platform_unit_test.cpp, libs/service/verifier_service.cpp, libs/service/windows_platform_service.cpp, tests/api_test/api_test.cpp, tests/client/ebpf_client.vcxproj, tests/client/main.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tests/libs/common/common_tests.cpp, tests/libs/common/common_tests.vcxproj, tests/libs/util/catch_wrapper.hpp
Suppress [C26451](https://docs.microsoft.com/en-us/cpp/code-quality/c26451).
Code in ELFIO and Boost are flagged for possible arithmetic overflow, but I think these are false positives. Suppressing this warning around code that pulls in ELFIO and Boost.
=> Suppress C26451

include/ebpf_program_types.h, libs/api/api_internal.h, libs/api_common/windows_helpers.cpp, libs/ebpfnetsh/ebpfnetsh.vcxproj, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_platform.h, libs/platform/ebpf_serialize.c, libs/platform/ebpf_serialize.h, libs/platform/ebpf_trampoline.c, libs/platform/kernel/ebpf_extension_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_extension_user.c, netebpfext/net_ebpf_ext.c, tests/api_test/api_test.vcxproj, tests/end_to_end/helpers.h, tests/unit/test.vcxproj, tools/netsh/ebpfnetsh.vcxproj
This change fixes #82 and #289 .
The summary of the changes:
1) ebpf_extension_data_t.data is now an opaque pointer instead of byte buffer. Program information NPI provider now sets the opaque pointer to ebpf_program_data_t which in turn has pointers to program_information and array of helper function addresses.
2) The helper function addresses are no longer passed in as program informatoin NPI provider's dispatch table, as these functions do not constitute the NPI contract between NPI modules (EC and extension). Rather they are the contract between eBPF program and Extension.
3). The program_information (includes program type context and helper function prototypes) are serialized in the GET_PROGRAM_INFORMATION protocol message handler and de-serialized in get_program_information_data.
4) …
=> program information serialization

Doxyfile, include/ebpf_execution_type.h, include/ebpf_nethooks.h, include/ebpf_result.h, include/ebpf_structs.h, include/ebpf_windows.h, include/tlv.h
* Make all enum values have a description in the generated API docs
* Also remove SAL annotation from the generated docs, since SAL
breaks doxygen type detection
=> Add doxygen documentation on enum values

Doxyfile, include/ebpf_helpers.h
Before this change, the API docs at
https://microsoft.github.io/ebpf-for-windows/ebpf__helpers_8h.html
just show the typedefs.  This PR updates the documentation so that the
helpers are documented just like normal public APIs would be.
This is the first step towards addressing #259
=> Add doxygen documentation on ebpf helpers

include/ebpf_api.h, include/ebpf_nethooks.h
This PR is the second of three steps towards fully addressing #259
The doxygen \ref annotation tells doxygen to make the following word be linked to the appropriate location in the generated docs.
=> Add doxygen docs on hooks

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_core.h, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_platform.h, netebpfext/net_ebpf_ext.c, tests/ext/drv/test_ext.c
This partially addresses #291 .
The net ebpf extensions used to have the map helper function prototypes in both the xdp and bind program info. This PR moves those to the global helper program info in ebpf_core.
get_helper_prototype_windows callback from verifier uses global_program_info.type.platform_specific_data stored in TLS to get the program type guid, which is supplied during program verification call. This program type stored in TLS is used to obtain the program info from EC by invoking an IOCTL. The IOCTL handler invokes ebpf_program_get_program_info_data which calls program initialize, which in turn loads the extension corresponding to the input program type, and returns the program info provider data (which includes helper function prototypes).
The …
=> move map helper function prototypes to EC

mainpage.dox
This PR addresses two gaps:
https://microsoft.github.io/ebpf-for-windows mentioned the hooks but
didn't mention what header file to include.
And it talked about ebpf programs, but didn't mention the reference for
user-mode apps to interact with them.
=> Improve doxygen main page

Analyze.default.ruleset, include/bpf.h, include/ebpf_helpers.h, include/ebpf_structs.h, libs/api/Verifier.cpp, libs/api/Verifier.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_map.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_program.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/unit/platform_unit_test.cpp, tests/client/main.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/sample/ebpf.h, tests/sample/sample.vcxproj, tests/sample/sample.vcxproj.filters, tests/sample/tail_call.c, tests/sample/tail_call_bad.c, tests/unit/libbpf_test.cpp, tools/encode_program_info/encode_program_info.cpp
This also fixes a bug where bpf_object__find_program_by_name
could only find the first program because program->object
was always null.
Also fixes tests to correctly use a signed int for what hooks return,
instead of an unsigned int.
Not done in this PR, but will be in a separate PR:
* make tail call replace stack frame instead of simply calling into the callee
* limit number of tail calls to 32
* require the same program type for caller and callee
* test with load from a byte array instead of from a file
Addresses part of #344
=> Add prog array map type and bpf_tail_call() helper

include/ebpf_program_types.h, libs/execution_context/ebpf_core.c, libs/platform/ebpf_serialize.c, libs/platform/unit/platform_unit_test.cpp, tests/sample/ext/drv/sample_ext.c, tools/encode_program_info/encode_program_info.cpp
Reverts microsoft/ebpf-for-windows#365
Not necessary now that we have clarified that the return_type provides the information necessary to tell whether stack unwind is needed.
=> Revert "Add code to propagate flags for helper functions."

include/ebpf_structs.h, libs/api_common/windows_platform_common.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp, tests/end_to_end/helpers.h
Add support for per-cpu hash and array maps - Part 1
Create core map functionality and block it from user mode API's.
Part 2 is to create per-cpu version of CRUD API's to access map entries.
=> Add support for per-cpu hash and array maps - Part 1

libs/api/ebpf_api.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp
This is a prerequisite to supporting variable-sized values being returned to user mode (when value size is a function of CPU count).
=> Explicit key and value lengths passed to map layer

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_platform.h
The final part of PR for issue #192 
This adds support for querying per-CPU maps from user mode and returning a merged view of the per-CPU data.
=> Adds support for querying per-CPU maps from user mode and returning a merged view of the per-CPU data

ebpfapi/Source.def, include/ebpf_api.h, libs/api/api_internal.h, libs/api/libbpf_map.cpp, tests/end_to_end/end_to_end.cpp, tests/sample/divide_by_zero.c, tests/sample/droppacket.c, tests/sample/droppacket_unsafe.c, tests/sample/ebpf.h, tests/sample/ext/app/sample_ext_app.cpp, tests/unit/libbpf_test.cpp, tools/port_quota/port_quota.cpp
Since there is a name conflict between KM helpers and UM libbpf APIs, the end-to-end tests need to _not_ include the KM helper prototypes, so removed ebpf_helpers.h from ebpf.h and made samples include it directly.
=> Update more UM map APIs for libbpf compatibility

libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_epoch.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_extension_user.c, libs/platform/user/ebpf_platform_user.cpp, libs/platform/user/framework.h, tests/libs/common/common_tests.cpp, tools/port_quota/port_quota.cpp
Switch to hash table from AVL. Lock-free in the presence of epoch allocator.
=> Switch to hash table from AVL. Lock free in the presence of epoch allocator.

.github/workflows/build.yml
Store build output as artifacts
Prerequisite to storing crash dumps.
Resolves: #412
=> Store build output as artifacts

libs/platform/ebpf_epoch.c
Immediately delete memory during rundown
=> Immediately delete memory during rundown

libs/platform/ebpf_hash_table.c
Stop searching once key is matched
Minor efficiency improvement in hash-table.
=> Stop searching once key is matched

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_platform.h, libs/platform/ebpf_trampoline.c, libs/platform/unit/platform_unit_test.cpp, libs/service/api_service.cpp, tests/sample/ext/app/sample_ext_app.cpp
This PR addresses #370 and second issue of #291 .
This PR adds support for program type specific helper functions in interpret mode. Here are the changes:
1. The program object now maintains an array of helper function IDs that are used by the program. Due to limitations in uBPF code, the helper function IDs have to be moved to a (0 - 63) range. The array indices are the "modified" helper IDs to be used by uBPF whereas the real helper IDs are stored in the array values.
2. When a program info provider (re)attaches the helper addresses are stored in the trampoline table. The index of the trampoline entry is chosen such that it can be easily derived from the helper ID; and a full lookup of the trampoline table is not needed when trying to retrieve address of a helper function.
3. Finally, …
=> Register program type specific helper functions to uBPF in interpreted mode

include/ebpf_api.h, include/ebpf_result.h, include/ebpf_structs.h, libs/api/ebpf_api.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_epoch.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_platform.h, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_extension_user.c
Fully support BPF flags for map operations
Options include:
1) Insert if the element doesn't exist.
2) Update the existing element.
3) Insert or update an element.
=> Fully support BPF flags for map operations

README.md
Also move the Zoom meeting info to an announcement in the discussions area
Fixes #162
=> Add note about github discussions

include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_hash_table.c, tests/end_to_end/end_to_end.cpp, tests/unit/libbpf_test.cpp
* Return correct error between EBPF_OBJECT_ALREADY_EXISTS (A program or
map is already pinned with the *same* path) vs
EBPF_ALREADY_PINNED (The program or map already pinned to a *different*
path).
* Update vs lookup elem were inconsistent in whether returning
EBPF_KEY_NOT_FOUND vs EBPF_INVALID_ARGUMENT when passing an array
index >= max_entries.  Made them be consistent in using
EBPF_INVALID_ARGUMENT.
Fixes #376
=> Add tests for libbpf bpf_map_*_elem APIs

ebpfapi/ebpfapi.vcxproj, ebpfsvc/eBPFSvc.vcxproj, include/ebpf_helpers.h, libs/execution_context/ebpf_core.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp, tests/client/ebpf_client.vcxproj, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/performance/performance.vcxproj, tests/sample/sample.vcxproj, tests/sample/sample_test_common.h, tests/sample/test_utility_helpers.c, tests/unit/test.vcxproj, tools/encode_program_info/encode_program_info.cpp, tools/encode_program_info/encode_program_info.vcxproj
This PR partly addresses #342  by adding the following helper functions.
```
bpf_get_prandom_u32
bpf_ktime_get_boot_ns
bpf_get_smp_processor_id
```
Few VS project files had to be updated to link against mincore.lib due to a windows function used.
=> utility general helper functions.

libs/platform/ebpf_epoch.c, libs/platform/ebpf_platform.h, libs/platform/ebpf_state.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp
=> All per-CPU structures should be allocated on EBPF_CACHE_LINE_SIZE boundaries

libs/api_common/api_common.cpp, libs/api_common/windows_platform_common.cpp, scripts/run_tests.bat, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/libs/common/common_tests.cpp, tests/libs/common/common_tests.h, tests/libs/common/common_tests.vcxproj, tests/libs/util/program_helper.cpp, tests/libs/util/program_helper.h, tests/libs/util/service_helper.h, tests/libs/util/test_util.vcxproj, tests/performance/performance.vcxproj, tests/sample/ext/app/sample_ext_app.cpp, tests/sample/ext/app/sample_ext_app.h, tests/sample/ext/app/sample_ext_app.vcxproj, tests/sample/ext/drv/sample_ext.c, tests/sample/ext/drv/sample_ext.h, tests/sample/ext/drv/sample_ext_drv.c, tests/sample/ext/inc/sample_ext_helpers.h, tests/sample/ext/inc/sample_ext_program_info.h, tests/sample/sample_common_routines.h, tests/sample/test_sample_ebpf.c, tests/sample/test_utility_helpers.c, tests/unit/test.vcxproj
This PR is further addressing #342  by adding tests for the utility helper functions in kernel mode. The PR makes the following changes:
1. Moves sample extension helper prototypes to a separate header file such that both code duplication is not needed betweeen extension driver and unit test.
2. Refactor eBPF program so that the the helper functions are invoked from another routine that can be included by eBPF programs of XDP and sample extension program types.
3. Some refactoring in unit test code such that code duplication can be avoided.
4. one *bug fix* where global attach type in TLS was not cleared up.
5. introduce run_tests.bat for running all tests on a test machine (I think it was part of #381 , but was removed when the PR was reverted).
=> Test utility helper functions.

scripts/deploy-ebpf.ps1
Fix for issue [#489](https://github.com/microsoft/ebpf-for-windows/issues/489).
Add missing `"sample_ebpf_ext.sys"` to `built_files` array in scripts/deploy-ebpf.ps1.
=> add sample_ebpf_ext.sys to built_files array in scripts/deploy-ebpf.ps1

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_core.h, libs/execution_context/ebpf_general_helpers.c, libs/execution_context/kernel/execution_context_kernel.vcxproj, libs/execution_context/kernel/execution_context_kernel.vcxproj.filters, libs/execution_context/user/execution_context_user.vcxproj, libs/execution_context/user/execution_context_user.vcxproj.filters, libs/platform/unit/platform_unit_test.cpp, tests/end_to_end/helpers.h, tests/unit/test.vcxproj, tools/encode_program_info/encode_program_info.cpp, tools/encode_program_info/encode_program_info.h, tools/encode_program_info/encode_program_info.vcxproj
This PR is cleaning up some test code in preparation for #341.
- The `helpers.h` file initializes the test program info provider for xdp and bind program types to have general helper prototypes. They are not needed as they are obtained from core library. So the PR removes them.
- netsh test still uses the old program_info encode fallback path. Those modules hard coded the global helper function and they had to be duplicated in 3 places. This PR consolidates the global helper function prototype descriptors in a single file.
=> clean up test code

libs/execution_context/ebpf_maps.c, tests/sample/map_in_map.c, tests/unit/libbpf_test.cpp
Updated the map_in_map.c test to use HASH instead of ARRAY as the inner
map type, to make it possible to test key_size mismatch (since key_size
must be 4 for all ARRAY maps, it can't be tested with ARRAY).
Fixes #507
=> Require all inner map attributes to match

libs/platform/kernel/ebpf_platform_kernel.c
ExAllocatePool2 isn't present in Windows Server 2019, switch to ExAllocatePoolUninitialized and zero memory.
Resolves: #506
=> Switch to memory allocation API's supported on older versions of Windows.

ebpfapi/Source.def, include/bpf.h, include/ebpf_structs.h, include/libbpf.h, include/linux/bpf.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_object.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_link.h, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_serialize.h, tests/unit/libbpf_test.cpp
This is the last libbpf api needed to enable the bpftool flow to detach an already loaded program.
There's already GET_MAP_INFO and GET_PROGRAM_INFO ioctls but they do different things than libbpf requires.
There's comments about this in ebpf_core.c.  In the future we may want to see what can be either combined or renamed for clarity, but for this PR I tried to minimize impact on other paths.
This also fixes a bug in ebpf_core.c where the map name was never being set in the kernel.
Fixes #372
=> Add support for libbpf bpf_obj_get_info_by_fd API

include/ebpf_nethooks.h, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_extension_user.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_program_info.h, netebpfext/net_ebpf_ext_xdp.c, netebpfext/netebpfext.vcxproj, netebpfext/netebpfext.vcxproj.filters, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/end_to_end/mock.cpp, tests/libs/util/test_util.vcxproj, tests/performance/performance.vcxproj, tests/sample/ebpf.h, tests/sample/ext/app/sample_ext_app.vcxproj, tests/sample/reflect_packet.c, tests/unit/test.vcxproj, tools/encode_program_info/encode_program_info.cpp, tools/encode_program_info/encode_program_info.vcxproj
This is part 1 of implementation for bpf_xdp_adjust_head helper.
This PR adds the prototype for the new function in netebpf ext XDP program information. Rest of the PR Is developing a sample eBPF Program that calls this function to encap an inbound packet with an extra IP header and reflects it back to the sender. And teh user mode unit test was added to test this program.
Part 2 will provide the actual implementation of the helper and an app to perform test with real network packets.
This PR builds on top of #520
=> Xdp adjust head part1

docs/GettingStarted.md, ebpfapi/Source.def, include/bpf.h, include/ebpf_api.h, include/libbpf.h, include/linux/bpf.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_object.cpp, libs/api/libbpf_program.cpp, libs/api_common/windows_helpers.cpp, libs/api_common/windows_platform_common.hpp, libs/ebpfnetsh/programs.cpp, libs/ebpfnetsh/tokens.h, libs/execution_context/ebpf_link.c, tests/end_to_end/netsh_test.cpp, tests/libs/common/common_tests.cpp, tests/libs/common/common_tests.vcxproj, tests/unit/libbpf_test.cpp, tools/netsh/ebpfnetsh.rc, tools/netsh/ebpfnetsh.vcxproj, tools/port_quota/port_quota.cpp
* Add support for libbpf bpf_obj_pin() API
* Add support for libbpf bpf_object__next() API
* Rename BPF_{PROG,ATTACH}_TYPE_UNKNOWN to ...UNSPEC for libbpf compat
* Remove now-unused handle APIs ebpf_api_load_program and ebpf_api_pin_object, which addresses part of issue #383 
* netsh set/delete program now uses the ID to identify the program, like bpftool does, so that it can work even if the program wasn't loaded from an ELF file
Fixes #191 
=> Update netsh commands to use more standard libbpf apis

.github/workflows/driver_test.yml
Revert fix for #530 as it breaks ci/cd pipeline.
=> Revert fix for #530 as it breaks ci/cd pipeline

docs/GettingStarted.md, docs/SelfHostedRunnerSetup.md, docs/vm-setup.md
Docs refer to installing the Visual Studio C++ Runtime, which is no longer required as we now include the runtime in the output folder.
=> Remove reference to MSVC Runtime from docs as it is no longer needed

ebpfapi/Source.def, ebpfapi/rpc_client.cpp, include/ebpf_api.h, include/ebpf_structs.h, include/ebpf_windows.h, include/libbpf.h, include/linux/bpf.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_protocol.h, tests/end_to_end/netsh_test.cpp, tests/sample/ext/app/sample_ext_app.h, tests/sample/ext/drv/sample_ext.c, tests/unit/libbpf_test.cpp, tools/encode_program_info/encode_program_info.h, tools/netsh/ebpfnetsh.rc
* Add the standard libbpf_prog_type_by_name() that accepts the equivalent of an ELF section name and returns the associated program type and expected attach type as ints.
* Add ebpf_get_program_type_by_name() that returns the GUIDs instead of ints.
This also removes the hard-coding of GUIDs or ints from the netsh helper.
=> Add libpf's libbpf_prog_type_by_name() API

ebpfapi/Source.def, include/bpf.h, include/ebpf_api.h, include/ebpf_structs.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_object.cpp, libs/api_common/windows_platform_common.cpp, libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_pinning_table.h, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tools/port_quota/port_quota.cpp
* The netsh `set program id=<id> pinned=` (with no value) will now unpin a program from all paths
* The netsh `delete program <id>` will now also unpin a program from all paths before and releasing any reference held by netsh itself
* Make the `attached=<string>` argument to netsh set programs work with a section name like string
* Add libbpf api bpf_obj_get()
* Add ebpf_get_next_pinned_program_name() API to enumerate pinned programs
Fixes #190 
Fixes #373
This is required for #188 which will update the "show programs" and also add an option to "add program" to pin all programs rather than just the first one in a file, like bpftool has such an option.
=> Add netsh capability to unpin programs

libs/platform/ebpf_object.c, libs/platform/ebpf_state.c
* Fix bug where getting the next ID failed to check for index beyond array size.
* Fix bug in ebpf_state.c where after enough tests ran it would start returning EBPF_NO_MEMORY because _ebpf_state_next_index was never reset.
The tests in PR #553 cover both of these bugs.
=> Fix bugs in ebpf_state and ebpf_object

.github/workflows/codeql-analysis.yml, include/ebpf_structs.h, libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp
Added BPF_MAP_TYPE_LRU_HASH to partially address #343.
Implemented as parallel key history hash-table. Need to investigate switching to heap for better reaping performance.
=> Add BPF_MAP_TYPE_LRU_HASH

libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c
Fixes issue in kernel CI/CD pipeline where maps aren't immediately removed from the object id table when their associated program is released.
=> Move release of maps to program release.

ebpfcore/EbpfCore.vcxproj, netebpfext/netebpfext.vcxproj, tests/sample/ext/drv/sample_ext.vcxproj
Bug was that if you cleaned everything and then tried to build just the
sample_ebpf_ext project, building would fail.  A race condition also
existed when trying to build everything in that if
execution_context_kernel wasn't done building by the
time sample_ebpf_ext was ready to link, the build would also fail.
=> Fix sample project dependencies

libs/platform/kernel/ebpf_platform_kernel.c
KeSetSystemAffinityThreadEx returning 0 means no-affinity was set, not failure.
=> Fix ebpf_set_current_thread_affinity

include/ebpf_structs.h, libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp
This version of BPF_MAP_TYPE_LPM_TRIE should be performant enough for experimentation / small instances of BPF_MAP_TYPE_LPM_TRIE.  This implementation is a placeholder until we get a more performant version.
Addresses: #560 
=> Implement trivial version of BPF_MAP_TYPE_LPM_TRIE

ebpfcore/ebpf_drv.c, libs/api/ebpf_api.cpp
Fix two bugs:
1) IOCTL handler shouldn't increase the reply length if the protocol handler sets it.
2) ebpf_get_next_pinned_program_path null terminates the return string, so the maximum length should be EBPF_MAX_PIN_PATH_LENGTH-1 to account for the null terminator.
=> Fix stack overrun and fix EC to return correct size

ebpfapi/Source.def, ebpfcore/ebpf_drv.c, include/bpf/bpf.h, libs/api/ebpf_api.cpp, libs/api/libbpf_map.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_maps.c, libs/platform/ebpf_handle.h, tests/end_to_end/test_helper.cpp, tests/unit/libbpf_test.cpp
* bpf_create_map() now fails for outer maps.  You must use  bpf_create_map_in_map() instead.
* Fixed bug where EBPF_INVALID_FD was incorrectly converted to EBPF_INVALID_ARGUMENT by ioctl handling code (part of issue #595). One symptom of this bug was that errno was being set to EINVAL in a number of cases which should have been EBADF.
* Fixed bug where a HASH_OF_MAPS (unlike ARRAY_OF_MAPS) wasn't enforcing that an inner map value had to match the inner map template. Refactored the code in ebpf_maps.c so the checking is done in one  place called by both maps, to ensure consistency.
* Fixed bug in HASH_OF_MAPS where if an update failed, it would leave the old entry but incorrectly drop the reference it held.  It now preserves the reference since the entry is unchanged.
* Added test case for …
=> Add libbpf bpf_create_map_in_map() API

include/ebpf_structs.h, libs/api/windows_platform.cpp, tests/sample/map_in_map_v2.c, tests/sample/sample.vcxproj, tests/sample/sample.vcxproj.filters, tests/unit/libbpf_test.cpp
Fixes #618 
The fix first tries to find inner map based on `inner_map_idx`. If `inner_map_idx` is 0, it tries to use `inner_id` to find the inner map template.
=> add inner_id support for map of map

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext_xdp.c, netebpfext/net_ebpf_ext_xdp.h, scripts/install_ebpf.psm1
This PR fixes issue described in #639 .
The netebpfext uses WFP callout at `INBOUND_MAC_FRAME_NATIVE` layer which caused WFP NDIS LWF to plumb receive handler only. However in `XDP_TX` code path the callout injects packets in outbound path, which required a send completion handler to be registered which was not present. NDIS invoked incorrect handler and OS crashed. The fix for this was to add WFP callout at `OUTBOUND_MAC_FRAME_NATIVE` layer as well which plumbed send completion handler.
The reason why this was not caught in internal testing was because the xdp_tests were run on other OS (client SKUs) that had some other Windows internal components that created WFP callouts in the `OUTBOUND_MAC` layer.
Some fixes were made to the installation script as well.
=> Add filter in outbound L2 layer.

libs/platform/kernel/ebpf_platform_kernel.c
MmMapLockedPagesSpecifyCache requires that pages be locked (i.e. won't be freed by memory manager). Because we explicitly allocated the pages, they are by definition locked, so the code should set the MDL_PAGES_LOCKED flag on the MDL.
=> Fix driver verifier failure due to not setting the flag to indicate pages are locked

libs/platform/kernel/ebpf_platform_kernel.c, netebpfext/net_ebpf_ext_xdp.c
This fixes an issue in netebpfext where it hits a bugcheck when trying to clone an NBL whose NB has multiple MDLs.
=> Fix AV in netebpfext when packet with multiple MDLs is received

libs/platform/user/ebpf_platform_user.cpp
Fix crash in the kernel on divide by zero.
Resolves: #666 
=> Fix crash in kernel on divide by zero

README.md
The redirect didn't work if you have a different slack group open.  Also adds pointer where to get an invite.
=> Updates link to slack

.github/workflows/build.yml
Pin actions/upload-artifact to version 2.2.4 to unblock ci/cd
=> Pin actions/upload-artifact to version 2.2.4 to unblock ci/cd

Directory.Build.props
Set the multi-processor build flag globally.
=> Set the multi-processor build flag globally

tests/libs/util/catch_wrapper.hpp
There does not appear to be any simple way to use a custom color
class with CATCH2 so we just disable color as is done for a UWP.
Fixes #679
=> Disable color output to avoid appverif problem

docs/GettingStarted.md
Align the formatting of a list (currently squashed into a single wrapped line).
Set code formatting, mainly for file names, similar to other locations in this file.
=> Align formatting

libs/api/ebpf_api.cpp, libs/api_common/api_common.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, libs/service/api_service.cpp, tests/unit/libbpf_test.cpp
Fixes #714
This also removes the EBPF_OPERATION_QUERY_MAP_DEFINITION ioctl which was now redundant with EBPF_OPERATION_GET_OBJECT_INFO for a map.  The only functional difference is that EBPF_OPERATION_QUERY_MAP_DEFINITION returned the original inner_map_id value set by the user mode app even for map types it was irrelevant for, whereas EBPF_OPERATION_GET_OBJECT_INFO would return EBPF_ID_NONE in such cases.  The latter is more correct, there's no use case that needs to preserve the original nonsense value other than EBPF_ID_NONE.
=> Support map fds with bpf_load_program

README.md, docs/GettingStarted.md
Also update the VS 2019 link now that it's not available on the MS site since VS 2022 was released.   Filed issue #725 to track VS 2022 support, not included in this PR.
Fixes #704 
=> Remove Server 2016 since mainstream support period is over

.github/workflows/driver_test_vm.yml, docs/GettingStarted.md, docs/InstallEbpf.md, docs/SelfHostedRunnerSetup.md, docs/vm-setup.md
This PR modifies the `Kernel_Test_VM` WF to have two jobs. The first one does a build on github action runner. The second one runs the kernel CICD tests on selfhosted runner. This job uses `fountainhead/action-wait-for-check@v1.0.0 action` to wait for the build job to complete first.
=> Modify Kernel_Test_VM workflow to have a build job and have the test job wait on it.

.github/workflows/driver_test_vm.yml, libs/api_common/api_common.hpp, libs/execution_context/ebpf_maps.c
This fixes #562 .
This PR refactors the ebpf_maps module as follows:
1. Move `inner_template` field to `ebpf_core_object_map`.
2. Move the lock field to individual map types that need lock.
3. Change signature of `create_map` to return a result.
4. Modify `ebpf_map_create` and `ebpf_map_delete` to not have inner template specific logic and instead have those in `create_map` and `delete_map` implementations of the various map types that use `ebpf_core_object_map`.
=> refactor maps

libs/execution_context/ebpf_maps.c, scripts/run_tests.psm1, tests/libs/common/common_tests.cpp
This fixes #740.
- Change PS script to re-throw exception raised due to test failure.
- Add temporary workaround for #739 .
- Fix ring buffer API test bug (which too was hidden due to the script issue).
=> fix CICD script to throw on test failure.

scripts/copy_pre_commit.ps1, scripts/setup_build/setup_build.vcxproj, scripts/setup_build/setup_build.vcxproj.filters
**Issue**
**setup_build** project copies pre-commit script to .git\hooks path as part of the build. This works fine when `ebpf-for-windows` repo is directly cloned. But if `ebpf-for-windows` is added as a submodule, then `setup_build` fails to build as it tries to copy the file to .git\hooks, but in case of submodule, there is no .git folder, instead, there is a .git file which has an entry to the root .git folder.
Ideally the file should be copied to the path which is returned by `git rev-parse --git-path hooks`. This command will return the correct .git path both in case of a submodule and a normal repo.
**Fix**
The fix adds a script which first executes `git rev-parse --git-path hooks` command to get the destination folder and then copy the precommit file to that folder. This allows …
=> add script to copy pre-commit file to relative hooks folder

.gitmodules
This PR updates ebpf-verifier submodule to `https://github.com/dthaler/ebpf-verifier.git` (branch `twostackvars`), until these changes are up-streamed.
=> update ebpf-verifier to the fork with latest changes

.gitmodules, ebpfapi/Source.def, include/asm/errno.h, include/asm/posix_types.h, include/asm/types.h, include/bpf/bpf.h, include/bpf/hashmap.h, include/bpf/libbpf.h, include/bpf_helpers.h, include/ebpf_api.h, include/linux/bpf.h, include/linux/stddef.h, libs/api/api.vcxproj, libs/api/api_internal.h, libs/api/bpf_syscall.cpp, libs/api/ebpf_api.cpp, libs/api/libbpf_link.cpp, libs/api/libbpf_map.cpp, libs/api/libbpf_object.cpp, libs/api/libbpf_program.cpp, libs/api/libbpf_system.cpp, tests/end_to_end/end_to_end.cpp, tests/unit/test.vcxproj, tools/bpftool/bpftool.vcxproj, tools/bpftool/bpftool.vcxproj.filters
* Added bpf_map_create, bpf_object__next_map, bpf_object__next_program, bpf_object__prev_map, bpf_object__prev_program libbpf APIs
* Removed obsolete exports ebpf_create_map and ebpf_create_map_name
* Updated prototype of bpf_program__attach and bpf_progam__attach_xdp to match latest libbpf header
* Now that bpftool has an official mirror, this PR switches the dependency to use it instead of Matteo's copy.
* Since libbpf is a submodule of bpftool, use it from that path rather than keeping libbpf as a separate submodule under ebpf-for-windows.
=> Update bpftool and libbpf dependencies

include/bpf2c.h, tests/bpf2c_test_wrapper/dllmain.cpp, tests/bpf2c_tests/bpf_test.cpp, tests/end_to_end/end_to_end.cpp, tests/libs/util/dll_metadata_table.cpp, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
Add function name and instruction count to program_entry_t.
Resolves: #770 
=> bpf2c should emit both symbol name and segment name in program_entry_t.

.github/workflows/build.yml, .github/workflows/driver_test_vm.yml
Switch CI/CD to explicitly use Server 2019 & VS 2019.
=> Switch to run CI/CD on Server 2019 + VS2019

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_handle.h, libs/platform/ebpf_object.c, libs/platform/ebpf_object.h, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_pinning_table.h, libs/platform/kernel/ebpf_handle_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_handle_user.c, tests/libs/util/dll_metadata_table.cpp, tests/performance/ExecutionContext.cpp
Both usermode and EC use same name for ebpf_object. This causes clash if both EC and UM header files are included in a test file.
This PR renames `ebpf_object_t` used in EC to `ebpf_core_object_t`
=> Rename EC ebpf_object_t to ebpf_core_object_t

include/bpf_helper_defs.h, include/ebpf_nethooks.h, include/ebpf_structs.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_general_helpers.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp, scripts/deploy-ebpf.ps1, tests/end_to_end/end_to_end.cpp, tests/sample/printk.c, tests/sample/sample.vcxproj, tests/sample/sample.vcxproj.filters
* Add bpf_printk() helper.  This initial version does not support any % arguments, that will come in a separate PR.  User-mode output goes to stdout.  Kernel-mode output goes to the trace log with a new printk keyword.
* Add a printk.c sample to test with, using the bind hook.
* Fix deployment script to deploy ebpfforwindows.wprp so that the "Getting traces" instructions actually work
=> Add support for bpf_printk helper without additional arguments

libs/platform/ebpf_epoch.c, libs/platform/ebpf_interlocked.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/kernel/platform_kernel.vcxproj, libs/platform/kernel/platform_kernel.vcxproj.filters, libs/platform/user/ebpf_platform_user.cpp, libs/platform/user/platform_user.vcxproj, libs/platform/user/platform_user.vcxproj.filters
Move common interlocked APIs into their own file.
Add bitwise interlocked operations.
Modify ebpf_epoch.c to use bitwise interlocked operations.
=> Move common interlocked API's into their own file

.gitmodules, libs/execution_context/ebpf_maps.c, libs/platform/ebpf_handle.h, libs/platform/kernel/ebpf_handle_kernel.c, libs/platform/user/ebpf_handle_user.c, tests/api_test/api_test.cpp
`ObReferenceObjectByHandle` can only be called at PASSVIE, but it was being called at DISPATCH. The map-in-map code is calling this API with spin lock held. This was not caught earlier due to missing map-in-map test cases in API test.
This PR changes code to not hold the lock when calling `ObReferenceObjectByHandle`
Added new test cases in api_test to cover this scenario.
NA
=> Fix calling ObReferenceObjectByHandle at DISPATCH

tools/bpf2c/bpf2c.cpp, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
bpf2c currently exports / emits map details for only those maps which are referenced in the ebpf programs. This causes the maps which are not referenced in the program to be never created. This at least breaks the scenario for map-in-map where the inner map is not really referenced by any program but is present in ELF file only as a template.
**Fix:**
Fix is to parse the maps section and read all the maps in that section.
PR #811 contains tests for this scenario.
NA
=> bpf2c should read and populate all the maps in ELF file

.github/workflows/build.yml, tests/bpf2c_test_wrapper/bpf2c_test_wrapper.vcxproj
Capture code coverage from bpf2c run during the build that is used to generate test dlls.
N/A
No.
=> Capture code coverage from bpf2c in build

.github/.codecov.yml
Set codecov task to only notify once all the CI/CD steps are complete.
CI/CD
N/A
=> Only notify after all CI steps are complete

.github/workflows/bpf2c-test.yml
For correctly determining the code coverage delta there needs to be a baseline value from the main branch. Both the build and bpf2c-test yml files upload code coverage data and should run on push to main.
CI/CD
N/A
=> Upload baseline for bpf2c tests

.gitmodules, include/elfio_wrapper.hpp, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
Switch back to the main upstream repo for ebpf-verifier now that PRs have been merged upstream.
Existing tests pass.  Also manually tested that the ebpf programs used in the Cilium demo pass verification.
No impact.
=> Use upstream main branch for ebpf-verifier

tests/api_test/api_test.cpp, tests/sample/bindmonitor_tailcall.c, tools/bpf2c/bpf_code_generator.cpp
This PR does the following:
1. Save the original map index while parsing the maps section.
2. Print the maps in the same order when emitting the C code.
Added new test in api_test.
NA
Fixes #875
=> bpf2c: emit maps in order they appear in ELF file

.github/.codecov.yml
Codecov.io sets the status as soon as the first coverage report is uploaded. The issue is that coverage data comes from parallel CI/CD jobs, resulting in the premature notification of status.
CI/CD
N/A
=> Only set codecoverage status after both bpf2c and build complete

.github/workflows/cicd.yml
Only run code coverage-related tests on push.
CI/CD.
N/A
=> Run code coverage baseline daily

.github/ISSUE_TEMPLATE/bug_report.yaml
The problem is that every bug report showed up as having "tasks" to be
done as can be seen at
https://github.com/microsoft/ebpf-for-windows/issues where a number of
bugs show "6 tasks". The checkboxes involved are not tasks, and indeed
they weren't providing us any value at present, so removed them.
=> Remove checkboxes from issue template

README.md
Fix the CodeQL status badge in the README.md file.
It should show the status for the scheduled run of the new CI/CD pipeline.
N/A
N/A
=> Fix the CodeQL status badge in README.md

libs/api/ebpf_api.cpp, libs/platform/ebpf_platform.h, libs/thunk/mock/mock.cpp, libs/thunk/platform.h, libs/thunk/windows/platform.cpp, scripts/config_test_vm.psm1, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/test_helper.cpp
This PR adds a fix for Issue #867. Following are the details:
The fix is to start calling `DeleteService()` and call `QueryServiceStatus()` before calling `DeleteService()`. Querying service status hydrates service reference count in SCM. This ensures that when `DeleteService()` is called, the service is only marked for deletion, and hence a later call to `ZwUnloadDriver()` by ebpfcore does not fail. 
One side effect of this approach still is that the stale service entries in the registry will not be cleaned up till the next reboot.
The PR also addresses some of the CR comments from earlier PRs.
Added new test case to ensure the driver is actually unloaded once the service is marked as deleted.
NA
Fixes #867
=> Fix ZwUnloadDriver failure issue

ebpf-for-windows.sln, ebpfapi/Source.def, include/ebpf_api.h, libs/api/Verifier.cpp, libs/ebpfnetsh/elf.cpp, tests/bpf2c_test_wrapper/bpf2c_test_wrapper.vcxproj, tests/bpf2c_test_wrapper/bpf2c_test_wrapper.vcxproj.filters, tests/bpf2c_test_wrapper/dllmain.cpp, tests/bpf2c_tests/elf_bpf.cpp, tests/end_to_end/end_to_end.cpp, tools/bpf2c/bpf2c.cpp, tools/bpf2c/bpf2c.vcxproj, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
Integrate bpf2c with ebpf-veriifer to permit calling verifier prior to performing code generation.
Updated bpf2c_tests.
Updated help output.
=> Call ebpf_verifier prior to code gen

.github/workflows/cicd.yml, tests/bpf2c_tests/elf_bpf.cpp
Verification of map.o can take 10minutes+, which can cause the BPF2C tests to timeout. This change disables verification for map.o in bpf2c.
CI/CD
No
=> Disable verification on for map.o to prevent CI/CD failures

.github/workflows/cicd.yml, include/ebpf_nethooks.h, netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_sock_ops.h, netebpfext/net_ebpf_ext_xdp.c, netebpfext/netebpfext.vcxproj, scripts/config_test_vm.psm1, scripts/run_driver_tests.psm1, tests/bpf2c_tests/expected/sockops_dll.txt, tests/bpf2c_tests/expected/sockops_raw.txt, tests/bpf2c_tests/expected/sockops_sys.txt, tests/libs/common/common_tests.cpp, tests/libs/common/common_tests.h, tests/libs/util/socket_helper.cpp, tests/libs/util/socket_helper.h, tests/sample/sockops.c, tests/socket/socket_tests.cpp, tests/socket/socket_tests.vcxproj, tests/socket/socket_tests_common.h
Fixes #786 
- WFP callout for WFP ALE established. The callout invokes the eBPF program notifying about new inbound/outbound connections. If the eBPF program returns success, the WFP flow is associated with a context.
- Upon flow deletion, eBPF program is notified of connection tearing down.
- Some changes to common code in netebpfext.
- Fixed some race conditions between WFP callbacks and program detach.
- Changes to socket and ring-buffer test libraries.
- Ran generate_expected_bpf2c_output.ps1.
- Some minor CICD WF changes.
New test cases added in socket_tests.exe
None.
=> WFP ALE Flow established callout, tests etc.

libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_core.c, scripts/deploy-ebpf.ps1, tests/bpftool_tests/bpftool_tests.cpp, tests/end_to_end/netsh_test.cpp, tests/libs/util/capture_helper.cpp, tests/libs/util/netsh_helper.cpp
This PR is the next in the series of bpftool test PRs.  It adds more bpftool tests and fixes various issues they uncovered.
* Fix netsh delete program to delete all pinned paths and remove spurious "Program not found" output.
* Remove bpftool help text output that only applies to Linux at the moment
* Make bpftool tests work regardless of the actual program/map id value so the tests can be run multiple times
* Fix bugs in capture_helper that sometimes lost output
This PR includes new tests.
No impact.
Resolves: #992
=> Add more bpftool tests

.github/workflows/cicd.yml, libs/platform/kernel/ebpf_extension_kernel.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_prog_info_provider.c, netebpfext/net_ebpf_ext_sock_ops.c, tests/sample/ext/drv/sample_ext.c
This fixes #990.
To fix this issue the EC NPI client module frees its binding context in CleanupBindingContext callback.
Similar fixes were applied in netebpfext and sample_ebpf_ext provider modules.
In addition to the above issue which caused a crash, there was another issue in the sock_ops hook.
Unloading a sock_ops program invokes detach_client handler of sock_ops hook removes WFP contexts from flows, which causes synch invocation of flowDeleteFn - which in turn tries to invoke the eBPF program to notify about connection deletion. This is wrong as the connection could be still active.
Other than this typos were fixed and redundant ebpf_client was removed from github runner.
Existing test caught the bug.
N/A.
=> Fix issues in NMR module implementations.

include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_link.cpp, libs/api/libbpf_program.cpp, tests/end_to_end/test_helper.cpp, tests/end_to_end/test_helper.hpp, tests/unit/libbpf_test.cpp
Addresses most of #1021
Add tests for:
* bpf_link__pin
* bpf_link__unpin
* libbpf_num_possible_cpus
* bpf_prog_attach
* bpf_program__unload
No impact.
=> Add more libbpf api tests

.github/workflows/cicd.yml
Change the CI/CD pipeline to run on push to main. This event occurs each time a PR completes. This is done to ensure each PR has an accurate code coverage baseline to compare against.
CI/CD.
No.
=> Run the CI/CD on push to main (after merge of a PR)

.github/workflows/cicd.yml, CMakeLists.txt, cmake/settings.cmake
Set CMAKE settings to target Windows SDK 10.0.19041.0.
CI/CD
No.
=> Set CMAKE_SYSTEM_VERSION and CMAKE_CXX_STANDARD

tools/bpf2c/bpf2c.vcxproj, tools/bpf2c/bpf2c.vcxproj.filters, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj
Drivers generated by Convert-BpfToNative should have the correct spectre mitigation flags set.
CI/CD
No.
=> Set /Qspectre option on generated drivers

libs/platform/user/ebpf_platform_user.cpp
This PR adds a workaround of disabling preemptible work items for UM till Issue #1038 is fixed.
Existing tests cover the changes.
NA
=> Disable preemptible workitems for UM (workaround)

libs/execution_context/ebpf_native.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp
**Issue**
native module in ebpfcore queues preemptible workitems in some scenarios. These workitems access the native module hash table which can be freed before the workitem is executed (in service stop scenario). This race condition is causing random crashes in the tests.
**Fix** 
The workitem routine does not really need to access the hash table, as it is only to unload the native driver. Modified the code now to ensure workitem routine does not touch any data structures, and only calls _unload driver_ function.
There is already code present to ensure the service does not stop until all the workitems have completed. So that aspect is already covered.
Existing tests cover this.
NA
Fixes #1038
=> Random crash fix - preemptible workitems

.github/workflows/reusable-build.yml
Set /W4 and /Qspectre on catch2 and ebpf-verifier projects.
CI/CD
No.
=> Resolve BA2004 - Missing /Qspectre flag

tests/bpf2c_tests/expected/divide_by_zero_dll.txt, tests/bpf2c_tests/expected/divide_by_zero_raw.txt, tests/bpf2c_tests/expected/divide_by_zero_sys.txt, tests/bpf2c_tests/raw_bpf.cpp, tools/bpf2c/bpf_code_generator.cpp
Running this command:
powershell scripts\Convert-BpfToNative.ps1 bpf_xdp_dsr
powershell scripts\Convert-BpfToNative.ps1 bpf_xdp_snat
Should succeed, but it fails due to /w4 /wx and warnings from the generated code.
CI/CD
Run:
powershell scripts\Convert-BpfToNative.ps1 bpf_xdp_dsr
powershell scripts\Convert-BpfToNative.ps1 bpf_xdp_snat
None required.
Resolves: #1056
Resolves: #1057
=> Resolve warnings in bpf2c generated code

ebpfapi/Source.def, include/bpf/libbpf.h, libs/api/libbpf_program.cpp, libs/ebpfnetsh/programs.cpp, tests/api_test/api_test.cpp, tests/unit/libbpf_test.cpp
In libbpf APIs, bpf_program__get_type() is a legacy alias for bpf_program__type().  We only supported the legacy alias and not the modern api.  This PR adds the modern api.
Tests are updated in this PR.
Documentation is updated in this PR.
=> Add support for bpf_program__type

.github/workflows/update-docs.yml, netebpfext/net_ebpf_ext_hook_provider.c
**Issue:**
MSDN (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exacquirepushlockexclusive) says that the caller should call `KeEnterCriticalRegion()` before acquiring push lock (both shared and exclusive).
This PR fixes that by calling `KeEnterCriticalRegion` / `KeLeaveCriticalRegion` at appropriate places.
Existing tests cover it.
NA
=> EX_PUSH_LOCK fix

.github/workflows/ossar-scan.yml
PE submodule contains invalid PE images that break the ossar tool. Skip checking out repo as it's not needed for the ossar scan.
CI/Cd
No.
=> Skip checkout of repo for ossar scan

tests/bpf2c_tests/bpf2c_tests.vcxproj, tests/bpf2c_tests/elf_bpf.cpp
Some of the expected output is overwritten during the build, invalidating the test.
CI/CD
No.
=> Move expected output to subfolder

libs/execution_context/ebpf_core.c
For async operations, once the submit path has returned the IOCTL may have already been completed.
CI/CD and targetted testing with conn_tracker.exe.
No.
Resolves: #1085
=> ebpf_core_invoke_protocol_handler can write to the output buffer after the IOCTL completes

netebpfext/net_ebpf_ext_sock_ops.c
net_ebpf_extension_sock_ops_flow_delete fails to deref filter context if the client is detached.
CI/CD with driver verifier.
No.
=> Always deref filter context on flow-delete

include/bpf/bpf.h, include/bpf/libbpf.h
Currently it's not well documented whether the caller is responsible for calling close on the fd returned from various APIs or not, which can lead to bugs in apps.  This PR updates documentation with the answers.
N/A
This is a documentation-only change.
=> Document whether to close fds returned from various APIs

ebpfapi/Source.def, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp
* Remove ebpf_get_next_program (bpf_prog_get_next_id should be used instead)
* Don't export the internal ebpf_map_pin api
Clean up code to reduce footprint.
Tests are updated.
Documentation is updated.
=> Remove more obsolete APIs

.github/workflows/reusable-test.yml
Tests are failing because they cannot complete in 30 minutes.
Temporarily increase the test timeout value.
Other CI/CD runs are failing due to this issue.
Example: https://github.com/microsoft/ebpf-for-windows/runs/6476052133?check_suite_focus=true
This PR fixes test runs.
None needed.
=> Increase test timeout

libs/platform/ebpf_epoch.c
Arm the epoch flush timer when an epoch scheduled work item is queued.
CI/Cd
No.
Resolves: #1109
=> Arm epoch cleanup timer on work item schedule

.github/workflows/cicd.yml, .github/workflows/ossar-scan.yml, .github/workflows/reusable-test.yml
Use the "need" keyword to declare dependencies between jobs.
CI/CD
No.
Resolves: #1066
=> Set interjob dependencies

ebpfapi/Source.def, include/bpf/bpf.h, include/bpf/libbpf.h, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, tests/socket/socket_tests.cpp, tests/unit/libbpf_test.cpp
* Add bpf_prog_load()
* Move prototype for bpf_prog_load_deprecated() from libbpf.h to bpf.h to match libbpf
* Mark as deprecated bpf_object__load_xattr(), bpf_load_program(), and bpf_load_program_xattr() to match libbpf
* Make bpf_load_program_xattr() support the program name field, where previously it was ignored and a random name was used.
Fixes #1073
Test additions included.
Doc changes included.
=> Add (non-deprecated) bpf_prog_load API support

rpc_interface/rpc_interface.idl
Remove unused typedefs left over from when other APIs were removed.
No changes needed.
No changes needed.
=> Remove unused typedefs

libs/platform/user/ebpf_extension_user.c, tests/performance/ExecutionContext.cpp
The user-mode ebpf_extension_load doesn't correctly emulate NMR behavior, causing it to incorrectly match provider and client based solely on the module_id.
CI/CD
No.
=> ebpf_extension_load should check both module_id and interface_id

docs/InstallEbpf.md, images/Dockerfile.install, images/build-images.ps1, images/build-images.sh, images/install-ebpf-for-windows.ps1, manifests/Kubernetes/ebpf-for-windows-daemonset.yaml
This PR is the first step for https://github.com/microsoft/ebpf-for-windows/issues/996 which adds scripts/dockerfile to build host-process container image. It also added manifests which can be deployed in a Kubernetes cluster. 
Note:
- The scripts need to be updated once the release process is finalised. 
- Which repository should the image been pushed?
- Need CI pipeline for building the images and deploy them. 
- Need CD pipeline to push the verified images to the repository.  
Yes. We would need update the doc on how to install ebpf-for-windows with host-process container.
=> Added support for host-process container installation

include/bpf/libbpf.h, libs/api/libbpf_object.cpp, libs/api/libbpf_program.cpp, tests/unit/libbpf_test.cpp
Updated to latest libbpf and bpftool.
Note that the function prototypes for two libbpf APIs changed from returning void to returning int, which required corresponding changes in our repo to build.
None changed
Doxygen docs are updated
=> Update to latest libbpf and bpftool

.github/workflows/scorecards-analysis.yml
Reverts microsoft/ebpf-for-windows#1161
Many failures happened due to https://github.com/ossf/scorecard-action/issues/329 so reverting until that issue is fixed.
=> Revert "Bump ossf/scorecard-action from 1.0.3 to 1.1.1"

include/ebpf_api.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/ebpfnetsh/elf.cpp, libs/thunk/mock/mock.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tests/end_to_end/test_helper.cpp, tests/unit/libbpf_test.cpp
* Populate object->maps when opening a native PE file.
* Fix ebpf_api.cpp bug in reading maps from PE file when a map name length had a multiple of 8 characters (not including the null terminator).  The same bug was previously fixed when reading programs from the PE file.
* Add test to end_to_end.cpp for trying to reuse a pinned map of the wrong type
* Add bpf_object__next_map() API to tests
* Add negative test trying to load a .sys file in user mode
Fixes #1140
Added/updated tests in this PR.
Already documented.
=> Create bpf_map structures from bpf_object__open() on a native file

docs/GettingStarted.md
GettingStarted.md had old hash, resulting in failure to download and execute ps1 script.
Manual.
Doc change.
Resolves: #1059
=> Update hash in GettingStarted.md

tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
Verify all sections returned by ELFIO prior to use.
CI/CD
No.
=> Reject elf malformed section

libs/execution_context/ebpf_core.c, scripts/deploy-ebpf.ps1, tests/end_to_end/test_helper.cpp, tools/port_quota/port_quota.cpp
PR #1132 introduced a regression whereby resolving maps fails.  It wasn't caught since the tests used separate buffers for input vs output for ioctls, whereas the real KM path shares the same memory.
This PR fixes the issue and also updates the tests to share the same memory to catch similar issues in the future.
Fixes #1165
This PR updates tests
No changes needed.  This makes the flow already documented work again.
=> Fix port_quota app usage

libs/execution_context/ebpf_maps.c
Fixes #1223
bpf_map_delete_elem didn't validate the prefix length of an LPM map key.
Found by fuzz tests
No impact.
=> Fix LPM crash with malformed key

libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp
_update_lpm_map_entry should reject call with NULL key
Added new cases to the execution context test.
No.
=> _update_lpm_map_entry should reject call with NULL key

.github/workflows/reusable-build.yml
Increase the timeout of the build to permit the CodeQL build to complete.
CI/CD
No.
Resolves: #1228
=> Increase build timeout to 90 minutes

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml
For the driver tests, `PRE_COMMAND`, `TEST_COMMAND` and `POST_COMMAND` are different ps1 scripts. But in the reusable-test.yml the 3 commands are part of the same job. So if the TEST_COMMAND fails but the POST_COMMAND succeeds, the task is treated as a success.
Fix is to split it into 3 jobs.
CI.
N/A.
=> fix test failure incorrectly treated as success

.github/workflows/reusable-test.yml
driver test post_test script uloads crash dumps if any. So the `Upload any crash dumps` step in reusable-test.yml was failing and so no test artifacts were being uploaded.
CI pipeline.
No.
=> fix cicd github action

.github/workflows/reusable-test.yml
The driver test logs were not getting uploaded in case of failure. Fixed it by putting an always() clause for this step of the workflow.
CI.
N/A.
=> Fix reusable test workflow to upload driver test logs in case of failure.

tools/netsh/ebpfnetsh.rc
The parameters had interface but it was missing from the Usage part
Manual
The help text is the documentation.
=> Fix netsh help text

scripts/config_test_vm.psm1, scripts/install_ebpf.psm1
In the driver tests automation, the ETW traces are stopped as part of the execute_test script. If any tests fail the script is aborted and the ETW session is not stopped. As a result in the cleanup script no ETL logs get collected as part of the result. The fix is to move the wpr command to stop ETW traces to the cleanup script.
CI.
NA.
=> Fix test automation.

docs/eBpfExtensions.md, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/platform/ebpf_platform.h, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, tests/end_to_end/helpers.h, tests/sample/ext/drv/sample_ext.c, tests/unit/libbpf_test.cpp
This PR fixes some of the TODO items for Issue #223 which were left over in the code.
1. `_ebpf_core_protocol_get_object_info` now returns the bpf program and attach types as provided by the extensions.
2. Updated the documentation about the new fields added.
Added new tests, and existing tests also cover the code changes.
Updated docs.
=> Clean up hard coded program type in EC

include/ebpf_api.h, libs/api/Verifier.cpp, tests/end_to_end/end_to_end.cpp
Do some cleanup of Verifier.cpp
* Make a common function between verify as file and verify as memory
* Make some functions not throw exceptions
Fixes #1234
Existing tests
No impact
=> Clean up Verifier.cpp

docs/GettingStarted.md
Fixes #1196
N/A
This is a doc-only change
=> Add note about WDK vsix checkbox when installing WDK

libs/execution_context/ebpf_core.c, libs/platform/ebpf_epoch.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp
Cleanup the handling of flags in epoch code (put them all under the lock).
Set thread affinity on epoch_enter/exit (some paths where missing this).
Unify CPU and thread ebpf_epoch_state_t.
Fix issue with re-arming timer that caused use after free.
Existing CI/CD tests.
Not needed.
=> Fix issued that caused epoch to not cleanup

docs/GettingStarted.md
Fixes #1181
Update guidance to state that clang must be version 11, not the latest version or anything higher than 11.
Already covered, this is a doc-only change.
This is a doc change.
=> Fix LLVM guidance in Getting Started

mainpage.dox
The link on https://microsoft.github.io/ebpf-for-windows/ was wrong
after we rearranged the headers.  This PR fixes the link to point
to the file that actually defines the helpers.
No impact.
=> Fix doc link

include/bpf/libbpf.h, libs/api/libbpf_object.cpp, tests/unit/libbpf_test.cpp
Fixes #1354
bpf_object__open_file() should allow null opts, for consistency with libbpf.
Updated tests
Updated docs
=> bpf_object__open_file() should allow null opts

libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp
Block creating BPF_MAP_TYPE_PROG_ARRAY and BPF_MAP_TYPE_ARRAY_OF_MAPS if value size != sizeof(ebpf_id_t).
Needs new negative tests.
No.
Resolves:  #1353
=> Fix invalid map value size for prog_array and map_array

tools/nuget/ebpf-for-windows.nuspec
The development package needs to include export_program_info to permit building native images.
No.
No.
Resolves: #1330
=> Update nuget package to include export_program_info.exe

docs/GettingStarted.md
Add docs about using the nuget package.
This PR assumes that PR #1372 is merged first.
Fixes #1382 
N/A
=> Add nuget docs

docs/GettingStarted.md, scripts/deploy-ebpf.ps1
And fix doc typos
Make deploy_ebpf script also copy xdp_tests.exe along with other test binaries.
And fix typos in the doc.
Manual.
Doc updates included.
=> Add xdp_tests.exe to deploy script

netebpfext/net_ebpf_ext_drv.c
This PR fixes #1272  by swapping the order of operations to unregister eBPF hook providers and unregistering WFP callouts. Unregistering eBPF hooks for sock_ops will ensure flow contexts are dis-associated from callouts which can then be unregistered successfully.
Private testing + CI.
No documentation changes are needed.
=> Fix unregistering hook providers

docs/GettingStarted.md
Update documentation on xdp_tests.
N/A.
Yes.
=> Update documentation on xdp_tests

ebpfapi/Source.def, include/bpf2c.h, include/ebpf_api.h, libs/api/ebpf_api.cpp, tools/bpf2c/bpf2c.cpp, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
Add a SHA256 hash of the program information used to verify that a program is safe to the program metadata. A subsequent change in EC will verify that the hash matches prior to permitting the attach to complete.
CI/Cd
No.
=> Include hash of program information in metadata

docs/tutorial.md, tools/netsh/ebpfnetsh.rc
PR #1257 removed the default program type, but didn't update the tutorial accordingly.  This PR does so, and also fixes the help output from netsh.
Fixes #1406
Manual
This is a doc change
=> Fix docs on show verification

libs/api_common/windows_platform_common.cpp
This PR changes `get_attach_type_windows()` API to use existing API `_get_section_definition()` instead of iterating over sections definitions.
Existing tests cover the scenario.
NA
Fixes #1304
=> Fix get_attach_type_windows()

docs/tutorial.md
Signed-off-by: James Sturtevant <jstur@microsoft.com>
updates docs to address not needing to build the project to use the eBPF. see https://github.com/microsoft/ebpf-for-windows/issues/1408 and https://github.com/microsoft/ebpf-for-windows/issues/1405
Adds a section with tips for installing ebpf programs with pointers where to learn more.
=> Use installer instead of building from source in the Tutorial

.github/dependabot.yml
This PR enables ```dependabot``` tracking of our ```docker``` components.
This is a ```dependabot``` enhancement and it's testing cannot be automated (hence no existing tests).  
Manually ensured that:
- the 'docker' entry shows up in github->Insights->Dependency Graph->Dependabot tab.
- the 'Check for updates' link (accessible from the 'Last checked xxx...' link for the 'docker' entry) does not show any errors.
- local testing with rolled back nanoserver sha256 tag values (in Dockerfile.install) correctly generates the requisite 'version bump' PR with the latest version.
1. Dependabot alerts need to be enabled (github -> security -> Dependabot) in the forked repository for this to work.
2. The docker image configuration file (named ```Dockerfile``` by default) can be called anything so …
=> Enable docker tracking by dependabot - (#1463)

.github/workflows/reusable-test.yml
Add a step in CICD to copy the .log files generated by bpf2c tests to the `TestLogs` folder, so that they can be uploaded as artifacts.
NA
NA
=> Add bpf2c test logs to test artifacts

ebpfapi/ebpfapi.vcxproj, libs/execution_context/user/execution_context_user.vcxproj, libs/ubpf/user/ubpf_user.vcxproj
Fixes issue #1494 - "*Visual Studio 2019 requesting to retarget `.vcxproj`-s after fresh clone.*".
Tested working on VS2019, with new clone + pre-first build steps.
=> Fix VS2019 requesting to retarget projects.

docs/GettingStarted.md
Updated the "Getting Started" guide with new required xDK versions, which are required to successfully build the `ebpf-for-windows.sln` solution.
Tested working with MSBuild CLI and VS2019, starting from a new clone + pre-first build steps.
Updates to `GettingStarted.md`.
=> Updated GettingStarted guide with new required xDK versions.

scripts/deploy-ebpf.ps1.in
Deploy-ebpf.ps1 doesn't correctly handle passing the name of the target vm.
Manual testing.
No.
=> Fix script to use provide VM name

libs/api_common/store_helper_internal.cpp
Resolves: #1535 and possibly others.
Fix the double free in _load_program_data_information.
Low-memory testing.
No.
=> Fix double free in _load_program_data_information

libs/platform/ebpf_serialize.c
Resolves: #1522
During low memory conditions, ebpf_program_info_t might not be fully allocated, which causes a crash when free the structure.
Low memory testing.
No.
=> Fix crash in ebpf_program_info_free under low memory

libs/execution_context/ebpf_core.c, libs/platform/ebpf_state.c, libs/platform/unit/platform_unit_test.cpp
Resolves: #1523 
Reset global variables to NULL after freeing memory.
Only call ebpf_epoch_exit if ebpf_epoch_enter succeeded.
CI/CD
No.
=> More low memory fixes

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext_tracelog.h, netebpfext/net_ebpf_ext_xdp.c, netebpfext/sys/net_ebpf_ext_drv.c
This PR replaces all KdPrintEx calls in the ```ebpf-for-windows\NetEbpfExt``` project with suitable ```NET_EBPF_EXT_LOG_XXX``` equivalents.
These messages are generally printed on encountering errors from WFP API calls, so added some sample log messages to ensure the new tracelogging macros behave as expected. Specifically:
1. Ensure installation updated and locally modified ```NetEbpfExt.sys``` driver on the test VM device (via WinDbgX).
2. Enable tracing for Windows ebpf drivers.
3. Run ```api_test.exe``` application to generate traces.
4. Extract traces after termination of the ```api_test.exe``` and ensure that the sample trace messages are present in the trace output.
No doc updates needed for this change.
Resolves: #1466
=> Replace KdPrintEx calls (in NetEbpfExt) with Trace logging calls (#1466)

libs/api/ebpf_api.cpp, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp, tests/libs/util/program_helper.cpp
API `ebpf_object_set_execution_type()` was allowing to set incorrect execution types.
This PR fixes that and adds test case for the API.
Added test.
NA
=> Fix API ebpf_object_set_execution_type()

libs/execution_context/ebpf_native.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_platform.h, libs/platform/unit/platform_unit_test.cpp
Resolves: #1506 
The ebpf_hash_table_delete API can fail in out-of-memory scenarios. To resolve this, pre-allocate the replacement block required for removing an element when adding an element to the hash table.
Each hash table bucket entry located at index N contains a pointer to memory needed to create a replacement bucket containing N-1 entries. 
CI/CD
No.
=> Remove failures on ebpf_hash_table_delete path due to low memory

libs/platform/unit/platform_unit_test.cpp
Resolves: #1557 
The test epoch_test_two_threads fails to check the return value from ebpf_epoch_enter, which triggers an assert when it calls ebpf_epoc_exit.
CI/CD
No.
=> Check ebpf_epoch_enter return code and stop if it fails

tests/api_test/api_test.cpp
Resolves: #1553 
Test case was double closing an FD from the OS.
CI/CD.
No.
=> Fix double close of fd in api_test.exe

tests/unit/libbpf_test.cpp
Resolves: #1559
Check for null before comparing strings from libbpf_bpf_prog_type_str.
CI/CD
No.
=> Check for null before comparing strings from libbpf_bpf_prog_type_str

.github/dependabot.yml
This PR will remove the dependency for pip module. Dependebot relies on the dependebot.yml file to check for dependencies and their updates. However, in ebpf-for-windows, we don't have dependencies with python packages. In order to verify that, I used `pip freeze` to check for the directories and packages related to python code. However, this was empty. 
The yml file is modified. Now, if we take these steps, we see that pip dependency is removed. 
- Enable dependabot for the forked repo via 'github->Security->Dependabot'. (This option is available only on forked repos).
- Select the 'Dependabot' tab @ 'github->Insights->Dependency Graph'.
- (OPTIONAL) - Trigger a dependabot scan for pip (by clicking 'last checked xxx -> 'Check for updates' link)
issue related #1492
=> dependabot's tracking for 'pip' is failing

.gitmodules
Dependabot was showing the following errors due to the nonexistence branches :
` Dependabot couldn't fetch the branch/reference for external/ubpf
Your dependency file specified a branch or reference for external/ubpf, but Dependabot couldn't find it at the project's source. Has it been removed?
Dependabot couldn't fetch the branch/reference for external/win-c
Your dependency file specified a branch or reference for external/win-c, but Dependabot couldn't find it at the project's source. Has it been removed? `
This PR will remove the dependency for branches of external/win-c and external/ubpf. Dependebot relies on the .gitmodules file to check for dependencies and their updates. However, in ebpf-for-windows, we use default branches for the following github repos
1. The windows branch in …
=> dependabot's tracking for 'gitmodules' is failing 

libs/platform/user/nmr_impl.cpp, libs/platform/user/nmr_impl.h
Resolves: #1595 
Resolves: #1599 
Only resolve nmr_binding_handle to _nmr::binding when passed from an external source. Use _nmr:binding& internally to avoid race conditions where nmr_binding_handle is invalidated.
CI/CD + run tests that triggered #1595
No.
=> Resolve nmr_binding_handle to only in external calls

.github/workflows/cicd.yml
Only run the low memory tests on a scheduled event until all the issue are resolved.
CI/CD
No.
=> Disable low memory tests until failures are resolved

tests/end_to_end/helpers.h
Resolves: #1607
Client can detach at any time. _single_instance_hook should check for detached client before firing.
CI/CD
No.
=> Check for detached client before firing

libs/ebpfnetsh/elf.cpp
Resolves: #1605
handle_ebpf_show_disassembly and handle_ebpf_show_sections fail to check for NULL being returned from eBPF API.
CI/CD
No.
=> Check for NULL return from ebpf_enumerate_sections and ebpf_api_elf_disassemble_section

tests/end_to_end/test_helper.cpp
Resolves: #1611
Rundown fd to simulate process termination at end of each test.
CI/CD
No.
=> Rundown fd on _test_helper_end_to_end terminate

libs/ebpfnetsh/programs.cpp
Fixes the double free of program fd in `handle_ebpf_add_program()`. This randomly raises exception in kernel CICD tests.
Example: Assertion failure in sample_ext_app.exe - 
https://github.com/microsoft/ebpf-for-windows/actions/runs/3441845845/jobs/5742003130
Existing tests
NA
=> Fix double free of program fd in handle_ebpf_add_program()

libs/api/ebpf_api.cpp
Resolves: #1622
Handles that have been associated with an fd should be closed via _close (and not directly). Closing it directly results in the handle being closed twice).
CI/CD
No.
=> Close handle via fd to prevent orphaned fd

libs/api/ebpf_api.cpp
Resolves: #1614 
Resolves: #1615 
bpf_object__open should fail if it hits a low-memory failure. 
CI/CD
No.
=> bpf_object__open should fail if it hits low memory failure

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_core.h, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_link.h, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_native.h, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/unit/execution_context_unit_test.cpp, tests/fuzz/execution_context.cpp, tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp, tests/libfuzzer/execution_context/libfuzz_harness.cpp, tests/performance/ExecutionContext.cpp
Partially resolves: https://github.com/microsoft/ebpf-for-windows/issues/1542
Annotate execution context API's with _Must_inspect_result_
CI/CD
No.
=> Annotate execution context API's with _Must_inspect_result_

libs/ubpf/kernel/ubpf_kernel.c
Changes in ubpf to support different JIT backends requires corresponding changes in eBPF for Windows.
Implement kernel mode equivalent of [abort](https://www.man7.org/linux/man-pages/man3/abort.3.html).
CI/CD
No.
=> Resolve conflict when updating ubpf

tests/unit/libbpf_test.cpp
Resolves: #1630 
Some of the tests fail to check for failure from bpf_object__open, which causes them to assert when running under low memory simulation.
CI/CD
No.
=> Always check return from bpf_object__open

libs/api/Verifier.cpp
Resolves: #1632
Resolves: #1634
The API allocate_string can fail on low memory, but the surrounding API will return success.
CI/CD
No.
=> Check for allocate_string failure

libs/ebpfnetsh/programs.cpp, tests/end_to_end/netsh_test.cpp
Clear the _ebpf_netsh_objects at the start of the test and verify objects are removed.
Resolves: #1655
Remove ODR violation on _ebpf_objects.
Cleanup netsh's list of bpf_object pointers at the start of the test and check that all are closed at the end of the test.
Orphaned objects in netsh's list of bpf_objects causes use after free when tests fail.
CI/CD
No.
=> Resolve duplicate definition of _ebpf_objects

libs/platform/user/nmr_impl.cpp
Resolves: #1642
Issue #1509 can cause the low-memory tests to hang during CI/CD, which results in a timeout and now dump files. To fix this, assert and loop if NMR deregistration takes > NMR_WAIT_TIMEOUT_SECONDS.
CI/CD
No.
=> Assert on deadlock in shutting down

libs/platform/user/ebpf_low_memory_test.cpp, libs/platform/user/ebpf_low_memory_test.h
Resolves: #1644 
Store the last failed allocation stack in memory to make debugging crash dumps easier.
CI/CD
No.
=> Store last failed allocation stack

tests/end_to_end/test_helper.cpp
Resolves: #1662
Expression short circuiting causes skipping of ebpf_api_close_handle.
CI/CD (low memory fuzzing)
No.
=> Expression short circuiting causes skipping of ebpf_api_close_handle

.github/workflows/cicd.yml, .github/workflows/reusable-build.yml, .gitmodules, docs/isa-support.rst
Use the release bits of bpf_conformance instead of build artifacts.
CI/CD
No.
=> Switch to release of bpf_conformance

libs/api/ebpf_api.cpp, tests/api_test/api_test.cpp
The PR fixes a bug where we would fail the loading of native programs that did not contain any maps.
1. Ensure that the command ```netsh ebpf add program printk.sys``` completes successfully.
2. Add a new test case ```nomap_load_test``` in ```tests\api_test\api_test.cpp``` to cover this specific use case as it was not addressed in the existing test cases.  Ensure that this test case passes successfully.
No documentation updates required.
Fixes: #1683
=> enable loading of native programs with no maps

.github/workflows/reusable-test.yml
Resolves: #1696 
Reduce noise from OpenCppCoverage during CI/CD testing.
CI/CD
No.
=> Reduce noise from OpenCppCoverage during CI/CD testing

libs/api/api_internal.h, libs/api/ebpf_api.cpp, tests/api_test/api_test.cpp
Resolves: #1694
Store module handle as an fd. All of the existing tests rundown open fds during cleanup but have no way of tracking open handles. By switching this to store the handle via fd, it permits the test to automatically close this handle on test assertion faliure.
CI/CD
No.
=> Switch to storing native module handle via fd

.github/workflows/cicd.yml
Now that the low-memory test passes, re-enable it on pull, push, and schedule.
CI/CD
No.
=> Re-enable low memory test

libs/api/ebpf_api.cpp
Resolves: #1649
The function peparse::IterSec relies on returning failure info via the context, but _ebpf_pe_add_section fails to set the failed status in some paths.
CI/CD
No.
=> Mark pe_context as failed on low-memory failure

libs/execution_context/ebpf_native.c
Native module is created when the native driver loads and attaches to EC. But currently the base object of native module is initialized when user mode sends a LOAD_MODULE IOCTL. This causes an assert to be hit in the detach path if for some reason LOAD_MODULE fails / never called.
This PR initializes the base object when the native module is created (at attach step).
Found by low memory test.
NA
NA
=> Initialize native module base object when attach happens

tests/end_to_end/end_to_end.cpp
Closes #1710
Adds missing nullptr check on string before duplication.
CI/CD pipeline.
None.
=> Fix ASAN issue on sanitize_unit_tests

tests/fuzz/execution_context.cpp
Partially fixes #1709 
This PR addresses the following:
- In function `seed_random_engine()`, fixed calling 'emplace_back' concurrently while iterating the container (unsafe), which caused ASAN to output "*AddressSanitizer failed to allocate 0x10000 (65536) bytes of memory at address 0xXXXXXXXX (error code: 1455)"*.
- In test case `TEST_CASE("execution_context_direct", "[fuzz]")`, used `std::fill` algorithm instead of a raw loop (std best practice).
- Added `const` on some container iterations, to enforce safety.
CI/CD pipeline.
None.
=> Fix vector addressing issue. Minor optimizations.

libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/api_common/store_helper_internal.cpp, libs/api_common/windows_platform_common.cpp, libs/platform/ebpf_object.c, libs/platform/ebpf_platform.h, tests/end_to_end/end_to_end.cpp
Replace _strdup with ebpf_duplicate_string, which is instrumented to test low-memory conditions.
Fix bugs in _update_global_helpers_for_program_information uncovered by low-memory testing.
Resolves: #1699
CI/CD
No.
=> Replace _strdup with instrumented ebpf_duplicate_string and fix bugs uncovered

libs/execution_context/ebpf_maps.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_platform.h, tests/performance/ExecutionContext.cpp
Fix heap corruption in LRU hash map under heavy load.
Add more realistic test case for LRU performance.
Fix bug in LRU hash map where it would fail to insert an entry if the hash table was full.
Implement the LRU as a notification callout from hash table when values are allocated, freed, or accessed. This ensures that LRU logic doesn't miss allocation or free if LRU keys.
Resolves: #1751
Resolves: #1741
CI/CD and new tests.
No.
=> Rolling lru test and fix for heap corruption

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml, libs/platform/CMakeLists.txt, libs/platform/user/ebpf_leak_detector.cpp, libs/platform/user/ebpf_leak_detector.h, libs/platform/user/ebpf_low_memory_test.cpp, libs/platform/user/ebpf_platform_user.cpp, libs/platform/user/ebpf_symbol_decoder.h, libs/platform/user/platform_user.vcxproj, libs/platform/user/platform_user.vcxproj.filters
Capture list of allocations made via ebpf_allocate that haven't been freed by ebpf_free.
At ebpf_platform_terminate, log list of outstanding allocations along with stack trace of when the allocation was made.
Future:
Fail tests if there are outstanding allocations. 
CI/CD
No.
=> Add support for logging leaked allocations

docs/Fuzzing.md
fuzzing documentation doesn't include steps to reproduce the crashes using the artifacts. This  PR updates the doc and set an example to better help developers. 
```fuzzing.md``` is updated. 
closes issue #1758
=> Update documentation for fuzz testing

tests/unit/libbpf_test.cpp
Resolves: #1798 
Test fails to free the returned bpf_link object.
CI/CD
No.
=> Free link-object returned from bpf_program__attach_xdp

.github/workflows/cicd.yml, docs/NativeCodeGeneration.md, tests/bpf2c_plugin/bpf2c_plugin.cpp, tests/bpf2c_plugin/bpf2c_plugin.vcxproj, tests/bpf2c_tests/expected/bad_map_name_dll.c, tests/bpf2c_tests/expected/bad_map_name_raw.c, tests/bpf2c_tests/expected/bad_map_name_sys.c, tests/bpf2c_tests/expected/map_dll.c, tests/bpf2c_tests/expected/map_raw.c, tests/bpf2c_tests/expected/map_sys.c, tests/bpf2c_tests/raw_bpf.cpp, tools/bpf2c/bpf2c.vcxproj, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h
This PR adds support for the 32-bit ```JMP``` instruction variants.
Existing tests are sufficient to test this change-set. No new tests needed.
Results of the command ```bpf_conformance_runner.exe --test_file_directory D:\wrk\ebpf-for-windows\external\bpf_conformance\tests\ --exclude_regex lock* --plugin_path .\bpf2c_plugin.exe --plugin_options "--include d:\wrk\ebpf-for-windows\include"``` attached.
No documentation changes needed
Fixes #1667
[bpf_conformance_test_results.txt](https://github.com/microsoft/ebpf-for-windows/files/10322498/bpf_conformance_test_results.txt)
=> Add support for j*32 instructions

libs/api/libbpf_program.cpp
Fixes #1800 
Fix memory leak in `bpf_prog_attach`. 
Existing tests cover this code path.
NA
=> Fix memory leak in bpf_prog_attach 

docs/isa-support.rst
j*32 ebpf instructions are now supported in bpf2c (PR: https://github.com/microsoft/ebpf-for-windows/pull/1792).
This PR updates the entries (for the corresponding j*32 instruction) in the bpf2c column in the 'eBPF Instruction Set' table in the ```ebpf-for-windows\docs\isa-support.rst``` document need to indicate this.
N/A
##Documentation
This is a doc update.
Fixes: #1810
=> Update docs to indicate j*32 ebpf instruction support in bpf2c

.github/workflows/cicd.yml, .gitmodules
Resolves: #1806 
The bpf_conformance test uses artifacts from the bpf_conformance repo instead of building them. Hence there is no need to include this as a submodule.
CI/Cd
No.
=> Remove bpf_conformance submodule

docs/Fuzzing.md, docs/eBpfExtensions.md, ebpfapi/Source.def, include/ebpf_api.h, include/ebpf_program_types.h, include/ebpf_result.h, include/linux/bpf.h, libs/api/bpf_syscall.cpp, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp, tests/end_to_end/helpers.h, tests/unit/libbpf_test.cpp
Resolves: #715
Resolves: #1823 
Resolves: #1818
Add support for the bpf_prog_test_run_opts libbpf API. For this to be used, there needs to be a separate PR to add the required conversion functions to the various extension providers.
CI/CD
No.
=> Add bpf_prog_test_run_opts support

scripts/.check-license.ignore
Closes #1862
`corpus` directories (containing binaries) must be excluded from license checks
=> Remove license-check on 'corpus' directories

tests/end_to_end/test_helper.cpp
Resolves: #661 
Cleanup test_helper.cpp. Add code analysis annotations and switch to variable names that match coding standards.
CI/CD
No.
=> Cleanup test_helper.cpp

tests/bpftool_tests/bpftool_tests.cpp
Fixes #1859
Previously bpftool failed on windows trying to show a map by pin path.
This PR adds a test case for that, and updates to the latest bpftool which does support it on windows.
This PR adds a new test case.
No impact.
=> Fix bpftool show map by pin path

include/ebpf_nethooks.h, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/user/fwp_um.cpp, netebpfext/user/fwp_um.h, tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp, tests/netebpfext_unit/netebpf_ext_helper.cpp, tests/netebpfext_unit/netebpf_ext_helper.h, tests/netebpfext_unit/netebpfext_unit.cpp
* Move functionality common between netebpfext_unit.cpp and netebpfext_fuzzer.cpp into netebpf_ext_helper.cpp
* Add unit tests for BIND, CGROUP_SOCK_ADDR, and SOCK_OPS
Fixes #1869 
No impact.
=> Add unit tests for BIND, CGROUP_SOCK_ADDR, and SOCK_OPS

.github/workflows/cicd.yml
Currently bpf2c_fuzzer and verifier_fuzzer complete last, 8 or so minutes after the next long pole (using https://github.com/microsoft/ebpf-for-windows/actions/runs/3952621659 as a recent example):
* bpf2c_fuzzer: 41 mins
* verifier_fuzzer: 41 mins
* stress: 33 mins
* sanitize_unit_tests: 32 mins
* driver: 31 mins
* fuzzing: 31 mins
* bpf2c: 30 mins
Breakdown within the bpf2c fuzzer and verifier fuzzer runs:
* 23-24 mins to build with fuzzing
* 2 mins to download the build artifact
* 15 mins to run the actual fuzzer using random inputs
Fuzz tests should not be the long pole on a per-PR basis, so drop the fuzz time from 15 mins to 5 mins per run so they are not the bottleneck.
This PR just changes the test duration.
No impact.
=> Shave 8+ minutes off the overall build time

.github/workflows/reusable-build.yml
Only rebuild ebpf-verifer if the commit id has changed.
CI/CD
No.
Resolves: #1925
=> Cache verifier based on commit id and options

tests/end_to_end/netsh_test.cpp
The ```netsh``` unit tests need to ensure correct ebpf core and api initialization at test initialization.  The PR adds that support by instantiating an instance of the ```_test_helper_netsh``` object at the start of every test that was missing this.
No new tests were needed as this issue was seen in some ```netsh``` tests which failed when run in isolation.  The fix was verified by re-running the fixed tests in isolation and ensuring that the tests now pass.
N/A
Fixes: #1636
=> Ensure core, api initialization for netsh unit tests

docs/InstallEbpf.md, images/Dockerfile.install, images/build-images.ps1, images/build-images.sh, images/install-ebpf-for-windows.ps1
This PR fixes https://github.com/microsoft/ebpf-for-windows/issues/1448.
`ebpf-for-windows` has now been released as an MSI package. This PR updated image build scripts to use MSI package and replace the old `install-ebpf.bat` script.
I've tested locally. However, we should set up CI pipelines for each release to test
- Image can be built and pushed to a public repository. 
- Install on Windows nodes in a Kubernetes cluster by applying the manifest and verify everything works.
Doc updated.
=> Use MSI package to build docker image

libs/platform/user/ebpf_leak_detector.cpp
Move an assert in ```_ebpf_leak_detector::dump_leaks()``` that terminates the application before the leak stack trace can be printed.  This assert should fire _after_ the stack trace has been printed to ensure that leaking test is marked as 'failed'.
1. Locally modify an existing test to force a memory leak. (Comment out the ```hook.detach_link(link);``` and
```hook.close_link(link);``` calls in ```end_to_end.cpp:bindmonitor_test()``` to trigger a memory leak) and rebuild the ```unit_tests.exe``` application.
2. set the ```EBPF_MEMORY_LEAK_DETECTION``` to ```true``` and run ```unit_tests bindmonitor-native```.
Output before fix:
```
D:\wrk\ebpf-for-windows\x64\Debug [mem-leak-assert]
PS > ./unit_tests bindmonitor-native
Filters: "bindmonitor-native"
Randomness seeded to: 3603025526 …
```
=> move misplaced assert in memory leak detection stack dump code to the right location.

include/ebpf_api.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp
Resolves: #1618
The ebpf layer APIs need to all be marked as noexcept to prevent propagating exceptions to callers that don't support C++ exceptions. All exceptions should be terminated and handled, but if they aren't this code should terminate the process and log an error.
CI/CD + low memory testing.
No.
=> Mark all ebpf_* api's as noexcept

.github/workflows/ossar-scan.yml
Fixes issue hit in
https://github.com/microsoft/ebpf-for-windows/actions/runs/4009703491 that was introduced by PR #1950 where that PR missed updating the ossar job.  In the linked CICD run, all other jobs (notably including build) were correctly skipped but ossar was not skipped so the run failed because ossar couldn't find the build generated by the skipped build job.  This PR updates the ossar job to be similarly skipped for doc-only changes.
CI/CD
No impact.
=> Fix ossar cicd job for doc-only changes

libs/execution_context/ebpf_link.c
Resolves: #1983
ebpf_link_detach_program calls ebpf_program_detach_link which removes the program ref-count on the link object. If this is the last ref-count, then the link object is destroyed and this function accesses memory after it's been freed.
CI/CD
No.
=> Protect ebpf_link_detach_program with a ref-count

.github/workflows/cicd.yml, installer/Product.wxs, installer/ebpf-for-windows.wixproj
Closes #1985 
This PR adds the possibility of installing the JIT feature with the *Release* build of the eBPF for Windows installer.
The feature can be now triggered by adding `ReleaseJIT='True'` build option to *msbuild*. This switch has been set as default in the `cicd.yml` script, for "regular" build only.
New MSI behavior:
- The *Debug* build will continue to always have the JIT option enabled by design, and **selected** by default.
- The *Release* build will *optionally* (i.e. if built with `ReleaseJIT='True'`) have the JIT option enabled, but **deselected** by default.
Manual testing on bare Nebula VM.
None.
=> Add JIT option for MSI Release bits and CI/CD.

docs/isa-support.rst, external/CMakeLists.txt, libs/execution_context/ebpf_program.c, tests/bpf2c_tests/expected/bindmonitor_dll.c, tests/bpf2c_tests/expected/bindmonitor_raw.c, tests/bpf2c_tests/expected/bindmonitor_sys.c, tests/bpf2c_tests/expected/bindmonitor_tailcall_dll.c, tests/bpf2c_tests/expected/bindmonitor_tailcall_raw.c, tests/bpf2c_tests/expected/bindmonitor_tailcall_sys.c, tests/bpf2c_tests/expected/map_dll.c, tests/bpf2c_tests/expected/map_raw.c, tests/bpf2c_tests/expected/map_sys.c, tests/sample/bindmonitor.c, tests/sample/bindmonitor_tailcall.c, tests/sample/map.c
* Update verifier to latest and accept that some programs will fail verification until functionality is added to PREVAIL.
* Also fix a compiler warning in ebpf_program.c about passing a const pointer to a function that requires non-const.
* Update 3 samples with workaround for temporary verifier limitation (tracked by https://github.com/vbpf/ebpf-verifier/issues/441), by unrolling loops
Fixes #1451
Fixes #1756
Existing tests cover.  The following samples fail to verify with the latest verifier and required updating with workarounds to remove `for` loops:
* bindmonitor.c
* bindmonitor_tailcall.c
* map.c
No impact.
=> Update verifier to latest

docs/InstallEbpf.md, scripts/deploy-ebpf.ps1.in
Add support for deploying eBPF to arbitrary filesystem locations, removing the local admin + local VM requirement.
Resolves #1994 
Tested locally, targeting both the local system and remote filesystems over SMB.
Updated [InstallEbpf.md](https://github.com/mtfriesen/ebpf-for-windows/blob/mtfriesen/deploy_script/docs/InstallEbpf.md).
=> Add support for deploying eBPF to arbitrary filesystem locations

libs/api/ebpf_api.cpp
The function ebpf_ring_buffer_map_subscribe is marked as noexcept, but throws.
CI/CD with low memory.
No.
=> Catch and terminate exception in ebpf_ring_buffer_map_subscribe

libs/api_common/api_common.hpp, libs/execution_context/ebpf_link.c
Resolves: #1987
Once NMR registration completes, the extension can call the program. Ensure that the program is fully initialized before registering with NMR.
CI/CD. Stress testing.
No.
=> Delay NMR registration until link is ready

include/ebpf_result.h, libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_object.c, libs/platform/ebpf_object.h, tests/api_test/api_test.cpp, tests/bpf2c_tests/expected/bindmonitor_tailcall_dll.c, tests/bpf2c_tests/expected/bindmonitor_tailcall_raw.c, tests/bpf2c_tests/expected/bindmonitor_tailcall_sys.c, tests/end_to_end/end_to_end.cpp, tests/sample/bindmonitor_tailcall.c, tests/unit/libbpf_test.cpp
The current 'map <--> contained-objects' relationship uses strong circular references maintained between object-maps (map-of-maps, hash-map-of-maps) and objects (programs and maps).
While this design works for well-behaved user mode applications, it breaks down if the user mode applications do not perform explicit clean-up via the provided clean-up APIs, leading to leaked resources by the way of programs and maps orphaned in memory. This typically happens with user programs that either exit prematurely, do not call the clean-up API calls or crash before they can do so.
This PR proposes a new design solution where we use references to the id table entry for object instead of the object itself. 
**Testing**
_User mode:_
Ensure that the ```unit_tests.exe``` test suite passes successfully. …
=> Resolve circular references using id entry references

netebpfext/net_ebpf_ext_xdp.c
Spotted during code review while working on a different bug: if the eBPF program fails, the XDP extension implicitly passes the packet to the stack and leaks any cloned NBL. Update the XDP extension to explicitly perform an `XDP_DROP` action. Also assert that any unexpected XDP action is not returned and `XDP_DROP` the packet if it does.
Resolves #2002 
CI/CD.
N/A.
=> perform a default action if the XDP program fails

include/ebpf_result.h, libs/execution_context/ebpf_maps.c, libs/platform/ebpf_object.c
This PR addresses the post-merge feedback for the 'circular references fix' [PR](https://github.com/microsoft/ebpf-for-windows/pull/2004)
**Testing**
_User mode:_
- Ensure that the ```unit_tests.exe``` test suite passes successfully.
_Kernel Mode:_
- Ensure that the ```api_test.exe``` test suite passes successfully, multiple times back-to-back.
- The ```epbfcore.sys``` driver can be unloaded and re-loaded successfully after a multiple pass test run.
**Documentation**
No new documentation required.
Fixes: #1509 #1510
=> Incorporate post-merge feedback

libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_extension.c, libs/platform/ebpf_platform.h
Resolves: #2008
NMR client attach contract states that validation of the binding should occur before calling NmrClientAttachProvider. The extension wrapper was incorrectly calling NmrClientAttachProvider first.
CI/CD
No.
=> Invoke _ebpf_extension_client_notify_change before completing binding

docs/GettingStarted.md, libs/platform/user/nmr_impl.cpp, libs/platform/user/nmr_impl.h
Resolves: #2045
Handle concurrent attach failure with deregistration of a provider or client.
CI/Cd
No.
=> Workaround to avoid race between attach failing and unregister

installer/Product.wxs
Closes #2043 
This PR sets the SID of the JIT service to SERVICE_SID_TYPE_RESTRICTED, which fixes the failure in loading ebpf programs (which checks for a specific SID).
It also syncs the artifacts from the previous MSI so that the latest api_tests fully pass.
- CI/CD
- api_tests full pass
n.a.
=> Set JIT compiler's SID to "restricted", sync artifacts for latest api_tests.

Directory.Build.props, tests/libfuzzer/include/libfuzzer.h
Closes #1934 
This PR complements #1935, by removing the preprocessor directives from `libfuzzer.h`, which were pulling in ASAN & fuzzing library dependencies. Now this is done by defining the libraries globally and referencing them locally only within the projects that actually need them.
CI/CD, local build.
n.a.
=> Remove preprocessor library dependencies from `libfuzzer.h`.

libs/execution_context/ebpf_native.c
ebpf_native_load allocates local_service_name, which eventually gets freed by the cleanup_workitem. However, if we fail to allocate the cleanup_workitem, then local_service_name leaks.
Manually free local_service_name if we fail before the cleanup_workitem can be allocated.
Resolves #2092 
Tested in XDP stress test. Other eBPF issues are still being hit, but this one seems fixed.
N/A.
=> Fix local_service_name leak in ebpf_native_load

libs/api_common/store_helper_internal.cpp, libs/api_common/windows_platform_common.cpp, scripts/install_ebpf.psm1
Currently, the extension driver (netebpfext) already populates HKLM. But the user mode reads from HKCU (which is populated by executing `export_program_info.exe`. This all works normally, but if the user mode app is running as a LocalSystem service, it is not able to read HKCU ebpf store, and program load fails. 
This PR makes changes in `api_common` to first read the eBPF store from HKLM and then from HKCU. This allows user mode app running as localsystem to be able to load programs.
Updated kernel CICD test scripts to _not_ call `export_program_info.exe`, so that user mode ends up reading the store values from HKLM path.
No.
=> Update api_common to first read eBPF store values from HKLM path.

libs/ebpfnetsh/elf.cpp, libs/ebpfnetsh/links.cpp, libs/ebpfnetsh/maps.cpp, libs/ebpfnetsh/pins.cpp
Closes #2052 
The following functions or structs in the source codes need SAL annotation. Please note that these annotations needed to match what was defined in public file of `NetSh.h`
1. `elf.cpp`
```
handle_ebpf_show_disassembly
handle_ebpf_show_sections
handle_ebpf_show_verification
```
2. `maps.cpp`
```
handle_ebpf_show_maps
```
3. `pins.cpp`
```
handle_ebpf_show_pins
``` 
4. `links.cpp`
```
handle_ebpf_show_links
```
5. ` svc_main.cpp` : Already addressed in PR #2019 
```
service_control_handler
report_service_status
service_init
service_main
```
6. Tried to remove `_In_` from pass by value types in `wer_report_test_wrapper.cpp` . However, they can't be removed to match header file. If removed, the CICD build will fail. 
```
WerReportAddDump_test
WerReportCreate_test …
```
=> SAL annotation for several source codes

.github/workflows/reusable-test.yml, .github/workflows/scorecards-analysis.yml
More of issue #2076.  Without this, the scorecards workflow doesn't run on queued merge requests.
Also fixes #2116
In CI/CD, since this only affects github CICD.
No impact
=> Enable scorecards to run in merge queue

netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_sock_addr.c
WFP may invoke a callout for the same connection for [re-authorization](https://learn.microsoft.com/en-us/windows/win32/fwp/ale-re-authorization). eBPF extension should not invoke the eBPF program upon reauthorization. This fix is related to the issue #2059.
Also, this PR takes into account if a callout with higher weight already redirected the connection to a local proxy. In that case, the expected thing to do would be to permit the connection un-modified. When the proxy sends a new outbound request to the original destination, the eBPF callout would get another look at the connection.
CI.
No.
=> Handle re-auth case.

.github/workflows/scorecards-analysis.yml
The scorecard step is not currently supported in the merge queue itself as documented in the github action (see #2118).  So make the scorecards workflow run and simply report success so that CI/CD runs in the merge queue don't fail as a result.
Fixes #2118
CI/CD.  Issue #2118 references an example of a failure in CI/CD that this should fix.
No impact.
=> Skip scorecard steps in merge queue

docs/SelfHostedRunnerSetup.md, docs/eBpfExtensions.md, include/ebpf_nethooks.h, libs/execution_context/ebpf_program.c, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_prog_info_provider.c, netebpfext/net_ebpf_ext_prog_info_provider.h, netebpfext/net_ebpf_ext_program_info.h, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c, tests/netebpfext_unit/netebpf_ext_helper.cpp, tests/sample/cgroup_sock_addr2.c, tests/sample/ext/drv/sample_ext.c, tests/sample/ext/drv/sample_ext_drv.c, tests/sample/ext/inc/sample_ext_helpers.h
This PR provides a new (temporary) 'program type specific' helper function ```bpf_sock_addr_get_current_pid_tgid(void *ctx)```.
This helper function is a _Windows_ _Only_ (stopgap) feature and is provided as a work-around for an existing edge-case implementation design bug in the currently supported 'global' ```bpf_get_current_pid_tgid()``` helper function.
This 'program type specific' helper function _may_ be removed once the implementation design issues for the global version are resolved.
Ensure single and multi-(VM) machine unit tests pass successfully.
Added documentation for the new call.
=> Export new sock_addr specific helper function (windows only)

libs/api/ebpf_api.cpp
`_initialize_ebpf_object_native` calls `_clean_up_ebpf_object` in its failure path, which releases all resources in the object. This leads to all kinds of errors, including double frees of memory and closures of OS handles.
This usage of `_clean_up_ebpf_object` is unlike the other `_initialize_ebpf_object*` routines, which release only locally-created resources. Fix this misbehavior by aligning with the clean-up-what-you-created pattern.
Resolves #2122 
Tested in XDP stress test, plus any coverage in eBPF CI/CD.
N/A.
=> _initialize_ebpf_object_native: only clean up locally-created objects

.github/workflows/reusable-test.yml, .github/workflows/scorecards-analysis.yml, .github/workflows/update-docs.yml
Block CICD workflow access to Internet endpoints other than those explicitly allowed, to harden workflows.
Changes come from the step-security recommendations based on the previous logging enabled:
* reusable-test.yml: https://app.stepsecurity.io/github/microsoft/ebpf-for-windows/actions/runs/4276930416
* scorecards-analysis.yml: https://app.stepsecurity.io/github/microsoft/ebpf-for-windows/actions/runs/4272794709
* update-docs.yml: https://app.stepsecurity.io/github/microsoft/ebpf-for-windows/actions/runs/4265294976 
See
https://github.com/step-security/harden-runner#restrict-egress-traffic-to-allowed-endpoints for docs on egress-policy.
Fixes #2142
CI/CD
No impact.
=> Set github workflow egress-policy to block

tests/unit/libbpf_test.cpp
Fix crash in libbpf_load_stress on low memory.
Low memory full tests caught this.
No.
=> Fix low-memory failure in libbpf_load_stress

docs/GettingStarted.md, docs/ReleaseProcess.md, installer/Product.wxs
Closes #2065
Closes #2160 
This PR syncs the MSI's directory tree for `/include/libbpf` to the one in the nuget package:
- Moves `/include/libbpf/*` to `/include/libbpf/include/*`.
- Adds `/include/libbpf/src/*`.
CI/CD, local install.
- GettingStarted.md
- ReleaseProcess.md
=> Sync msi's libbpf directory tree to nuget

netebpfext/user/fwp_um.cpp, netebpfext/user/fwp_um.h, tests/netebpfext_unit/netebpfext_unit.cpp
Closes #2077 
`FWP_CONDITION_FLAG_IS_REAUTHORIZE` is defined as a parameter for condition to reauthorize a connection. Missing tests for the following APIs:
These tests are invoked in `netebpfext_unit.exe`, inside `sock_addr_invoke` API. 
Build the visual studio successfully without any error on local machine.
Loading and running the following tests on the VM to make sure they are passing :
```
PS C:\Debug> .\netebpfext_unit.exe -d yes
Randomness seeded to: 24456912
0.014 s: query program info
0.008 s: classify_packet
0.007 s: xdp_context
0.007 s: bind_invoke
0.009 s: bind_context
0.010 s: sock_addr_invoke
10.017 s: sock_addr_invoke_concurrent1
10.017 s: sock_addr_invoke_concurrent2
10.007 s: sock_addr_invoke_concurrent3
0.004 s: sock_addr_context
0.006 s: sock_ops_invoke
0.004 s: …
```
=> Add a connection reauth test in sock_add tests

include/ebpf_extension.h, installer/Product.wxs, libs/platform/ebpf_platform.h
Resolves: #2146
Resolves: #2147
Extension writes need access to certain structures and types. Moving these types from ebpf_platform.h to ebpf_extension.h allows developers to more easily implement extensions.
None needed. No impact to existing code.
No.
=> Move extension definitions to their own file

.github/workflows/cicd.yml, libs/platform/user/kernel_um.h, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_sock_ops.c
This PR does the following:
1. Enable memory leak detection for `fault_injection_netebpfext` tests.
2. Fix memory leaks discovered by the test.
3. Remove `unit_tests_leak_detection`, `netebpfext_unit_leak_detection` and enable `leak_detection` in `unit_tests`, `netebpf_ext_unit_tests`.
This PR adds the memory leak detection test.
NA
=> Fix memory leaks in netebpfext

.github/workflows/cicd.yml, .github/workflows/reusable-build.yml, docs/ReleaseProcess.md
- Add new `build_msi` flag in `reusable-build.yml` and embed automatic artifact name/configuration in the output name, for more flexibility in adding multiple msi/nuget packages for multiple ci/cd builds.
- Build the nuget package & msi on the `regular` build only.
- Uniform artifact name and task descriptions.
CI/CD.
`ReleaseProcess.md`
=> Add build_msi flag, build nuget on regular build only.

ebpfcore/ebpf_drv.c, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_core.h, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/platform/ebpf_epoch.c, libs/platform/ebpf_epoch.h, libs/platform/ebpf_platform.h, libs/platform/ebpf_state.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp, tests/end_to_end/end_to_end.cpp, tests/performance/ExecutionContext.cpp, tests/performance/platform.cpp
Ensure that all calls from ebpf_drv.c are to API's that call epoch enter/exit as appropriate.
Replace dynamically sized thread entry table with fixed capacity thread entry table with block on full semantics.
Resolves: #2164
Resolves: #2165
CI/CD
No.
=> Wrap calls from ebpf_drv.c in epoch calls

installer/ebpf-for-windows.wixproj, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_tracelog.h, netebpfext/sys/netebpfext.vcxproj, scripts/run_driver_tests.psm1, tests/connect_redirect/connect_redirect_tests.cpp
This PR simplifies the connect_redirect callout's logic in the sock_addr hook. The callout now stores only the connections that are blocked by the eBPF program. The auth_connect layer callout would permit all connections by default, unless they are found in the blocked connection list. This change was made with the assumption, that in a typical deployment, eBPF program will permit majority of the connections that it will inspect. This way, the frequency of allocation for connection contexts would be reduced. Plus, the overall callout logic is simplified.
Refactored connect_redirect tests to have 80 test cases instead of 4 giant test cases with 20 sub-variations each.
TraceloggingWrite seems to be increasing stack frame size which is being flagged by static analysis tool. To temporarily …
=> Redirect list

libs/platform/user/ebpf_leak_detector.cpp, libs/platform/user/ebpf_leak_detector.h
Debugging asserts from _ebpf_leak_detector::dump_leaks due to leaked memory is hard as the log is written to the console which is not always captured. To make it easier to debug, this change also writes the log to an in memory buffer.
CI/CD
No.
=> Store leaked stacks in memory

libs/api/ebpf_api.cpp, libs/api_common/store_helper_internal.cpp, libs/execution_context/ebpf_native.c, netebpfext/user/fwp_um.cpp
For each Memory leak call stack and SIGSEGV, please refer to the analysis attached in #2101 
This PR was tested with fault injection conditions added for the following NMR APIs.
1. NmrRegisterProvider
2. NmrDeregisterProvider
3. NmrWaitForProviderDeregisterComplete
FYI, Issue #2101 will be addressed in incremental commits.
_Do any existing tests cover this change? Yes
Are new tests needed?_ No
No
=> Simulate NMR API failures: Fix memory leaks and segmentation fault

docs/EpochBasedMemoryManagement.md, include/ebpf_extension.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/platform/ebpf_epoch.c, libs/platform/ebpf_epoch.h, libs/platform/unit/platform_unit_test.cpp, tests/performance/ExecutionContext.cpp, tests/performance/platform.cpp
Resolves: #2126 
Resolves: #2260
Resolves: #2261
Epoch memory management code shouldn't need to hard affinitize threads to CPUs. The reason for this was so that the exit epoch could find the thread entry. Instead, the change is to have the caller track the epoch state entry for the epoch.
CI/CD
No.
=> Remove hard affinity in epoch code

libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_program.c, libs/platform/ebpf_crypto_hash.c, libs/platform/user/nmr_impl.cpp
This PR addresses 3 crashes when fault injection is enabled in nmr apis.
Please see the details of call stack in #2101 
_Do any existing tests cover this change? Yes
Are new tests needed?_ No
_Is there any documentation impact for this change?_ No
=> Simulate NMR API failures: Fix SIGSEGV crashes

libs/api/ebpf_api.cpp
Resolves: #2278 
The function _link_ebpf_program calls ebpf_link_close on failure, which attempts to close the fd associated with the link object. If the function fails before allocating an fd, it will attempt to close fd 0.
CI/CD + new km stress test.
No.
=> Initialize new_link fd to ebpf_fd_invalid

docs/NativeCodeGeneration.md
ELF is an acronym for Executable and Linkable Format.
=> Correct the ELF acronym

tests/api_test/api_test.cpp, tests/bpf2c_tests/raw_bpf.cpp, tests/connect_redirect/connect_redirect_tests.cpp, tests/end_to_end/end_to_end.cpp, tests/libfuzzer/bpf2c_fuzzer/bpf2c_fuzzer.vcxproj, tests/libfuzzer/bpf2c_fuzzer/libfuzz_harness.cpp, tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp, tests/libfuzzer/execution_context/libfuzz_harness.cpp, tests/libfuzzer/include/libfuzzer.h, tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp, tests/libfuzzer/verifier_fuzzer/libfuzz_harness.cpp, tests/libs/common/ebpf_watchdog_timer.h, tests/libs/common/watchdog.h, tests/netebpfext_unit/netebpfext_unit.cpp, tests/sample/ext/app/sample_ext_app.cpp, tests/socket/socket_tests.cpp, tests/unit/wer_report_test_wrapper.cpp, tests/xdp/xdp_tests.cpp, tests/xdp/xdp_tests.vcxproj
Part 1 of #2269 
Add code to fire a watchdog timer if an individual test takes longer than 300 seconds.
CI/CD
No.
=> Raise STATUS_ASSERTION_FAILURE on test timeout

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_tracelog.h, netebpfext/user/fwp_um.cpp, netebpfext/user/fwp_um.h
Windows HLK tests for WFP requires drivers to add a provider object to identify the vendor. The changes were to add the provider to pass the HLK tests.
CI.
Not required.
=> Add a WFP provider object.

libs/platform/ebpf_epoch.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp
Resolves: #2271 
Guard epoch logic using critical regions.
CI/CD
No.
=> Call KeEnterCriticalRegion during epoch

README.md
Fixes the link for the CI/CD badge so it goes to the proper place.
No impact.
=> Fix CI/CD Badge

tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c, tests/connect_redirect/connect_redirect_tests.cpp, tests/sample/cgroup_sock_addr2.c, tests/socket/socket_tests_common.h
This PR adds a check in the connect redirect test that source port in sock_addr_ctx given to ebpf program is never 0.
This PR adds test.
NA
=> connect_redirect tests: Add check that source port is not 0

libs/platform/user/ebpf_platform_user.cpp
Add fault injection condition in  _initialize_thread_pool() for ebpf_platform_initiate() in ebpf_platform_user.cpp
1. Added fault injection in _initialize_thread_pool().
2. Without initialization ( InitializeThreadpoolEnvironment()), CreateThreadpoolWork OS API and other thread apis give access violation. See both the call stacks below. Hence the fault injection is called after the static callback_environment initialization is done.
```
(8cd0.13564): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
ntdll!InsertTailList+0x4 [inlined in ntdll!TppCleanupGroupMemberInitialize+0x182]:
00007ff9`d6d22e86 483901          cmp     qword ptr [rcx],rax ds:feeefeee`feeefeee=???????????????? …
```
=> ebpf_platform_user.cpp: Add Fault injection condition in _initialize_thread_pool for OS API

libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp, tests/end_to_end/end_to_end.cpp
Added fault injection in ebpf_platform_user.cpp OS apis.
_Do any existing tests cover this change? Yes
platform_unit_test.cpp:  
- Test case: trampoline_test
Coverage for ebpf_protect_memory
- Test case: extension_test 
Coverage for ebpf_guid_create:
- Test case: access_check
Coverage for ebpf_validate_security_descriptor
Coverage for ebpf_access_check
Are new tests needed? Yes
In platform_unit_test.cpp:  
- Added Test case: get_authentication_id
Existing test cases: 
unit_tests.exe : Passed
netebpfext_unit.exe: Passed
_Is there any documentation impact for this change?_ No
=> Simulate OS api failure: ebpf_platform_user.cpp api

include/ebpf_program_attach_type_guids.h, include/ebpf_program_types.h, include/ebpf_store_helper.h, libs/api_common/store_helper_internal.cpp, libs/api_common/windows_helpers.cpp, libs/api_common/windows_platform_common.cpp, libs/execution_context/ebpf_program.c, libs/platform/ebpf_serialize.c, libs/platform/unit/platform_unit_test.cpp, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_program_info.h, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, tests/end_to_end/helpers.h, tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp, tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp, tests/sample/ext/drv/sample_ext.c, tests/sample/ext/inc/sample_ext_program_info.h, tools/export_program_info/export_program_info.cpp
Allow various structs to be const so that an extension writer doesn't get build warnings or errors when trying to register a const struct.
Fixes #2145
No impact.  Existing CI/CD.
No impact.
=> Allow various structs to be const

docs/eBpfExtensions.md, include/ebpf_extension.h, libs/execution_context/ebpf_link.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_hook_provider.h, tests/sample/ext/drv/sample_ext.c, tests/sample/ext/drv/sample_ext.h
The `_ebpf_link_instance_invoke_batch_end` definition in the eBPF implementation diverged from the `ebpf_program_batch_end_invoke_function_t` definition in the extension header: a `state` parameter was added to the implementation, but not the header.
- Update the header to match the implementation.
- To let the compiler catch this error, both in the eBPF project and in extension projects, explicitly define the dispatch table used to invoke programs.
- Remove redundant (and erroneous) definitions throughout the eBPF test and sample codebase.
Resolves #2310 
Builds locally. CI/CD should cover the rest.
Note: the batch begin/invoke/end routines do not appear to be tested via NPI dispatch tables in the eBPF project.
Documentation updated.
=> Fix ebpf_program_batch_end_invoke_function_t definition and clean up NPI

libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h
Resolves: #2316
The native module code registers for address change notification with the program object, but fails to unregister when unloading. This results in a notification for address change accessing freed memory.
CI/CD + kernel stress.
No.
=> Deregister for helper function change when deleting native module

netebpfext/net_ebpf_ext.c
Fixes #1971
Set the WFP sublayer weight to maximum. This will increase the chance of eBPF callout to be invoked first.
CI/CD
NA
=> Set WFP sublayer weight to maximum

libs/execution_context/ebpf_native.c
Fixes #2326
Fixes use after free in ebpf native module. When all program references have been removed, native module queues a workitem to unload the driver. It is possible that the driver is unloading at the same time. This can cause a race where one thread decrements the ref count to 1, then proceeds to queue a workitem, but second thread makes the ref count 0 at the same time which frees the native module memory.
Fix is to hold the module lock until the workitem is queued to ensure ref count does not go down to 0.
existing CICD and new stress tests
NA
=> Fix use after free in native code.

netebpfext/net_ebpf_ext_xdp.c, netebpfext/user/ndis_um.cpp
1. Added fault injection condition in ndis OS API functions in ndis_um.cpp file.
2. Fixed a crash in _ebpf_xdp_context_delete() in net_ebpf_ext_xdp.c, which was triggered by xdp_context test case. Call stack details in #2101 
_Do any existing tests cover this change? Yes 
=> Add fault injection in ndis_um.cpp

.github/workflows/reusable-build.yml
Crashes occurring during the bpf2c run need to be investigated and fixed. Currently there is no way to determine what failed.
CI/CD
No.
=> Capture crash dumps during build phase and upload them

.github/workflows/scorecards-analysis.yml
Note that we tried this before in PR #1161 and had to revert it in PR #1174 but the issue it was blocked on seems to be fixed and this should fix the various scorecard failures we are now seeing.
MsQuic which originally did the same as we did already snapped to latest as can be seen at
https://github.com/microsoft/msquic/blob/main/.github/workflows/scorecards-analysis.yml and its scorecard runs are passing.
Match msquic config which is passing.
Similarly, l3afd was hitting the same scorecard failures we are, and https://github.com/l3af-project/l3afd/pull/230 makes this same fix and scorecards pass with it.
No impact.
=> Update scorecard workflow to latest

libs/api_common/store_helper_internal.cpp
Fixes #2381
Fixes #2360
If netebpfext is running, it populates HKLM ebpf store. ebpfapi has logic to prefer HKLM over KHCU, if HKLM is present. This causes the build to fail as the HKLM store will not contain data related to sample_ext.
Fix is to prefer HKCU over KHLM.
Note: This issue should be completely fixed once #2339 is fixed.
CICD
NA
=> Prefer HKCU over HKLM for ebpf store

.github/codecov.yml
This PR corrects the `after_n_builds` code coverage upload counter value in `.github/codecov.yml`.  It also adds a comment describing the count calculation algorithm.
CI/CD.
=> Fix code coverage upload count in .github/codecov.yml.

libs/execution_context/ebpf_link.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_extension.c
Resolves: #2328
Fix invalid state transitions in link state machine.
CI/CD + km stress.
No.
=> Harden link state machine

.github/workflows/reusable-build.yml
To enforce Build-x64-FuzzerDebug upload when a crashdump is encountered for fuzzer build failure.
[Note: Still the RCA for FuzzerDebug build failure is not known. So, this PR can help with symbols, when the problem is hit]
_Do any existing tests cover this change? Are new tests needed? No
=> Get Build-x64-FuzzerDebug build output even on failure

netebpfext/net_ebpf_ext.c, netebpfext/user/fwp_um.cpp
- Added fault injection condition in the following WFP OS APIs:
1. FwpmFilterDeleteById0
2. FwpmTransactionBegin0
3. FwpmFilterAdd0
4. FwpmTransactionAbort0
5. FwpsCalloutRegister3
6. FwpmCalloutAdd0
7. FwpsCalloutUnregisterById0
8. FwpmEngineOpen0
9. FwpmProviderAdd0
10. FwpmSubLayerAdd0
11. FwpmEngineClose0
12. FwpsInjectionHandleCreate0
13. FwpsInjectionHandleDestroy0
-  In net_ebpf_extension_initialize_wfp_components(), added a call to close the session and to unregister the callouts for the failure paths.
- Fixed an issue in net_ebpf_extension_initialize_wfp_components(), where the failure status was overwritten with FwpmTransactionAbort() return value and returned as success to the caller. This led the code flow to continue with the assumption that the initialization of wfp …
=> Add Fault Injection in WFP OS APIs

libs/api/ebpf_api.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_native.c
Fixes #2354
In case of native module load failure, currently handles for all the maps and programs created are closed synchronously. That causes the thread to call `epoch_enter` twice. This can cause a deadlock if multiple threads are doing the same.
This PR changes the logic to allocate a `handle cleanup` workitem and context, and in case of failure, use this workitem and context to close the handles.
Existing tests and stress tests.
NA
=> Close native object handles in a work item in case of failure

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_tracelog.c, netebpfext/net_ebpf_ext_tracelog.h, netebpfext/net_ebpf_ext_xdp.c, netebpfext/sys/netebpfext.vcxproj
`TraceLoggingWrite` macro pushes distinct local variables on stack for each trace statement. This causes the stack to bloat. There is a chance of bugcheck due to stack size crossing the limit, since there are some functions with a lot of trace statements. The fix is to wrap the tracelog macros in a function (annotated with `__declspec(noinline)`) and invoke the functions instead of the macros directly. There are several helper macros that in turn the tracelog macros and takes trace level and trace keyword as macro parameters. If we now make the keywords as parameters of the wrapper function, the compiler generates error as the Tracelog macros expect literals.
```
uint64_t foo = 1;
TraceLoggingWrite(                                                    
net_ebpf_ext_tracelog_provider, …
```
=> trace_refactor.

.github/workflows/cicd.yml, scripts/vm_run_tests.psm1, tests/api_test/api_test.cpp, tests/bpftool_tests/bpftool_tests.cpp, tests/connect_redirect/connect_redirect_tests.cpp, tests/libs/util/CMakeLists.txt, tests/libs/util/native_helper.cpp, tests/libs/util/native_helper.hpp, tests/libs/util/test_util.vcxproj, tests/libs/util/test_util.vcxproj.filters, tests/sample/ext/app/sample_ext_app.cpp, tests/socket/socket_tests.cpp
This PR has the following changes:
1. Add new `driver_native_only` test which runs driver tests on `native_only` artifacts.
2. Update the driver test cases:
1. If a test already contains both JIT and NATIV variants, disable the JIT test for `native_only` run.
2. If the test only uses `.o` file, update the test to use `.o` file for regular test, and `.sys` file for `native_only` test.
3. Since quick unloading and reloading of native driver can fail, add `native_module_helper` class which creates a unique copy of the native driver, so that the programs can be immediately reloaded instead add a wait / delay.
4. Reverts the recent regression in connect_redirect tests.
This PR adds new tests.
NA
=> Add kernel tests for native_only build.

libs/execution_context/ebpf_native.c, libs/platform/user/ebpf_platform_user.cpp, tests/end_to_end/test_helper.cpp
Fixes #2411
Fixes #2413 
This PR fixes random test failures which are caused due to timing issue. In kernel, IO_WORKITEMS guarantee that the driver will not be unloaded until all the queued work items are completed. In the user mode mock though, there is no such guarantee currently. This causes the memory leak and other checks to be executed _before_ all the queued work items have completed.
This PR adds a wait where the `test_helper` dtor waits for all preemptible work items to complete before performing various checks.
Existing CI/CD
NA
=> Wait for preemptible work items to complete in UM mock.

.github/workflows/reusable-cmake-build.yml, .github/workflows/reusable-test.yml
This PR adds a `skip_check` step for cmake builds. Currently when a PR is added to merge queue, all steps are correctly skipped except the `cmake` builds.
Existing CICD
NA
=> Add skip_action check in reusable_cmake_build yml

tools/bpf2c/bpf_code_generator.h
properly initialize the pe_section_name_counter
bpf2c crashes in set_pe_section_name during call to strncpy_s when provided invalid prefix_length as count due to integer underflow. the root cause is pe_section_name_counter is not appropriately initialized to 0
=> propertly initialize pe_section_name_counter

libs/platform/user/kernel_um.cpp, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/user/fwp_um.cpp
Added Fault Injection to the list of Kernel OS APIs listed.
1. Skip: IoAllocateMdl
2. Skip: IoAllocateWorkItem
3. Added: MmGetMdlByteCount
4. Skip: ExAcquireRundownProtection
5. Skip: ExAcquireSpinLockExclusiveEx
6. Skip: ExAcquireSpinLockSharedEx
7. Skip: QueryInterruptTimeEx
8. Skip: RtlCreateAcl
9. Skip: RtlLengthSid
10. Added: RtlAddAccessAllowedAce
11. Skip: RtlSetDaclSecurityDescriptor
12. Skip: RtlCreateSecurityDescriptor
13. Added: SeAccessCheckFromState
14. Skip: KeGetCurrentIrql
15. Skip: PsGetCurrentProcessId
16. Skip: PsGetCurrentThreadId
_Do any existing tests cover this change? Yes.
Coverage of the above APIs is already in test cases with _netebpf_ext_helper user.
```
_netebpf_ext_helper
| -- net_ebpf_ext_register_providers
| -- net_ebpf_ext_sock_addr_register_providers() …
```
=> Add Fault Injection in Kernel OS APIs in kernel_um.cpp

Directory.Build.props
Closes #2427
Disables JIT (and interpret) from "regular-native_only" CI/CD build, on all configurations.
CI/CD.
n.a.
=> Disable JIT (and interpret) from "regular-native_only" CI/CD build

scripts/Test-FaultInjection.ps1
During fault injection, set a watchdog timer in PS to kill the process if it takes more than 5 minutes to execute.
CI/CD
No.
=> Kill test process if it takes more than 5 minutes to execute

libs/platform/ebpf_object.c
Resolves: #2435 
The function _ebpf_object_tracking_list_insert always returns success, even if it fails to allocate an object_id.
CI/CD + stress
No.
=> _ebpf_object_tracking_list_insert returns success if table is full

libs/execution_context/ebpf_link.c
This PR fixes a kernel mode `assert`.
The root cause here is that the `assert` itself as it is checking for the link state prematurely. Specifically:
Assuming two threads were racing to detach a program and end up invoking `ebpf_link_detach_program`, only one would acquire `link->lock` causing the other to block.  (At this instant, the detach operation needs the link state to be either 'Attached' (provider loaded) or 'Attaching' (waiting for the provider to load). Any other state causes the ebpf_link_detach_program call to exit.)
The running thread then sets the link state to 'Detaching', sets some local variables and releases the lock prior to
calling `ebpf_program_unload` to detach from the provider.  This results in the invocation of the `_ebpf_link_extension_changed_callback` callback …
=> Remove premature assert

tests/stress/ebpf_mt_stress.h, tests/stress/ebpf_stress_tests.cpp, tests/stress/km/stress_tests_km.cpp, tests/stress/readme.md, tests/stress/um/stress_tests_um.cpp
Code clean-up and common code refactoring of the tests in the 'Kernel mode Multi-threaded stress tests' suite. 
clean-up of existing test collateral.
Fixes #2463
=> KM Multi-threaded stress tests - Code clean-up, duplicate code refactoring

libs/api/ebpf_api.cpp
Resolves: #2512 
The function _initialize_ebpf_maps_native double frees the map entry on failure.
CI/CD + fault injection.
No.
=> Remove double free of ebpf_map_t

tests/end_to_end/helpers.h
Resolves: #2511 
C++ destructors are noexcept by definition. Throwing from a destructor is a noexcept violation which results in abort. Avoid this by making best effort to cleanup in destructors.
CI/CD
No.
=> Don't throw exceptions from ~_single_instance_hook

libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_program.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_handle_kernel.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp, tests/api_test/api_test.cpp
Fixes #2457
Earlier fix done in PR #2395 was incomplete. The previous fix queued a workitem to close the program and map handles in the case of native module load failure. Closing the handles in system worker thread fails with `INVALID_HANDLE` as the handle is created for type `UserMode`, and the worker thread is running in system context.
The fix is to attach the current process to the worker thread to be able to close the handles. The new fix does the following:
1. take reference on the current process, and pass process info to the worker thread.
2. worker thread attaches process, closes handles, detaches process and release process reference.
Added new kernel tests.
NA
=> Fix closing native program / maps handles in system worker thread. 

tests/stress/km/stress_tests_km.cpp
This PR adds some runtime tweaks to fix some non-test-related but intrusive issues. Specifically:
1. Ignore 'advisory' return status codes from OS/runtime APIs to start/stop NetEbpfExt (i.e., 'driver already stopping/stopped'/'driver start-pending/already started').  These were treated as 'fatal' errors leading to false positives.
2. Plumb test runtime awareness deeper into long running functions to ensure as timely test termination as possible.  Currently, in some cases the actual runtime far exceeded the specified runtime.
3. Separate out test cases for 'JIT' and 'native' ebpf programs into respective 'test classes'.  This now allows us to run 'JIT-only' or 'native-only' tests if required. (Default is still 'all').
This is test collateral.
No documentation changes required.
Fixes #2520
=> kernel mode stress test - tweak extension stop/restart, better handling of test runtime

netebpfext/net_ebpf_ext_sock_addr.c
This PR fixes a minor bug in the sock_addr tracing where source IP was being printed instead of destination IP.
CICD
NA
=> Fix sock_addr tracing bug

.github/workflows/reusable-build.yml
closes #2538 
Scheduled run failed:
https://github.com/microsoft/ebpf-for-windows/actions/runs/5149210014/jobs/9271934842
Same for other PRs trying to build.
The "Create verifier project" fails with error:
CMake Error at CMakeLists.txt:4 (project):
The CMAKE_C_COMPILER:
C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/HostX64/x64/cl.exe
is not a full path to an existing compiler tool.
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md says
CICD
N/A
=> Fix CICD failure 

.github/workflows/reusable-build.yml, libs/api/libbpf_internal.h, libs/execution_context/unit/execution_context_unit_test.cpp, tests/end_to_end/test_helper.cpp, tests/libs/util/socket_helper.cpp
Looks like the MSVC version has again changed from `14.35.32215` to `14.36.32532` and broke the build for the `main` branch. This PR fixes the build failures and contains the following changes:
1. Use `vcvars64` and set the environment variables for `VCToolsInstallDir` and `VCToolsVersion`, so that we dont hardcode path in the yml.
2. Fixes for new analysis failures flagged by new MSVC version.
Existing CICD
NA
=> Fix build failures with latest MSVC (main)

README.md, docs/Diagnostics.md, docs/TroubleshootingGuide.md
Add a troubleshooting guide for eBPF. This iteration is largely focused on initial configuration issues and issues related to the program type BPF_PROG_TYPE_CGROUP_SOCK_ADDR.
N/A
Adds new diagnostics.md and troubleshootingguide.md
=> Add troubleshooting guide

.github/workflows/reusable-test.yml, scripts/Test-FaultInjection.ps1, tests/libs/common/passed_test_log.h
Add timeout logic to fault injection to permit capturing dumps for hung tests.
Fix intermittent bug in _passed_test_log that prevented logging.
CI/CD
No.
=> Timeout during fault injection

libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/unit/execution_context_unit_test.cpp
__ebpf_program_parameters had program_type not set. Hence the ebpf program failed to load and attach.
Behavior change in return value:
If the program type guid is 0, the new return value is changed 
From:  EBPF_EXTENSION_FAILED_TO_LOAD
To: EBPF_INVALID_ARGUMENT
Trace Addition:
1. This PR adds a trace for debugging where program type is 0.
2. This PR adds a trace for debugging to print the guid for program type and attach type. There can be cases when the extension can fail to load/attach:
- Program type is valid but incorrect attach type (For eg, Program type is EBPF_PROGRAM_TYPE_BIND, Attach type is  EBPF_ATTACH_TYPE_XDP)
- Attach type is valid but incorrect program type (For eg, EBPF_PROGRAM_TYPE_XDP, EBPF_ATTACH_TYPE_BIND)
_Do any existing tests cover this change? Yes
Are new tests …
=> Validate program type in ebpf_program_create

.github/workflows/reusable-test.yml
A regression in https://github.com/microsoft/ebpf-for-windows/pull/2635 causes fault injection full tests to fail.
CI/CD
No.
=> Step run_test_without_code_coverage should not run with fault injection

.github/workflows/cicd.yml
ASAN apparently takes its own lock inside NtQueryObject so if TerminateThread gets called on that thread because of NtQueryObject hanging, the ASAN lock may not get released and ASAN can hang in the next CreateThread call.
We had similar issues with codecov so apply the same solution here in excluding `[processes]` from a sanitize run.
Fixes #2650
Covered by existing CI/CD tests, since this was found by CI/CD runs.
No impact.
=> Exclude netsh show processes test from sanitize job

include/net/tcp.h
Verified field names in BPF samples such as Cilium BPF programs
Fixes #2643 
Static asserts don't work with bitfields so cannot be tested that way.
Manually tested with a C program using both clang and MSVC:
```
#include <assert.h>
#include <stdint.h>
#include "..\..\..\include\net\tcp.h"
// Test packet:
// Source Port            = 0x0102
// Destination Port       = 0x0304
// Sequence Number        = 0x05060708
// Acknolwedgement Number = 0x090a0b0c
// Data Offset            = 0xd
// Reserved + flags       = 0x07f
// Window                 = 0x1011
const char test_packet[] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0xd0, 0x7f, 0x10, 0x11};
int main(int argc, char** argv)
{
assert(((struct tcphdr*)test_packet)->source == 0x0201);
assert(((struct …
```
=> Fix tcphdr layout

.github/workflows/reusable-test.yml
Ensure that traces are captured on test failure as well.
CI/CD 'scheduled jobs' run
No Doc changes.
Fixes: #2594
=> Ensure traces are captured on test failures as well

.github/workflows/reusable-build.yml, .github/workflows/reusable-test.yml
Tool install commands should validate that the tool is installed and is present in the path via the where command.
CI/CD
No.
=> Always end tool install with where command

libs/api_common/windows_platform_common.cpp, libs/api_common/windows_program_type.h
Dead code elimination.
Initialize "unspec" program type on demand.
CI/CD
No.
=> Eliminate dead code

cmake/process_bpf_source_file.cmake, tests/sample/CMakeLists.txt, tests/sample/unsafe/CMakeLists.txt
If the user does not have clang installed, it is impossible to build any of the pieces of the project.
No
No -- a new CMake warning message has been added.
=> Support compiling even without clang installed

.github/CODEOWNERS, tools/redist-package/ebpf-for-windows-redist.nuspec.in, tools/redist-package/redist-package.vcxproj
Removed bpf2c.exe/.pdb from the redist-package:
1. tools/redist-package/ebpf-for-windows-redist.nuspec.in
2. tools/redist-package/redist-package.vcxproj
_Do any existing tests cover this change? N/A
**Manual Testing:** Check if the bpf2c.exe and bpf2c.pdb does not exist.
```
PS C:\Users\...\Downloads\ebpf-for-windows - NuGet Redist package (Build-x64_Release)\eBPF-for-Windows-Redist.0.9.0\package\bin> dir
Directory: C:\Users\...\Downloads\ebpf-for-windows - NuGet Redist package
(Build-x64_Release)\eBPF-for-Windows-Redist.0.9.0\package\bin
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         7/18/2023   3:18 PM                drivers
-a----         7/18/2023   3:18 PM          77312 bpftool.exe …
```
=> Remove bpf2c from redist-package

include/ebpf_api.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/ebpfnetsh/elf.cpp
The API bpf_object__open_file causes the provider data to be loaded to resolve program type to program type name. This is not needed for the actual load of the file and should be deferred until needed.
CI/CD + WPR + WPA reference set analysis
No.
=> Reduce reference set from bpf_object__open_file

include/net/ip.h
Fix #2637 
No new tests are added. 
N/A
=> Add Linux member names for IPV4_HEADER

libs/platform/ebpf_tracelog.h
Fixes #2651
This PR:
-  Adds checking for the availability of the `TraceLoggingProvider`, where not previously implemented, accounting also for the contextual tracing level and keyword.
- Refactors the macro functions' ordering in the source code.
CI/CD, local
n.a.
=> Uniform trace logging

installer/Product.wxs, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_platform.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp, scripts/deploy-ebpf.ps1.in, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/end_to_end/test_helper.cpp, tests/netebpfext_unit/netebpf_ext_helper.cpp, tests/netebpfext_unit/netebpf_ext_helper.h, tests/performance/performance_measure.h, tests/stress/um/stress_tests_um.cpp, tests/unit/libbpf_test.cpp, tools/export_program_info/CMakeLists.txt, tools/export_program_info/export_program_info.vcxproj, tools/nuget/ebpf-for-windows.nuspec.in
* Convert usersim to a DLL
* Also make the cmake build clear program info state like the VS build does. (PR #1192 updated the vcxproj file but not the corresponding CMakeLists.txt file for export_program_info.)
* Update platform_unit_test.cpp to fix deadlock in epoch_test_stale_items hit by latest usersim fixes.  The main test thread can't run at `DISPATCH_LEVEL` or it can block execution of one of the two test threads if they are affinitized to the same processor as the main test thread.
* Update performance test to fix the same issue.
* Update `single_instance_hook_t` test class to not throw exceptions in unit tests, but rather allow using `REQUIRE()` so catch2 can correctly deal with fault injection
Fixes #2586 
Covered by existing tests
No impact
=> Convert usersim to a DLL

.github/workflows/release-scheduler.yml
Closes #2710
Adds GitHub workflow for scheduling releases.
Local.
n.a.
no
=> Add GitHub workflow for scheduling releases.

netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_prog_info_provider.c, netebpfext/net_ebpf_ext_tracelog.h
Issues fixed:
- Check nmr binding handle validity prior to calling NmrDeregisterProvider
- Add some critical traces.
_Note: The `NetEbpfExt` extension can certainly use some more traces.  That task will be addressed in a subsequent PR._
CI/CD run.
Fixes #2583
=> Misc. code clean-up fixes, add some critical traces.

libs/api/ebpf_api.cpp, libs/api_common/windows_platform_common.cpp, libs/api_common/windows_platform_common.hpp, libs/execution_context/unit/execution_context_unit_test.cpp
Eliminate 5 pages from ebpf_api_initiate.
CI/CD + WPR + WPA comparative analysis (shows pages no longer being touched).
No.
Notes:
The API load_ebpf_provider_data is best effort, so removing the result.
=> Reduce code pages touched during ebpf_api_initiate

tests/bpftool_tests/bpftool_tests.cpp
The bpftool_test is intermittently failing due to a string parsing error. Add instrumentation to allow better diagnositcs.
CI/CD
No.
No.
=> Log the bpftool output to aid diagnostics

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml
Finish off impactless staged runner migration.
When introducing new runners, in order to allow PRs to continue flowing I relied on the below mechanism:
All runners have the` self-hosted` label, so can be picked up by all PRs.
For the new runners, I removed the ebpf_cicd_tests label, so they woudidn't pick up jobs for PRs other than the one introducting them. Otherwise all jobs failed. Then, all PRs could use all runners, since the code changed to use the `self-hosted `label
Now, we're restoring the labels to what they were, for all runners.
=> Restore runner labels.

tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj
These two build flags are required when using the internal "native compiler" builds from OneBranch that are used to produce "official" binaries that have all the correct compiler/linker flags required by Windows OS builds.
Not yet. Requires going through the process to merge this PR, update XDP to consume, regenerate XDP VS projects, mirror internal XDP repo and run through internal build.
N/A
N/A
=> Add OneBranch Build Property Flags to Build Template

tests/connect_redirect/connect_redirect_tests.cpp, tests/libs/common/common_tests.h, tests/socket/socket_tests.cpp
Revert the changes from #2669
PR on #2669 was first introduced with sockets tests and connect redirect tests with global variables.  However, a comment on the PR raised the concern that usersim will detect the global declaration as a memory leak, or at the very least, result in a leak occurring in an incorrect context, or even lead to the absence of a leak despite its presence. The suggestion was to have it be a local variable on the stack of each test case. However, this caused connect redirect test to fail. CICD would show that the tests are passing and merged the PR although the test was failing due to [this issue ](https://github.com/microsoft/ebpf-for-windows/issues/2707). 
This PR will revert the changes in PR #2669, and a new PR will be raised after a discussion with the team …
=> revert changes

libs/platform/CMakeLists.txt, libs/platform/ebpf_object.c, libs/platform/ebpf_platform.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_fault_injection_kernel.c, libs/platform/kernel/platform_kernel.vcxproj, libs/platform/kernel/platform_kernel.vcxproj.filters, libs/platform/unit/platform_unit_test.cpp, tests/end_to_end/netsh_test.cpp, tests/end_to_end/test_helper.cpp, tests/netebpfext_unit/netebpfext_unit.cpp
Fixes in this PR:
1. Replace the global 'fault injection state' flag with a call to a `usersim` function that returns this state.
2. Fix a post-crash memory leak in test code.
CI/CD
No documentation changes needed.
No
Fixes #2557
=> Fix for failing 'Full fault injection' test.

.github/workflows/reusable-test.yml, scripts/config_test_vm.psm1
Fixes #2736 
Missed one instance of state leakage in #2722.
Tthe `driver` job generates almost all its logs on the VM where the tests are executed.
However, the few log lines from the runner deploying the test collateral on the VMs are persisted in a file in the host's TEMP directory.
We never overwrote the default file name, so the 2 runner processes hit a race condition, when writing to this file.
Due to an existing bug, we never collected this file anyway, fixed now, confimed in the respective artifact file.
=> Fix driver job failure due to log file contention.

scripts/deploy-ebpf.ps1.in
Fix usage text
Fix duplicate -t options
Fix setup_build to put files where deploy-ebpf expects them
Manual
No impact
No MSI impact.
This PR fixes the powershell install script.
=> Fix deploy-ebpf script

libs/execution_context/ebpf_core.c, libs/platform/CMakeLists.txt, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_platform.c, libs/platform/ebpf_platform.h, libs/platform/ebpf_random.c, libs/platform/ebpf_random.h, libs/platform/kernel/platform_kernel.vcxproj, libs/platform/kernel/platform_kernel.vcxproj.filters, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/platform_user.vcxproj, libs/platform/user/platform_user.vcxproj.filters, tests/performance/performance.h, tests/performance/platform.cpp, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj
The previous implementation of bpf_get_prandom_u32 relied on RtlGenRandomEx, which uses a single global state for its PRNG. Replacing this with a per-CPU PRNG implementation.
CI/CD
No.
No.
=> Implement bpf_get_prandom_u32 using linear congruential generator

libs/execution_context/ebpf_maps.c
The function _insert_into_hot_list needs to recheck the key state after acquiring the lock. Failure to do this causes freed keys to be inserted into the hot list.
CI/CD + Perf tests.
No.
No.
=> Recheck state after acquiring lock

libs/execution_context/ebpf_maps.c
When keys are moved to the hot-list, they should be also moved to the current generation. This allows subsequent key usages to take the hot-path and not re-acquire the lock.
CI/CD + Perf
No.
No,
Resolves: #2777 
Note: This also contains the fix for #2765 as it is needed to test this.
=> Fix incorrect LRU algorithm

libs/execution_context/ebpf_maps.c, libs/execution_context/unit/execution_context_unit_test.cpp
The function _update_array_map_entry incorrectly uses only the first 8bits of the key to find the location in the map array.
Added test to catch this.
No.
No.
Resolves: #2779
=> Use full key width when computing array index

.github/workflows/cicd.yml, tests/end_to_end/helpers.h, tests/stress/ebpf_mt_stress.h, tests/stress/ebpf_stress_tests.cpp, tests/stress/km/stress_tests_km.cpp, tests/stress/um/stress_tests_um.cpp
This PR fixes the user mode ('usersim') multi-threaded stress test application to ensure that allocated 'mock' resources are explicitly free'd prior to process termination.
Existing CI/CD test.
No installer changes required.
Fixes: #2222
=> enable explicit clean-up prior to process exit for user mode stress test app.

libs/api/ebpf_api.cpp, tests/end_to_end/helpers.h
Resolves: #2781
The bpf2c tool populates the _programs array sorted by the section name for each program. This then defines the order in which program handles are returned from kernel to user mode. The function _ebpf_enumerate_native_sections returns programs in the order in which they occur in the PE file (which doesn't always match). The net result is that libbpf programs -> kernel handles sometimes don't match.
CI/CD
No.
No.
=> Sort programs to match bpf2c

tests/bpf2c_tests/expected/bindmonitor_mt_tailcall_dll.c, tests/bpf2c_tests/expected/bindmonitor_mt_tailcall_raw.c, tests/bpf2c_tests/expected/bindmonitor_mt_tailcall_sys.c, tests/sample/bindmonitor_mt_tailcall.c, tests/stress/km/stress_tests_km.cpp, tests/stress/readme.md
bindmonitor_tail_call_invoke_program_test test case fails with MAX tail calls 32. The max does not include top-level caller.
Solution:
- Reduce the number of tail calls to 31 in bindmonitor_mt_tailcalls.sys ebpf program, to onboard kernel stress in CICD.
Note: 
- This test case needs to pass to onboard kernel stress in CICD.
- The behavior of processing up to 31 (MAX TAIL CALL CNT - 1) was done in https://github.com/microsoft/ebpf-for-windows/pull/2504/files.
- Linux behavior of 33 MAX TAIL CALL CNT (provided in https://www.man7.org/linux/man-pages/man7/bpf-helpers.7.html) is pending to verify in https://github.com/microsoft/ebpf-for-windows/issues/2794
_Do any existing tests cover this change? Yes.
Manual testing:
```
PS C:\Temp> .\ebpf_stress_tests_km.exe -tt=32 …
```
=> Fix bindmonitor_tail_call_invoke_program_test test case with 31 MAX tail calls

.github/workflows/cicd.yml, scripts/execute_ebpf_cicd_tests.ps1, scripts/vm_run_tests.psm1
Fixes runtime parameter handling to ensure correct and exclusive execution of the scheduled km stress tests. 
CI/CD Scheduled Run
No installation changes.
Fixes: #2771 
Fixes: #2772
=> Ensure correct params are passed for CI/CD km mt stress test jobs

include/ebpf_extension.h, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h
Move saving tail_call_state into the ebpf_state store outside of the inner loop of a program dispatch.
CI/CD
No.
No.
=> Reduce the cost of bpf_tail_call overhead

.github/workflows/reusable-build.yml
The bpf_performance repo depends on artifacts from ebpf-for-windows repo to build.
The ebpf-for-windows repo depends on artifacts from bpf_performance to build.
Net effect is that both builds now fail and there is no way to recover.
CI/CD
No.
No.
=> Fix build artifact circular dependency

scripts/setup-ebpf.ps1
This PR fixes `setup-ebpf.ps1` script. Currently the script tries to copy the binaries from a parent directory which causes copy hence installation fail.
Manually tested the script + CI/CD
No. 
No
=> Fix setup-ebpf.ps1

ebpfcore/EbpfCore.vcxproj, libs/execution_context/kernel/execution_context_kernel.vcxproj, libs/runtime/ebpf_object.c, libs/runtime/kernel/platform_kernel.vcxproj, libs/ubpf/kernel/ubpf_kernel.vcxproj, netebpfext/sys/netebpfext.vcxproj
Resolves: #2742 
```cmd
Baseline:
C:\bpf_perf>RelWithDebInfo\bpf_performance_runner.exe -i tests.yml -e .sys -c 500000 -t "bpf_tail_call"
Test,CPU 0,CPU 1,CPU 2,CPU 3,CPU 4,CPU 5
bpf_tail_call,15931,16075,15942,16029,16109,16092
No reference history:
C:\bpf_perf>RelWithDebInfo\bpf_performance_runner.exe -i tests.yml -e .sys -c 500000 -t "bpf_tail_call"
Test,CPU 0,CPU 1,CPU 2,CPU 3,CPU 4,CPU 5
bpf_tail_call,11891,11892,11902,11719,11839,11907
```
Disable reference counting on release builds.
CI/CD
No.
No.
=> Disable reference history on release builds

libs/execution_context/ebpf_maps.c
The function _ebpf_adjust_value_pointer checks current CPU against max CPU, but current CPU can never exceed max CPU. This is performed via an expensive DIV operation.
CI/CD.
No.
No.
Baseline:
C:\bpf_perf>Debug\bpf_performance_runner.exe -i tests.yml -e .sys -t "BPF_MAP_TYPE_HASH read" -c 100000000 -p 6
BPF_MAP_TYPE_HASH read,86,85,86,83,85,84
_ebpf_adjust_value_pointer fix:
C:\bpf_perf>Debug\bpf_performance_runner.exe -i tests.yml -e .sys -t "BPF_MAP_TYPE_HASH read" -c 100000000 -p 6
BPF_MAP_TYPE_HASH read,81,81,81,81,79,81
=> ebpf_adjust_value_pointer check is redundant

libs/execution_context/ebpf_maps.c, libs/runtime/ebpf_hash_table.c, libs/runtime/ebpf_hash_table.h, libs/runtime/ebpf_state.c, libs/runtime/unit/platform_unit_test.cpp, tests/performance/platform.cpp
Hash tables use MOD in computing the bucket index from the hash.
Two changes:
1) Expand bucket count to power of 2.
2) Use AND mask to compute bucket index.
CI/CD and performance testing.
No.
No.
```cmd
Baseline:
C:\bpf_perf>Debug\bpf_performance_runner.exe -i tests.yml -e .sys -t "BPF_MAP_TYPE_HASH read" -c 100000000 -p 6
BPF_MAP_TYPE_HASH read,86,85,86,83,85,84
No mod hash:
C:\bpf_perf>Debug\bpf_performance_runner.exe -i tests.yml -e .sys -t "BPF_MAP_TYPE_HASH read" -c 100000000 -p 6
BPF_MAP_TYPE_HASH read,73,71,72,73,71,71
```
=> Switch from mod to and for computing bucket index

include/ebpf_nethooks.h, netebpfext/net_ebpf_ext_program_info.h, netebpfext/net_ebpf_ext_sock_addr.c, tests/api_test/api_test.cpp, tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c, tests/connect_redirect/connect_redirect_tests.cpp, tests/libs/util/socket_helper.cpp, tests/libs/util/socket_helper.h, tests/sample/cgroup_sock_addr2.c, tests/socket/socket_tests_common.h, tests/tcp_udp_listener/tcp_udp_listener.cpp
Proxy applications receiving redirected connections currently are unable to identify details about the original underlying connection. This new helper function allows for a program to store data which can be retrieved by the proxy application receiving the redirected connection via WSAIoctl.
Updated existing connect_redirect_tests to utilize this helper function.
cgroup_sockaddr2 program was updated to set the redirect_context message.
tcp_udp_listener was updated to fetch the redirect_context using the WSAIoctl.
N/A
N/A
=> Add helper function to set redirect context

.github/workflows/reusable-build.yml, scripts/run_driver_tests.psm1
eBPF for Windows v0.11.0 has a breaking change where drivers built with v0.10.0 won't run on v0.11.0, so new release of bpf_performance was needed.
CI/CD
No.
No.
=> Pick up v0.3.0 of bpf_performance

docs/EpochBasedMemoryManagement.md, include/ebpf_extension.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_epoch.h, libs/runtime/unit/platform_unit_test.cpp, tests/performance/ExecutionContext.cpp, tests/performance/platform.cpp
Switch epoch logic from relying on spin-lock for protecting to relying on running at IRQL == DISPATCH_LEVEL.
Batching == 1
Before:
```cmd
C:\bpf_perf>RelWithDebInfo\bpf_performance_runner.exe -i tests.yml -e .sys -t "Baseline" -b 1 -c  50000000
Test,CPU 0,CPU 1,CPU 2,CPU 3,CPU 4,CPU 5
Baseline,119,119,115,117,116,118
```
After:
```cmd
C:\bpf_perf>RelWithDebInfo\bpf_performance_runner.exe -i tests.yml -e .sys -t "Baseline" -b 1 -c  50000000
Test,CPU 0,CPU 1,CPU 2,CPU 3,CPU 4,CPU 5
Baseline,31,30,31,31,31,33
```
Batching == 64
Before:
```cmd
C:\bpf_perf>RelWithDebInfo\bpf_performance_runner.exe -i tests.yml -e .sys -t "Baseline" -c  50000000
Test,CPU 0,CPU 1,CPU 2,CPU 3,CPU 4,CPU 5
Baseline,10,11,10,9,10,10
```
After:
```cmd
C:\bpf_perf>RelWithDebInfo\bpf_performance_runner.exe -i tests.yml …
```
=> Remove barriers and spinlock in epoch_enter and epoch_exit

scripts/config_test_vm.psm1, tests/api_test/api_test.cpp
Fixes #2839
This PR adds regression test for native module for 0.11.0 release.
This PR adds test.
No.
No.
=> Add regression test for 0.11.0 release

.github/workflows/cicd.yml, .github/workflows/upload-perf-results.yml
GitHub requires that secrets are explicitly passed to reusable workflows. 
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
CI/CD
No.
No.
=> Explictly pass secrets to reusable workflow

libs/api_common/windows_platform_common.cpp
Fix double-free in api_common.
Fixes #2486
We don't have specific tests to inject faults into C++ new() other than AppVerifier.
Verified using manual fault injection into these paths.
No impact.
No impact.
=> Fix double-free in api_common

.github/workflows/cicd.yml
When adding the new WS2022 runners, I also renamed all the runner labels for consistency, but forgot to update the stress job to reflect that so it failed in the daily scheduled run.
Wait for nightly CI to spin.
No change - docs already contain the new labels.
No.
=> Fix up km_stress job labels.

.github/workflows/upload-perf-results.yml
Fix wrong sha1 hash in reference to actions/upload-artifact.
CI/CD
No.
No.
=> Fix typo in actions/upload-artifact

libs/runtime/ebpf_object.c, libs/runtime/kernel/framework.h, libs/runtime/kernel/platform_kernel.vcxproj.filters, libs/runtime/user/framework.h, tests/end_to_end/netsh_test.cpp, tests/end_to_end/test_helper.cpp, tests/netebpfext_unit/netebpfext_unit.cpp, tests/unit/ebpfcore_test.cpp
* Update usersim to latest
* Add test case calling an IOCTL in ebpfcore_usersim.dll
This updates the ebpfcore_usersim unit test.
Future work (not in this PR) will take some of the existing unit tests that don't use ebpfcore_usersim.dll and add support for using ebpfcore_usersim.dll.
No impact.
No impact.
=> Add test case calling an IOCTL in ebpfcore_usersim.dll

.github/workflows/upload-perf-results.yml
First convert BPF perf results into ANSI so that Python script can process it.
Resolves: #2898
CI/CD as a pull-request.
No.
No.
=> Fix processing of bpf perf results

include/bpf_helpers.h
Resolves: #2730
The libbpf's version of bpf_helpers.h includes both common cross-platform macro definitions as well as Linux platform specific helper function identifiers. This PR recreates the BTF macros from kernel documentation and eliminated the dependency on the libbfp headers.
CI/CD
No.
No.
=> Move required definitions to include/bpf_helpers.h

libs/ebpfnetsh/maps.cpp, tests/end_to_end/netsh_test.cpp
Fix column alignment issue in netsh "show maps" output
Fixes #2917
This PR updates tests.
No impact.
No impact.
=> Fix netsh show maps alignment issue

tools/bpf2c/bpf_code_generator.cpp
In some cases, the BTF data generated by clang contains line number as 0. bpf2c file generating native code, uses line numbers from BTF data to emit `#line <line_number>`. If line number is 0, it causes an issue with compiler as `#line ` pragma can only start from 1.
bpf2c already has a check in one place to ensure it does not generate `#line 0` pragma, but another place was missing this. This PR adds a check for the missing case.
As this is hard to repro on demand and was discovered while converting a `.o` file for a different project, manually tested the changes.
No
No.
=> Fix #line 0 issue for bpf2c

tests/connect_redirect/connect_redirect_tests.cpp, tests/xdp/xdp_tests.cpp
#2707 was recently fixed by amending the error parsing expression.
This is a follow-up fix that will make use of us checking for `$LASTEXITCODE `too.
`xdp_test` and `connect_redirect_test` were swallowing the return code and implicitly returning 0 (per the C standard, p.13 https://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf)
so the exit code portion of our error detecting was being ignored.
Here's an example from Catch2 docs: 
https://github.com/catchorg/Catch2/blob/devel/docs/own-main.md#amending-the-catch2-config
And we're doing it right in `socket_tests.cpp`:
https://github.com/microsoft/ebpf-for-windows/blob/main/tests/socket/socket_tests.cpp#L471
Locally running the tests without eBPF installed fails as expected and sets the $LASTEXITCODE to the number of failed tests.
=> Fix some Catch2 tests not returning exit code.

libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_work_queue.c, libs/runtime/ebpf_work_queue.h, libs/runtime/kernel/platform_kernel.vcxproj, libs/runtime/kernel/platform_kernel.vcxproj.filters, libs/runtime/unit/platform_unit_test.cpp, libs/runtime/user/platform_user.vcxproj, libs/runtime/user/platform_user.vcxproj.filters
1) Add a timed work queue that maintains a per-CPU list of work items to execute. Items inserted into the queue are executed either when the timer expires or when the queue is polled.
2) Switch to using timed work queues to manage inter-processor messages. Messages sent between CPU are inserted into the timed work queue and then either processed via polling the timed work queue or via a timer.
This reduces the number of DPCs that need to be queued to process epoch's distributed consensus algorithm.
CI/CD
Doxygen.
No.
=> Timed work queue

ebpfcore/ebpf_drv.c
Adding a call to ebpf_trace_termination in case of a subsequent APIs failure.
Following this [issue](https://github.com/microsoft/ebpf-for-windows/issues/2838)
=> Adding a call to ebpf_trace_terminate in case of subsequent APIs faliure

libs/runtime/ebpf_epoch.c
The ebpf_epoch_initiate function should cleanup on failure. The ebpf_epoch_terminate function assumes that either initiate was called successfully or that state has already been cleaned up,
CI/CD
No.
No.
Resolves: #2971
=> ebpf_epoch_initiate should cleanup on failure

tests/libs/util/wer_report.hpp
Resolves: #2660
Remove debug fprintf statements.
CI/CD
No.
No.
=> Remove debug fprintf calls

.github/workflows/cicd.yml
The 'quick' version is really meant for the PR validation CI/CD workflow and was inadvertently enabled for the Scheduled CI/CD workflow. The scheduled workflow already runs the extended user-mode multithreaded stress test, so running the quick version as well is redundant.
CI/CD
CI/CD workflow modification.  No new tests needed.
No documentation impact.
Fixes #2998
=> Skip running the 'quick' user-mode multi-threaded stress test in scheduled CI/CD runs

libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/runtime/ebpf_object.c, libs/runtime/ebpf_object.h, libs/runtime/unit/platform_unit_test.cpp
Split cleanup of eBPF objects into zero-refcount and free operations. Zero-rerfcount is permits the object to release refcounts on other objects while still permitting it to operate. The free operation is the final release of the object and is performed once the current epoch ends.
Delay freeing all objects util the end of the current epoch.
Expose function to obtain pointer to object in current epoch.
CI/CD & Perf
No.
No.
Before:
```
C:\test>Release\bpf_performance_runner.exe -i tests.yml -e .sys -t "bpf_tail_call"
Timestamp,Test,Average Duration (ns),CPU 0 Duration (ns),CPU 1 Duration (ns),CPU 2 Duration (ns),CPU 3 Duration (ns),CPU 4 Duration (ns),CPU 5 Duration (ns)
2023-10-20T18:22:01-0800,bpf_tail_call,1448,1467,1459,1469,1452,1444,1401
```
After:
``` …
```
=> Delay free of objects to epoch end

libs/runtime/ebpf_async.c, libs/runtime/ebpf_epoch.c, libs/runtime/unit/platform_unit_test.cpp
Fixes in this PR:
1. Raise IRQL _after_ `test_helper` initialization, so that its destructor is called at PASSIVE in we hit an error in `test_helper::initialize()`.
_(The `test_helper::~test_helper()` destructor calls `ebpf_flush_epoch()` that ends up blocking on a lock if called at DISPATCH.)_
2. Ensure that the `_ebpf_epoch_cpu_table` ptr is reset to NULL if `ebpf_epoch_initiate` frees that pointer in its error handling path.
_(Not doing so led to the 'use-after-free' crash seen in [this](https://github.com/microsoft/ebpf-for-windows/issues/2973#issuecomment-1759363487) comment, where the code path initiated by `ebpf_epoch_flush` ends up referencing this (now freed) pointer.)_
Issued exposed by existing test.  No new test …
=> Raise IRQL to DISPATCH _after_ test_helper is successfully initialized.

scripts/cleanup_ebpf_cicd_tests.ps1
Fixes #2913 
Restore VM checkpoint after `driver `job finishes.
If Duonic devices are accidentally persisted in the checkpoint during runner maintenance,
it causes subsequent test runs to fail.
This is a workaround for us not being able to cleanly uninstall Duonic currently.
In cases where we want to manually grab a dump if it failed to upload, this checkpoint restore comes after the dump was copied to the runner host. So this doesn't reduce the amount of time we'd have to do that before another job is scheduled on a given runner.
=> Restore VM after driver job finishes.

libs/runtime/unit/platform_unit_test.cpp
Resolves: #2986
Test of randomness for causes sporadic failures by being to strict.
CI/CD
No.
No.
=> Increase critical value threshold

tests/socket/socket_tests.cpp
Fixes #2203 
Use `std::uniqe_ptr` with deleter to clean up the bpf_object pointer in case execution doesn't reach the cleanup call.
Before this change, an assertion failure after a program was attached in one test, would cause the other tests trying to use that program to fail too.
Locally forced an assertion failure for one of the 4 `connection_test` cases
```
if (address_family == AF_INET && protocol == IPPROTO_UDP) {
REQUIRE(false);
}
```
and observed only that specific test failing.
=> Clean up bpf_object on exceptions in socket_tests.

Directory.Build.props, ebpfcore/usersim/EbpfCore_Usersim.vcxproj, external/Directory.Build.props, scripts/check_binary_dependencies_ebpfapi_dll_nativeonly_release.txt
**Problem domain:**
The problem below was exposed due to the latest ASAN update
•	EbpfCore_Usersim depending on usersim_dll_skeleton statically.
•	usersim_dll_skeleton getting EnableASAN set to true (due to Directory.Build.Props)
•	EbpfCore_Usersim getting EnableASAN set to false.
**Solution:**
1. Enable EnableASAN in EbpfCore_Usersim to inherit the root setting from Directory.Build.Props, by adding a conditional flag to the EnableASAN. With this, EbpfCore_Usersim's EnableASAN is set to true.
2. LinkTimeCodeGeneration (LTCG) is set based on EnableASAN value. If EnableASAN is false, then LTCG is enabled.
3. WholeProgramOptimization (WPO) is set based on EnableASAN value.  If EnableASAN is false, then WPO is enabled.
4. SPGO  (SharePoint extension) is set based on EnableASAN value. If …
=> Fix ASAN linker error

docs/GettingStarted.md, scripts/Setup-DevEnv.ps1
chore: fix the hash for setup scripts, orelse scripts/Setup-DevEnv.ps1 would always fail.
=> chore: fix the hash for setup scripts

.github/workflows/cicd.yml, scripts/config_test_vm.psm1, scripts/run_driver_tests.psm1
Related #2948 
The bad runner which failed to upload crash dumps and perf traces seems better now - connected the vSwitch to a faster adapter.
To further facilitate uploads, first compress the large files.
KM dumps 600MB -> 60MB
Perf ETLs      1.1GB -> 110MB
Modified the km_stress and perf_with_profile jobs to run on PR as a one-off, and observed the files were successfully uploaded:
km_stress crash dumps upload logs: 
https://github.com/microsoft/ebpf-for-windows/actions/runs/6792240647/job/18465751588
perf profile upload logs:
https://github.com/microsoft/ebpf-for-windows/actions/runs/6794724707/job/18471866156
=> Compress KM dumps and perf ETLs before upload.

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_program.c, libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_epoch.h, libs/runtime/unit/platform_unit_test.cpp, tests/end_to_end/netsh_test.cpp
New API ebpf_epoch_synchronize that waits for current epoch to end.
Add synchronize to start of test run to minimize noise in results.
CI/CD
No.
No.
=> Switch from epoch_flush to epoch_synchronize

libs/execution_context/ebpf_maps.c, tests/unit/libbpf_test.cpp
Problem:
The next_key was incorrectly set to _next_array_map_key.
Fix:
Set .next_key = _next_hash_map_key,
_Do any existing tests cover this change? No.
Are new tests needed? Yes
_Is there any installer impact for this change? No
=> Fix bpf_map_get_next_key for hash-of-maps

libs/execution_context/ebpf_core.c
Resolves: #3049 
Default to 1 repeat count if zero is specified
CI/CD
No.
No.
=> Default to 1 repeat count if zero is specified

.github/workflows/reusable-build.yml, .github/workflows/reusable-test.yml
There is an issue with the latest version of ASAN which makes it incompatible with the latest version of Windows. To workaround this issue (while an ASAN fixed is worked on), we can set the environment variable for ASAN_WIN_CONTINUE_ON_INTERCEPTION_FAILURE.
CI/CD
N/A
N/A
=> Workaround ASAN issue with environment variable

.github/workflows/cicd.yml
Fixes #2879 
Speed up PR validation by removing the `Heaps` and `Leak` AppVerifier checks in Debug PR builds.
We retain PR coverage by
- keeping `sanitize_unit_tests` job - ASAN team claims it's more effective at detecting memory violations than AppVerifier.
- keeping the leak detection from `usersim`
The nightly run remains the same and enables the following checks:
`Exceptions Handles Heaps Leak Locks Memory SRWLock Threadpool TLS DangerousAPIs DirtyStacks TimeRollOver`
The PR run uses these:
`Exceptions Handles Locks Memory SRWLock Threadpool TLS DangerousAPIs DirtyStacks TimeRollOver`
Exhaustively tried all combinations of removing the Heaps, Leak, Memory, DirtyStacks options in side-by-side job runs.
Observed removing Heaps+Leak reduced run-time by 50%; removing only Heaps - 25%. …
=> Only run unit_tests in Debug flavor with AppVerifier memory checks in the nightly CI run.

.github/workflows/cicd.yml
We're seeing multiple CI runs for the same PR, while pushed updates should cancel the ongoing runs.
GH must have changed the event payload, and now the `pull_request` event contains the `before / after` fields, which previously only existed in the `push` event.
Fix: reorder the fields in the OR expression so that the calculation reaches the PR number and detects existing duplicates.
=> Reorder GH events in concurrency expression.

docs/isa-support.rst
Match https://github.com/ietf-wg-bpf/ebpf-docs/blob/main/rst/instruction-set-opcodes.rst
This adds some new instructions, and fixes a few typos and formatting issues
Fixes #3025
This PR is best reviewed using the "Hide whitespace" checkbox on github (under the gear icon when viewing Files changed)
No impact.
No impact.
=> Update isa-support table

docs/eBpfExtensions.md, include/ebpf_extension.h, libs/execution_context/ebpf_link.c
Resolves: #3057
Batch invoke begin is passed a state field. It was assuming that the memory was zero initialized, but that doesn't match the SAL annotation.
The fix is to zero initialize the state field.
CI/CD
Documented the batch API semantics.
No.
=> Zero initialize batch context state

libs/api_common/api_common.hpp, libs/execution_context/ebpf_core.c, tests/bpf2c_tests/expected/sockops_dll.c, tests/bpf2c_tests/expected/sockops_raw.c, tests/bpf2c_tests/expected/sockops_sys.c, tests/sample/cgroup_sock_addr.c, tests/sample/sockops.c, tests/socket/socket_tests.cpp, tests/socket/socket_tests_common.h
This PR fixes #2706 . 
This turned out to be a test issue, not a defect in feature code.  The test eBPF program flipped the local and remote IP addresses on the connection based on the direction of the connection to look up a connection table populated by the user mode test app. Since the direction is not available in connection deletion case, it failed to look up the connection and did not update the ring buffer.
The `connection_tuple_t` struct has been modified to use local/remote IP instead of source and destination so that the eBPF program do not need to flip them based on direction. Instead two entries have been added to the connection table for each direction.
There was a incidental finding in a lack of mapping from `ebpf_error` to `errno` which is fixed.
The eBPF core was also …
=> fix sock_ops test.

.github/workflows/cicd-release-validation.yml
Fix file name error in uploading perf-logs in the release validation ci/cd workflow.
CI/CD.
n.a.
n.a.
=> Fix perf-log upload in release validation workflow.

docs/eBpfExtensions.md, include/ebpf_program_types.h, libs/api_common/store_helper_internal.cpp, libs/api_common/windows_helpers.cpp, libs/execution_context/ebpf_program.c, libs/shared/ebpf_serialize.c, libs/store_helper/ebpf_store_helper.c, libs/store_helper/kernel/ebpf_store_helper_km.vcxproj, netebpfext/net_ebpf_ext_program_info.h, tests/end_to_end/netsh_test.cpp, tests/sample/unsafe/xdp_adjust_head_unsafe.c, tools/bpf2c/bpf2c.cpp, tools/bpf2c/bpf2c.vcxproj
This fixes #3090. A `reallocate_packet` flag is added to the helper function prototype metadata, to pass onto the PREVAIL verifier, to validate programs that uses any helper function that may change the packet pointers such as `xdp_adjust_head`.
A new netsh tests is added that tries to load an unsafe XDP program and fails.
Updated extension documentation.
No changes to installation.
=> Helper reallocate packet

.github/workflows/release-scheduler.yml
Fixes #3119
Adds read-only permissions to `release-scheduler.yml`.
CICD
n.a.
n.a.
=> Add permissions to `release-scheduler.yml` workflow.

netebpfext/net_ebpf_ext_sock_addr.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c, tests/connect_redirect/connect_redirect_tests.cpp, tests/libs/util/socket_helper.cpp, tests/libs/util/socket_helper.h, tests/sample/cgroup_sock_addr2.c, tests/socket/socket_tests_common.h
- Adds connected UDP tests for cgroup/sock_addr_connect. Closes #1917.
- Adding these tests exposed issue #3053. This PR also resolves the issue by removing a stale connection context for the same connection if it exists. Closes #3053.
Future work: These tests also found issue #3052 which is NOT resolved in this PR.
- Modified the connect_redirect_tests to also utilize connected UDP sockets.
- Modified cgroup_sock_addr2.c to skip setting the redirect context (filed issue #3052 for tracking).
N/A
N/A
=> Add connected UDP tests to cgroup/sock_addr_connect

docs/ReleaseProcess.md
There is a requirement to have ebpf-for-windows debug binaries. Hence we need the below in the ebpf release.
- Build-x64-native-only-Debug.0.13.0.zip*
_Do any existing tests cover this change? N/A
Are new tests needed? N/A
_Is there any documentation impact for this change? Yes
_Is there any installer impact for this change? No.
=> Update Release process to get the Debug version.

tests/end_to_end/netsh_test.cpp, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj
Enable optimization flag when generating release versions of native binaries.
CI/CD
No.
No.
=> Enable optimization on bpf2c generated code

docs/eBpfExtensions.md, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c
The sockops and sockaddr program information are missing the required_irql fields. This causes bpf_prog_test_run_opts to invoke them at IRQL == PASSIVE_LEVEL instead of IRQL == DISPATCH_LEVEL.
CI/CD
No.
No.
=> Set required_irql in sockops and sockaddr program information

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c
In certain instances, inability to enter rundown does not indicate a fatal error.  It just means that we lost the race to get there, so we should just exit.
CI/CD  only (Bug cannot be repro'd locally)
No installer changes.
Fixes #3097
=> Bail if we can't enter rundown in WFP classify callbacks

libs/runtime/unit/platform_unit_test.cpp
Resolves: #3150
Some of the platform tests were leaking epoch states. (Failing to call epoch exit before unwinding). With changes from https://github.com/microsoft/ebpf-for-windows/pull/3039 leaked epoch states are now caught during testing.
Scheduled CI/CD https://github.com/microsoft/ebpf-for-windows/actions/runs/7492392364
No.
No.
=> Add RAII wrapper for epoch_enter/exit

docs/isa-support.rst
Fix descriptions of atomic fetch operations in isa-support.rst.
Specifically, after the operation, src contains the original (not the modified) value
This fix was already made in the https://github.com/ietf-wg-bpf/ebpf-docs repository, this PR just copies the same fix into the isa-support.rst in this repo.
No impact, this is a doc-only change.
This is a doc change.
No impact.
=> Fix descriptions of atomic fetch operations in isa-support.rst

.github/workflows/cicd.yml
Support for testing CPU v4 instructions requires an updated bpf_conformance release.
CI/CD
No.
No.
=> Pickup version 0.0.5 of bpf_conformance

docs/isa-support.rst, tools/bpf2c/bpf_code_generator.cpp
Add support to bpf2c for the signed division and modulo instructions as specified in https://github.com/ietf-wg-bpf/ebpf-docs/pull/42
Manually tested with latest bpf_conformance suite (in bpf_conformance main branch) using
```
bpf_conformance_runner --test_file_directory C:\Users\dthal\git\ebpf\bpf_conformance\build\tests --plugin_path C:\Users\dthal\git\ebpf\ebpf-for-windows\x64\Debug\bpf2c_plugin.exe --cpu_version v4 --exclude_regex "imm-" --plugin_options "--include C:\Users\dthal\git\ebpf\ebpf-for-windows\include"
```
This PR includes a doc change to update the list of what instructions are supported.
It also lists bpf_conformance tests for the same, although the latest release of bpf_conformance still doesn't include them yet.
It also fixes a cut-and-paste error for opcode 0x06.
No …
=> Add sdiv and smod instruction support to bpf2c

libs/api/Verifier.cpp, tests/bpf2c_tests/elf_bpf.cpp, tests/bpf2c_tests/expected/inner_map_dll.c, tests/bpf2c_tests/expected/inner_map_raw.c, tests/bpf2c_tests/expected/inner_map_sys.c, tests/sample/undocked/inner_map.c, tests/unit/libbpf_test.cpp, tools/bpf2c/bpf_code_generator.cpp
Resolves: #2854
Add support for loading BPF programs that contain anonymous inner maps.
CI/CD
No.
No.
=> Add support for handling anonymous inner maps

.github/workflows/cicd-release-validation.yml, .github/workflows/cicd.yml, docs/isa-support.rst, tools/bpf2c/bpf_code_generator.cpp
* Update CI/CD bpf_conformance job to test cpu=v4 commands.
* Remove movsx*-imm instructions from doc.  Per latest discussion on the mailing list at
https://mailarchive.ietf.org/arch/msg/bpf/uQiqhURdtxV_ZQOTgjCdm-seh74/ the MOVSX operation is only defined to support register extension.
* Add bpf2c support for swap* instructions.
* Add bpf2c support for movsx* instructions.
* Add bpf2c support for ja32 instruction.
* Change bpf2c to use verifier's `INST_`* defines where available, to start removing dependency from bpf2c on ubpf headers, since bpf2c should not use ubpf.
This PR includes test updates.
This PR includes doc updates.
No impact.
=> Add bpf2c support for cpu=v4 instructions

.github/workflows/cicd-release-validation.yml, .github/workflows/cicd.yml, include/bpf2c.h, tests/bpf2c_plugin/bpf2c_plugin.cpp, tests/bpf2c_plugin/bpf2c_test.cpp, tests/bpf2c_tests/expected/atomic_instruction_fetch_add_dll.c, tests/bpf2c_tests/expected/atomic_instruction_fetch_add_raw.c, tests/bpf2c_tests/expected/atomic_instruction_fetch_add_sys.c, tests/bpf2c_tests/expected/atomic_instruction_others_dll.c, tests/bpf2c_tests/expected/atomic_instruction_others_raw.c, tests/bpf2c_tests/expected/atomic_instruction_others_sys.c, tools/bpf2c/bpf_code_generator.cpp
Resolves: #3188
Switch from intrinsic form of interlocked instructions to function call version (supported in user mode and kernel mode).
CI/CD
No.
=> Enable interlocked tests in bpf2c conformance

libs/api/ebpf_api.cpp
This PR serializes calls to the pe-parse api and the associated error handling by calling them under lock.
No new tests needed as this is already exercised by the existing multi-threaded stress tests.
Fixes #3207
=> Serialize calls to pe-parse api calls.

installer/Product.wxs, libs/execution_context/ebpf_native.c, scripts/check_msi_installation_files_regular_debug.txt, tests/bpf2c_tests/elf_bpf.cpp, tests/bpf2c_tests/expected/hash_of_map_dll.c, tests/bpf2c_tests/expected/hash_of_map_raw.c, tests/bpf2c_tests/expected/hash_of_map_sys.c, tests/sample/undocked/hash_of_map.c, tests/unit/libbpf_test.cpp, tools/bpf2c/bpf_code_generator.cpp
Resolves: #2882
Add support for statically initializing BPF_MAP_TYPE_HASH_OF_MAPS.
CI/CD + new test.
No.
Updated installer to permit libbpf tests to run.
=> Add support for statically initializing BPF_MAP_TYPE_HASH_OF_MAPS

libs/api/ebpf_api.cpp
Resolves: #3213 
Fix AV if allocation of error_message string fails.
CI/CD
No.
No.
=> Fix AV if allocation of error_message fails

libs/execution_context/ebpf_native.c
The function ebpf_native_load_programs leaks handles if initialization of native modules fails.
CI/CD + fault injection.
No.
No.
=> If setting initial value of maps fails, ebpf native module leaks handles

libs/execution_context/ebpf_maps.c
LPM tracks prefix lengths stored in the hash-table via a bitmap. This bitmap is only ever added to (never removed) so unconditionally doing an interlocked test and set is excessive.
Possibly related to: #3016
CI/CD
No.
No.
=> Eliminate unneeded interlocked operation on LPM updates

libs/execution_context/ebpf_program.c
In bpf_prog_test_run_opts, the IRQL can be specified for program execution. However, this is not used for context_create and context_destroy.
This change moves context_create and _destroy to be executed at the same IRQL as the program is.
Closes #3241.
Existing test coverage validates that there are no issues with this change.
n/a
n/a
=> Move context_create and context_destroy to run at same IRQL as program invocation.

libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_object.cpp, tests/unit/libbpf_test.cpp
Fixes #3234
Fixes the behavior of `bpf_obj_get()` to comply with the official specs: https://docs.kernel.org/userspace-api/ebpf/syscall.html
CI/CD
n.a.
n.a.
=> Fix `bpf obj get()` behavior.

libs/execution_context/ebpf_maps.c
The LPM map tracks prefix lengths in a bitmap. Updates to the bitmap are done using 64bit interlocked operations. If the bitmap isn't 64bit aligned, then this can result in 64bit interlocked operations that cross cache lines, which cause a system wide memory stall (due to interlocked operation needing to lock the bus).
CI/CD
No.
No.
=> Ensure that LPM's prefix bitmap is always 64bit aligned

docs/isa-support.rst
Changes to match latest draft-ietf-bpf-isa
Also correct legacy packet instruction lines to show that PREVAIL does support them.  https://github.com/vbpf/ebpf-verifier/pull/577 will update the verifier so make such support a platform specific property but that hasn't been merged yet so this PR reflects current state.
No impact.
This is a documentation change.
No impact.
=> ISA support updates

.github/workflows/cicd-release-validation.yml
The file cicd-release-validation.yml wasn't updated to match cicd.yml.
Update the CI/CD pipeline in release/0.14.0 branch.
CI/CD
No.
No.
=> Update cicd-release-validation.yml (#3245)

.github/workflows/cicd-release-validation.yml
Cherry-pick #3245 : The file cicd-release-validation.yml wasn't updated to match cicd.yml.
The file cicd-release-validation.yml wasn't updated to match cicd.yml.
CICD testing.
No
No
=> Release v0.14.0

docs/GettingStarted.md
Resolves: #3192
This change expands the documentation of the port_quota example to work around a number of potential issues a new user may encounter when attempting to run the demo, because the existing documentation was very incomplete.
 
This change does not include any code changes.
_Is there any documentation impact for this change?_ Yes, see description.
_Is there any installer impact for this change?_ No. This is a docs-only change.
=> Improve documentation for running the port_quota demo.

docs/ReleaseProcess.md
Update to ReleaseProcess doc to add the additional zip files to the Release.
What changed?
- Do not rename ebpf-for-windows.X.Y.Z.msi to `eBPF-for-Windows.X.Y.Z.msi`.
- Add additional Build-x64-Debug.zip and Build-x64-Release.zip files.
_Do any existing tests cover this change? N/A. Are new tests needed? N/A
_Is there any documentation impact for this change? Yes.
_Is there any installer impact for this change? No
=> Minor update to ReleaseProcess doc

libs/runtime/ebpf_work_queue.c
KeSetTargetProcessorDpc should not be used on systems with > 64 CPUs. KeSetTargetProcessorDpcEx should be used instead.
CI/CD
No.
No.
=> Fix issue with > 64 cpus

libs/runtime/ebpf_object.c
Fixes #3275
Remove max limit for `ebpf_id_table`. Also change the number of buckets to 1024 (currently defaults to 64) to reduces chances of collision and chaining.
Existing CICD.
No
No
=> Remove max limit for `ebpf_id_table`

tests/end_to_end/netsh_test.cpp, tests/sample/unsafe/xdp_datasize_unsafe.c
This PR adds a known 'unsafe' ebpf program and a related unit test to verify xdp data size checks.
New ebpf program added and related test added to `unit_tests.exe`
No documentation changes.
Fixes #3255
=> Add negative test program and test for xdp datasize check

.github/workflows/scorecards-analysis.yml
https://github.com/microsoft/ebpf-for-windows/actions/workflows/scorecards-analysis.yml?query=branch%3Amain shows that the scorecards workflow is consistently failing in main.
As can be seen at
https://app.stepsecurity.io/github/microsoft/ebpf-for-windows/actions/runs/8052805389 we are hitting the errors because the score card action tries to access www.bestpractices.dev.  This is the new name of
bestpractices.coreinfrastructure.org which was allowed (indeed if you try to go to that site in a browser, it now redirects to www.bestpractices.dev).  This updates the ACL with the new domain name.
Covered by CI/CD.
No impact.
No impact.
=> Fix scorecards workflow runs

libs/api/ebpf_api.cpp, libs/api_common/device_helper.cpp, libs/api_common/device_helper.hpp
Resolves: #3325
IOCTL calls from multiple threads sharing the same device handle that has FILE_FLAG_OVERLAPPED but without an OVERLAPPED can cause IOCTL calls to hang.
CI/CD
No.
No.
=> Eliminate calls with FILE_FLAG_OVERLAPPED set, but no overlapped

ebpfapi/dllmain.cpp, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api_common/api_common.cpp, libs/api_common/device_helper.cpp, libs/api_common/device_helper.hpp, libs/service/api_service.cpp, tests/api_test/api_test.cpp
IOCTLs sent via a file handle that is opened without the FILE_FLAG_OVERLAPPED flag are serialized in the file object. This will affect performance if multiple user mode threads are making concurrent IOCTL requests.
This change switches the synchronous handle to being per-thread, with the handle being closed on thread detach.
CI/CD
No.
No.
=> Switch synchronous thread to thread_local storage

include/bpf_helper_defs.h, tests/sample/utility.c
Memset was incorrectly declared in the header as taking (destination, size, value), but the standard C memset takes (destination, value, size). Fix the definition to match the standard C version to avoid developer confusion.
CI/CD
No.
No.
=> Memset is defined as taking destination, c, count

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext.h
This PR adds some additional book-keeping info and traces to further debug this issue.    This issue is inconsistently seen in CI/CD runs and not repro'd locally.
Issue seen in existing test, so no new tests needed.
No doc impact.
No Installer Impact.
Fixes #3161
=> km stress test hang investigation - Add book-keeping info and traces for post-mortem debugging.

libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/shared/ebpf_tracelog.h, netebpfext/net_ebpf_ext_tracelog.h
The tracelog macros had incorrect check for trace level for error messages. The trace for extensions failing to attach did not have correct message string.
CI.
N/A.
N/A.
=> fix tracing.

.github/workflows/cicd.yml, .github/workflows/reusable-build.yml
This PR adds support to ensure that the CI/CD workflow checks out sources for the specified branch from the github-provided input specifying the repository to use.
(Details in linked issue)
Tested with a custom self-hosted runner setup for the `https://github.com/dv-msft/ebpf-for-windows` down-stream fork.
Fixes #3346
=> Use specified primary repository (for self-hosted runner setups)

docs/DevelopmentGuide.md, docs/InstallEbpf.md, docs/NativeCodeGeneration.md, docs/TroubleshootingGuide.md, docs/debugging.md, docs/eBpfExtensions.md, docs/tutorial.md
Marking doc blocks as C/JSON/XML adds syntax highlighting.
N/A
Docs should now be syntax highlighted, but otherwise there are no changes.
N/A
=> docs: Mark C/JSON/XML code, remove stray backticks

tests/api_test/api_test.cpp
This fixes #3361.
This is related to #3354 which introduced a flaky test, which can fail intermittently like [this](https://github.com/microsoft/ebpf-for-windows/actions/runs/8318926167/job/22761743245).
The new `test_ringbuffer_wraparound` does not wait for all the callbacks to be completed before checking the goal state is reached. The fix was to add a `std::promise` that is satisfied when the expected event count is reached.
`test_ringbuffer_wraparound`.
No.
No.
=> wait for all events.

scripts/Run-Self-Hosted-Runner-Test.ps1, scripts/config_test_vm.psm1
This PR contains:
1. Streamlining and adding additional trace statements during kernel mode dump harvesting.
2. Fixing the issue where we were passing the incorrect process id to procdump64.exe
This is an enhancement to the existing test infrastructure itself.  Tested via manual verification locally as well as on private 'self-hosted runners' setup.
Fixes #3371
=> CI/CD user, kernel dump harvesting fixes

.github/workflows/reusable-build.yml
When calling reusable build from netperf, only the MSI is required.
CI/CD
No.
No.
=> Add option to skip if build artifact name == none

.github/workflows/cicd-release-validation.yml
A previous PR (#3345) added a new required parameter into the reusable-build.yml workflow. The cicd-release-validation.yml was not updated to account for this. This change address this.
none.
n/a
n/a
=> Update release yml to use new required repository parameter in the build workflow

.github/workflows/reusable-build.yml
This pull request primarily involves updates to the GitHub Actions workflow file `.github/workflows/reusable-build.yml`. The changes introduce new outputs for the `build` job and the workflow itself. These outputs, `should_skip` and `skipped_by`, are designed to provide more information about whether a build was skipped and the action that caused the skip.
* [`.github/workflows/reusable-build.yml`](diffhunk://#diff-951765131741a39f193f7387e405bafacb9b9e836a17986e6c7480d6dc448cc3R48-R65): Added new outputs `should_skip` and `skipped_by` to the `build` job and the workflow. These outputs are set with values from the `skip_check` step outputs. This will provide more detailed information about the skipping of builds.
Callers can use these outputs to determine if the …
=> Make results of skip_check step available to caller

include/bpf_helpers.h, include/ebpf_nethooks.h, undocked/tests/sample/ext/inc/sample_ext_helpers.h
Make sure all helpers are declared const to avoid any cases where clang would generate callx instead of call instructions.
Fixes #3387
Existing tests pass.
No impact. (callx discussion was previously removed from the tutorial.md in PR #782)
No impact.
=> Make sure all helpers are declared const

tools/nuget/nuget.vcxproj
Fixes #3385
This PR deletes any old / stale nuget packages from the build directory when `nuget` project is built.
Existing CICD
No
No
=> Clean up stale nuget packages in build step

scripts/install_ebpf.psm1
Fixes recent regression where a duplicate call to 'wpr.exe -cancel' returns an error and causes the post-test cleanup to fail, which shows up as the whole job failing and causes test results not to be gathered.
Manually scheduled run - perf job passed.
https://github.com/microsoft/ebpf-for-windows/actions/runs/8457367236/job/23169744149
=> Swallow wpr cancel error in uninstallation path.

.github/workflows/cicd.yml, .github/workflows/netperf.yml, .github/workflows/upload-perf-results.yml
This pull request mainly focuses on enhancing the CI/CD workflow by introducing a new `netperf` job, adding new jobs for uploading `netperf` results, and modifying the existing `upload-perf-results` workflow. The changes also include the addition of a new `netperf.yml` workflow and some modifications to the `upload-perf-results.yml` workflow.
New Jobs:
* [`.github/workflows/cicd.yml`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0R581-R590): A new `netperf` job has been added which uses the `netperf.yml` workflow. This job is triggered either on a schedule or when a workflow is dispatched.
* [`.github/workflows/cicd.yml`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0R602-R640): Three new jobs …
=> Integrate with netperf repo.

scripts/Run-Self-Hosted-Runner-Test.ps1, scripts/cleanup_ebpf_cicd_tests.ps1, scripts/config_test_vm.psm1
This PR fixes the regression that broke user, kernel mode dump harvesting.
Tested for both paths ('on drivers' CI/CD tests, 'on-drivers' kernel mode multi-threaded stress tests):
- locally on the dev machine across a local VM (in close approximation of the CI/CD workflow)
- on a dedicated private self-hosted runner
- on the usual CI/CD workflow
'on-drivers' CI/CD test result (output fragment):
```
<SNIP>
.\cleanup_ebpf_cicd_tests.ps1 -KmTracing $true -LogFileName TK5-3WP07R0703_WS2019_3.log -SelfHostedRunnerName TK5-3WP07R0703_WS2019_3
shell: C:\Windows\System[3](https://github.com/microsoft/ebpf-for-windows/actions/runs/8448844584/job/23142117260#step:27:3)2\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
env:
SOURCE_ROOT: …
```
=> Fix user, kernel dump harvesting regression

.github/workflows/reusable-build.yml
Invoking reusable-build from the netperf workflow, it fails to execute if the target repo is unchanged. 
CI/CD
No.
No.
=> Make skip-duplicate-actions optional.

ebpfapi/Source.def, libs/api/Verifier.cpp, libs/api/Verifier.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_object.cpp, tests/unit/libbpf_test.cpp
Resolves: #3352 
This pull request introduces changes that allow the EBPF verifier to load EBPF programs not only from files but also from memory. This is achieved by using `std::variant` to hold either a file path or a memory buffer. The most significant changes include adding a new method `bpf_object__open_mem` for opening an ELF file from memory, modifying several methods in `libs/api/Verifier.cpp` and `libs/api/ebpf_api.cpp` to handle the variant type, and adding a new test case for loading an EBPF program from memory.
Changes to the API:
* [`ebpfapi/Source.def`](diffhunk://#diff-2f82d1ff51a61fb435467ba5290591820cb88e359100a25e9b9a8e7913c6577cR60): Added a new function `bpf_object__open_mem` to the exports.
* [`libs/api/api_internal.h`](diffhunk://#diff-545d6b59394e62a7162e59b142ddf08d …
=> Implement bpf_object__open_mem

docs/eBpfExtensions.md, include/ebpf_program_types.h, include/ebpf_windows.h, libs/api_common/store_helper_internal.cpp, libs/api_common/windows_helpers.cpp, libs/execution_context/ebpf_program.c, libs/shared/ebpf_serialize.c, libs/shared/shared_common.c, libs/store_helper/ebpf_store_helper.c, netebpfext/net_ebpf_ext_program_info.h, scripts/config_test_vm.psm1, tests/end_to_end/netsh_test.cpp, tests/sample/unsafe/xdp_adjust_head_unsafe.c, tools/bpf2c/bpf2c.cpp, tools/bpf2c/bpf2c.vcxproj
**Note** this PR must be completed *after* #3326 is merged.
This fixes https://github.com/microsoft/ebpf-for-windows/issues/3090. A reallocate_packet flag is added to the helper function prototype metadata, to pass onto the PREVAIL verifier, to validate programs that uses any helper function that may change the packet pointers such as xdp_adjust_head.
A new netsh tests is added that tries to load an unsafe XDP program and fails.
Updated extension documentation.
No changes to installation.
=> Reallocate packet

scripts/Cleanup-Installer.ps1
This pull request introduces a new PowerShell script `Cleanup-Installer.ps1` to forcefully remove all eBPF components when an uninstall is not possible. This script is not intended for production systems but for test systems where eBPF components are being tested. The script performs several operations including removing registry keys related to eBPF, stopping and removing eBPF services, and deleting the eBPF installation directory.
Key changes include:
* `scripts/Cleanup-Installer.ps1`: This new script forcefully removes all eBPF components from a test system. It does this by:
* Finding and removing the registry key for the eBPF for Windows product from the `Installer\UserData` and `Uninstall` registry paths.
* Stopping and removing the eBPF services `ebpfsvc`, `ebpfcore`, and …
=> Add script to forcefully remove ebpf-for-windows

.github/workflows/perf.yml
This pull request includes a minor change to the `.github/workflows/perf.yml` file. The change adds a `repository` field to the `with` section under `jobs`. This field is set to the current GitHub repository, which allows the workflow to know which repository to use for the build.
CI/CD
No.
No.
=> Add missing required option for reusable-build.yml

.github/workflows/cicd.yml, .github/workflows/netperf.yml
Pickup the new combined artifacts containing both BPF and XDP performance data and publish both to Grafana.
CI/CD
No.
No.
=> Switch to merged netperf logs

scripts/install_ebpf.psm1
Updates Path after install so EbpfApi.dll can be found (instead of copying the dll to current directory). Fixes #3425
N/A
N/A
=> Update install script to refresh Path

.github/workflows/cicd.yml, libs/api_common/windows_platform_common.cpp, libs/execution_context/ebpf_program.c, libs/shared/ebpf_serialize.c, libs/shared/ebpf_serialize.h, libs/shared/ebpf_shared_framework.h, libs/shared/shared_common.c, libs/store_helper/ebpf_store_helper.c, scripts/config_test_vm.psm1
This PR patches some more gaps in #3326 that was found by the regression tests introduced by #3421. Specifically, the previous PR did not take into account the array of `ebpf_helper_function_prototype_t` in `ebpf_program_info_t`. Processing program information from an older extension can cause crashes if the size of the individual array elements are not considered. The solution was to "normalize" input `ebpf_program_data` to the latest version with safe defaults before processing them.
CI/CD with kernel mode regression tests.
No documentation impact.
No installer impact._
=> Various fixes to the extension version logic.

libs/shared/shared_common.c, scripts/config_test_vm.psm1
Fixes #3418
This PR fixes memory leak in `_duplicate_program_descriptor()` that was caught by fault injection tests.
Existing CICD
No
No
=> Fix memory leak in `_duplicate_program_descriptor()`

docs/isa-support.rst
* Put imm column after offset column
* Fix src_reg field name
* Narrow legacy instruction definitions to not have "any" where appropriate
* Fix callx line since issue #3237 is still open so not yet supported by bpf2c
No impact.
No impact.
=> Update isa-support.rst with latest from ebpf-docs

libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/shared/shared_common.c
Resolves: #3484
The values bpf_attach_type and link_type aren't meaningful to ebpfcore and it shouldn't block new values.
Copilot summary:
This pull request primarily focuses on enhancing the logging and error reporting mechanism in the `libs/execution_context` and `libs/shared` directories. The key changes include the addition of more detailed logging messages and the removal of certain conditions in the `ebpf_validate_attach_provider_data` function.
Enhancements to logging and error reporting:
* [`libs/execution_context/ebpf_link.c`](diffhunk://#diff-c14a8d075874a74f3dc279088def67e69e031f00016092c8da47dba0bb4513a1L156-R172): In the `_ebpf_link_client_attach_provider` function, the logging mechanism has been updated to provide more detailed information when the provider's `ModuleId` or …
=> Revert overly strict check in link attach to provider

.github/workflows/reusable-test.yml, tests/end_to_end/end_to_end.cpp
The current stack depth of 4 used for fault injection tests in PR is not able to currently find many issues. One reason can be that due to memory allocation wrappers used, 2 stacks are used just by `ebpf_allocate` and `cxplat_allocate`, leaving only 2 more stacks frames to be unique.
This PR increases the stack depth to 8. This change increases the `fault_injection` test time from ~4.5 minutes to ~9 minutes.
PR also contains a memory leak fix in unit_tests that was caught by increasing stack size to 8.
This PR updates tests.
No
No
=> Increase stack depth for PR fault_injection tests

.github/workflows/cicd.yml, .github/workflows/netperf.yml
This pull request includes changes to the CI/CD pipeline configuration files. The changes remove the job for uploading netperf results for Azure 2025 from the `.github/workflows/cicd.yml` file and the step for uploading test logs for Azure 2025 from the `.github/workflows/netperf.yml` file.
CI/CD pipeline changes:
* [`.github/workflows/cicd.yml`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L635-L647): Removed the job `upload_netperf_results_azure_2025` which was responsible for uploading netperf results for Azure 2025. This job was dependent on the `netperf` job and was only triggered on schedule or workflow dispatch events.
* [`.github/workflows/netperf.yml`](diffhunk://#diff-f2ba71ce9002e907f7355bdaf9e43385e451541fd886c97f1d89f80cf9697a46L56-L61): …
=> The netperf run fails due to missing Azure 2025 results

libs/execution_context/ebpf_maps.c
This pull request includes changes to the `libs/execution_context/ebpf_maps.c` file, focusing on improving the language and code readability in the `ebpf_core_object_map` structure and the `_lru_hash_table_notification` and `_create_lru_hash_map` functions.
* [`typedef struct _ebpf_core_object_map`](diffhunk://#diff-ae8a7da4edcb9e1f7c73d5704cb00d475c4f847515c8d97c08a178a326ccb27cL53-R53): Changed the term "double-linked lists" to "doubly-linked lists" for proper terminology usage.
* [`_lru_hash_table_notification`](diffhunk://#diff-ae8a7da4edcb9e1f7c73d5704cb00d475c4f847515c8d97c08a178a326ccb27cL1262-R1264): Reformatted the code to improve readability by moving the `break` statement to a new line.
* [`_create_lru_hash_map`](diffhunk://#diff-ae8a7da4edcb9e1f7c73d57 …
=> PR feedback

ebpfapi/dllmain.cpp, ebpfapi/ebpfapi.vcxproj
This pull request primarily involves changes to set up and support fuzz testing. The most significant changes include the addition of a new entry point in `dllmain.cpp`, the addition of a preprocessor definition in the `ebpfapi.vcxproj` file, and an update to the `ebpf-verifier` subproject.
Fuzz testing setup:
* [`ebpfapi/dllmain.cpp`](diffhunk://#diff-9a0fe5a5bacad3cf88ecd2809b3a5e8262ea280a656a1be38d8bb629e54628a5R35-R46): A new entry point `LLVMFuzzerTestOneInput` has been added to satisfy the requirements of the fuzzing engine. This function is not used in normal operation but is required for fuzz testing.
Project configuration:
* [`ebpfapi/ebpfapi.vcxproj`](diffhunk://#diff-f24d2e799e853ec88d6f9c478d3b150d7897efd5e687b8743c616b4a114f4026L157-R157): The preprocessor definition …
=> Update ebpf verifier

.github/workflows/reusable-test.yml
This pull request includes changes to the `.github/workflows/reusable-test.yml` file, specifically in the `jobs:` section. The changes involve setting up a local cache for Chocolatey (choco) packages and adding a cache entry for any installed choco packages. The cache key is based on the hash of the workflow file, so any changes to the choco packages in the file will invalidate the cache.
Key changes:
* [`.github/workflows/reusable-test.yml`](diffhunk://#diff-e386584fe70c301924ab6a8d4656b54ef92ed1961e6eb6f77c155be3475615f6R112-R130): Added a new step to create a local folder for caching Chocolatey packages. The cache location is set using the `choco config set` command. This step is skipped if the `should_skip` output of the `skip_check` step is 'true'.
* …
=> Cache choco packages to work around connectivity issues

docs/eBpfExtensions.md
Resolves: #3429 
Add to documentation clarify the purpose and scheme of the program information hash.
N/A
Yes.
No.
=> Add documentation to eBpfExtensions.md to clarify use of hash

docs/debugging.md, include/ebpf_api.h, libs/api/Verifier.cpp, libs/ebpfnetsh/elf.cpp, libs/ebpfnetsh/tokens.h, libs/service/verifier_service.cpp, tests/cilium/cilium_tests.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tests/unit/libbpf_test.cpp, tools/bpf2c/bpf2c.cpp
Resolves: #3569
This pull request includes changes to calls to the eBPF verifier to provide more detailed verbosity levels for verification results. The changes include the introduction of a new enum `ebpf_verification_verbosity_t` and replacement of the `bool verbose` parameter with `ebpf_verification_verbosity_t verbosity` in various functions. The verbosity level now allows for normal, informational, and verbose output. The changes also include modifications to test cases to accommodate the new verbosity levels.
Here are the most important changes:
Changes to verbosity levels:
* [`include/ebpf_api.h`](diffhunk://#diff-8b744ef020b2dae7afefac77b8d1d9664fa3d249c683b307cd393362da9f5e8bR112-R125): Introduced a new enum `ebpf_verification_verbosity_t` and replaced `bool verbose` parameter …
=> Add option to control the level of verbosity emitted by verifier.

tests/stress/km/stress_tests_km.cpp
The ```bindmonitor_tail_call_invoke_program_test``` multi-threaded stress test case exposes a potential issue in WFP where it does not confirm a filter delete request thereby causing the NetEbpfExt extension driver to hang forever during unload.
This is an OS level issue and as of now there's no ETA for the fix (Tracked by issue #3567).  
This PR conditionally disables this specific test until the WFP issue is resolved.
CI/CD run on self-hosted runner.
No documentation changes required.
No installer changes.
Fixes #3337
=> Disable tailcall multi-threaded stress test for now.

tools/bpf2c/bpf_code_generator.cpp
Resolves: #3579
The proposal [P2905R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2905r2.html) makes a breaking change to make_format_args to reject temporary values as arguments. Workaround is to create place holder variables to hold temporary and extend there lifetime.
CI/CD
No.
No.
=> Fix for breaking change P2905R2 in STL

docs/eBpfExtensions.md, include/ebpf_extension.h, libs/execution_context/ebpf_link.c, tests/end_to_end/helpers.h, undocked/tests/sample/ext/drv/sample_ext.c
This pull request primarily focuses on simplifying the function signatures for batch invocation in the eBPF program. The changes remove the `extension_client_binding_context` parameter from various functions across multiple files, making the functions easier to use since they now require fewer arguments. 
Removal of `extension_client_binding_context` parameter:
* [`docs/eBpfExtensions.md`](diffhunk://#diff-b183ad62c09db1f1cb4109ad107cba4e40c085d2e4a4635b5e7723fbce474310L353): The `extension_client_binding_context` parameter was removed from the `ebpf_program_batch_begin_invoke_function_t`, `ebpf_program_batch_end_invoke_function_t` functions. [[1]](diffhunk://#diff-b183ad62c09db1f1cb4109ad107cba4e40c085d2e4a4635b5e7723fbce474310L353) …
=> Cleanup batch APIs and remove unused parameter

tests/stress/km/stress_tests_km.cpp
This PR fixes bugs in the existing kernel-mode multi-threaded stress test. Specifically:
1. Ensure that the NetEbpfExt extension is restarted only if specified on the command line.
2. Ensure that native programs are consistently marked as such.
3. Ensure successful generation and loading of unique native program files where required.
Tested locally and via CI/CD runs on a private self-hosted runner.
Fixes #3453
=> Fixes for kernel mode multi-threaded test

include/ebpf_extension.h, libs/execution_context/ebpf_link.c
This PR moves `ebpf_link_dispatch_table_version_t` enum to `ebpf_extension.h`, so that extensions can also access the enum in case they want to work with an older version of ebpfcore.
Existing CICD
NA
No
=> Move `ebpf_link_dispatch_table_version_t` to `ebpf_extension.h`

ebpfapi/Source.def, include/bpf/libbpf.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_protocol.h, libs/runtime/ebpf_object.c, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp, tests/libs/util/ioctl_helper.cpp, tests/libs/util/ioctl_helper.h, tests/unit/libbpf_test.cpp
This PR does the following:
* Implement libbpf autoload APIs
* Make `bpf_program__set_type()` fail for native programs, since verification is done at compile time so the prog type cannot be changed after that.
* Add a test for the case of a file with maps but 0 programs.  Per the libbpf API contract, the load should succeed and create the maps.
* Remove `program_type` from the load native programs ioctl, since it was unused and since a file loaded can contain programs of multiple types.
* Update `_load_invalid_program` in unit_tests to match the same function in api_test
Fixes #3555
Updated tests.
Updated docs.
No impact.
=> Implement libbpf autoload APIs

.github/workflows/cicd.yml, installer/Product.wxs, installer/ebpf-for-windows.wixproj, scripts/check_msi_installation_files_nativeonly_release.txt, tests/end_to_end/netsh_test.cpp
Fixes #3610
Fixes #3624
This PR fixes multiple issues related to new MSVC version:
1. Update the failing test show sections `tail_call_multiple_um.dll` to accept both old and new values.
2. Include VC redist binaries in `Release / NativeOnlyRelease` MSI to mitigate the issue of mismatched VC redist binaries.
Existing CICD
No
No
=> Multiple MSVC related fixes

.github/workflows/cicd.yml, scripts/config_test_vm.psm1, scripts/run_driver_tests.psm1
This PR contains the following changes:
1. Update regression tests to consume 0.17.0 artifacts.
2. Update script for the new URL of the release artifacts.
3. Skip test case `load_native_program_invalid4`: This test case has already been removed in the `main` branch as it is no longer valid (an empty sys file is allowed to be loaded). But this test exists in 0.17 release artifacts, and when the 0.17 tests are run against the latest ebpf runtime, the test fails. As a workaround to avoid a churn in 0.17 release, skipping this test.
Existing CICD, updated tests.
No
=> Update regression tests to 0.17

docs/InstallEbpf.md
With fix #3623 , VC redist package is no longer needed for Release MSI. Hence this PR removes the instruction from the installation.
_Do any existing tests cover this change? N/A
Are new tests needed? N/A
_Is there any documentation impact for this change? Yes
_Is there any installer impact for this change? N/A
=> Remove VC++ Redist package from installation instruction

.github/workflows/cicd.yml
The netperf repo is undergoing restructuring to become compliant with the MSFT internal policies. Until this is complete, the repo is unable to execute eBPF jobs correctly, so removing this from the daily scheduled run.
This pull request includes changes to the `.github/workflows/cicd.yml` file that modify the conditions under which certain jobs are executed. The jobs `netperf`, `upload_netperf_results_azure_2022`, and `upload_netperf_results_lab_2022` will now only run if the GitHub event name is 'workflow_dispatch', as opposed to previously when they would run on either 'schedule' or 'workflow_dispatch'. 
* [`.github/workflows/cicd.yml`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L601-R601): The `netperf` job will now only …
=> Remove netperf from daily schedule until it's fixed

Directory.Build.props, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_program.h, libs/runtime/ebpf_platform.h, libs/runtime/ebpf_random.h
Elide extra stack frame from BPF helper function calls, removing unnecessary wrapper functions from the final image.
This pull request primarily involves two categories of changes: the addition of the `EBPF_INLINE_HINT` macro to various function definitions in the `libs/execution_context/ebpf_maps.h`, `libs/execution_context/ebpf_program.h`, `libs/runtime/ebpf_platform.h`, and `libs/runtime/ebpf_random.h` files, and the addition of an `AdditionalOptions` tag in the `Directory.Build.props` file. The `EBPF_INLINE_HINT` macro serves as a hint to the compiler that the function should be inlined during link time code generation. The `AdditionalOptions` tag enables hinting to link time code generation that a function should be inlined.
Addition of `EBPF_INLINE_HINT`:
* …
=> Add hint to LTCG that code should be inlined

include/ebpf_store_helper.h, installer/Product.wxs, libs/api_common/store_helper_internal.cpp, libs/store_helper/ebpf_store_helper.c, libs/store_helper/user/ebpf_registry_helper.cpp
**Issue:**
When using libbpf APIs for attaching eBPF programs, the app / service needs to provide `bpf_attach_type` enum. ebpfapi.dll uses eBPF store to convert this enum to ebpf attach type guid. We recently took a change where we stopped populating eBPF store entries in HKLM, and they are now only updated in HKCU. That caused a regression and breaks any app / service that is running as LOCAL_SYSTEM.
**Fix:**
To mitigate the regressions, only in 0.17 release, update the store APIs to also attempt to update / delete / read from HKLM. If the update or delete operation fails due to ACCESS_DENIED, that error is absorbed, as the app may not be running as admin.
Existing tests.
No.
=> Update store APIs to also update HKLM

libs/ubpf/user/ubpf_user.c
This pull request primarily focuses on updating the `ubpf` submodule and resolving conflicts between Windows headers and `ubpf` headers. 
* [`external/ubpf`](diffhunk://#diff-ef001804bec5d3e67f97267c6195ad049b67fc392c2f42fbb86c15f358ef9173L1-R1): The `ubpf` submodule was updated. The commit hash was changed from `d370804a852b67f81c3aeed225ab646420d6b23e` to `2c2a68a2d9d3d9c4db159a03391a2841e8baa964`. This update could include various changes in the `ubpf` project that are not directly visible in this pull request.
* [`libs/ubpf/user/ubpf_user.c`](diffhunk://#diff-8390ee49b3d19d236d625f845a64b770c2e0be7bc5607d18bc1b60950c9b567fR34-R37): To avoid conflicts with the Windows headers, `near` and `far` were undefined before including the `ubpf` headers. These …
=> Fix conflict between Windows and ubpf headers

.github/workflows/netperf.yml, docs/eBpfExtensions.md, include/ebpf_extension.h, include/ebpf_program_types.h, include/ebpf_windows.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/runtime/ebpf_object.c, libs/runtime/ebpf_object.h, libs/runtime/unit/platform_unit_test.cpp, libs/shared/shared_common.c, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/performance/ExecutionContext.cpp, tests/unit/libbpf_test.cpp, undocked/tests/sample/ext/drv/sample_ext.c, undocked/tests/sample/ext/drv/sample_ext.h, undocked/tests/sample/ext/drv/sample_ext_drv.c
Fixes part of #3645
This PR adds (an optional) support for new `context_header`, where an extension can opt in to allocate an array of `uint64_t` of size 8 in the context passed to the eBPF program. The extra header allocated by the extension is then used by the eBPF runtime to store the eBPF state, instead of relying on per-CPU or per-thread runtime state to store tail call information.
With these changes, there is around **22**% improvement in the tail call numbers.
```
C:\performance>release\bpf_performance_runner.exe -i tests.yml -e .sys -r -t "bpf_tail_call"
Timestamp,Test,Average Duration (ns),CPU 0 Duration (ns),CPU 1 Duration (ns),CPU 2 Duration (ns),CPU 3 Duration (ns),CPU 4 Duration (ns),CPU 5 Duration (ns),CPU 6 Duration (ns),CPU 7 Duration (ns) …
```
=> Use `context_header` for tail call perf improvement

include/net/tcp.h, libs/execution_context/ebpf_link.c, libs/runtime/ebpf_bitmap.c
This pull request primarily focuses on modifying the assertions and structure packing in several files. The changes include replacing `C_ASSERT` with `static_assert` and adding more specific error messages, and adding `#pragma pack` directives to ensure correct alignment of structures in memory. 
Structural changes:
* [`include/net/tcp.h`](diffhunk://#diff-ff57716b18eaf625ed142c9cb45d80319f37663be3c35ef3001de8f614737111R5-R6): Added `#pragma pack(push)` and `#pragma pack(1)` before the `struct tcphdr` definition, and `#pragma pack(pop)` after it. This ensures that the structure is packed in memory without any padding, which is crucial for network protocols. [[1]](diffhunk://#diff-ff57716b18eaf625ed142c9cb45d80319f37663be3c35ef3001de8f614737111R5-R6) …
=> Upgrade all C_ASSERT to static_assert

ebpfapi/Source.def, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_map.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, tests/end_to_end/end_to_end.cpp, tests/libs/common/common_tests.cpp
Fixes #3572.
Add a new API in eBPF API.dll to write into a ring buffer map from user mode. This API issues an IOCTL which calls `bpf_ring_buffer_output` function to write user specified data into the ring buffer.
Updated unit and api tests to write messages into ring buffer interleaved with events that invoke eBPF programs (which in turn write into the same ring buffer).
No documentation impact.
No installation impact.
=> UM API to write into a ring buffer map.

tools/redist-package/ebpf-for-windows-redist.nuspec.in
This PR adds `export_program_info.exe` to the redist packge. Earlier extension drivers used to populate the eBPF store (HKLM), but since that support is now removed, the redist package also needs to include `export_program_info.exe` that will be used to populate the eBPF store on the target machine.
Existing CICD
No
No
=> Include `export_program_info.exe` in redist nuspec

.github/workflows/cicd.yml
Netperf tests were disabled in daily runs due to issues in the netperf repo. They appear to be fixed now, so re-enable it.
This pull request includes a change to the `cicd.yml` file in the `.github/workflows` directory. The `netperf` job has been updated to trigger not only on `workflow_dispatch` events, but also on `schedule` events. This means that the job will now run both when manually triggered and on a set schedule.
* [`.github/workflows/cicd.yml`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L617-R617): Updated the `if` condition for the `netperf` job to also trigger on `schedule` events. This allows the job to run both when manually triggered and on a set schedule.
CI/CD
No.
No.
=> Turn netperf on for daily runs

include/bpf/libbpf.h, libs/api/libbpf_map.cpp, tests/unit/libbpf_test.cpp
bpf_object__find_map_by_name():
- Set errno to ENOENT.
- Add a case to check errno set for invalid map name.
- Added errno in doxygen comment.
_Do any existing tests cover this change? No. 
Are new tests needed? Yes
_Is there any installer impact for this change?No
=> Set errno for bpf_object__find_map_by_name

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/shared/ebpf_shared_framework.h, libs/shared/shared_common.c
fixes #3717.
This PR introduces some execution context unit test around checking invalid program data. It also adds some asserts in `_ebpf_program_get_helper_address_info_from_program_data`. Finally, it changes the general helper prog info provider to use `global_helper_function_addresses` instead of `program_type_specific_helper_function_addresses`.
CI.
No documentation changes are needed.
No installation changes are needed.
=> invalid prog data tests.

docs/eBpfStringLibraryProposal.md, docs/eBpfStringsAPI.md
Documentation discussing the addition of a subset of the C <strings.h> library, to enable use cases for eBPF programs where string operations are needed, in lieu of individual extensions providing their own versions, or programs needing to implement basic standard library functions on their own.
N/A
=> Strings library API proposal

.github/workflows/cicd.yml
This pull request includes updates to the `.github/workflows/cicd.yml` file to enhance the conditions under which certain jobs are triggered. The changes ensure that the `upload_netperf_results_azure_2022` and `upload_netperf_results_lab_2022` jobs can now be triggered by both scheduled events and manual workflow dispatches.
Trigger condition updates:
* [`jobs.upload_netperf_results_azure_2022`](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L640-R640): Modified the `if` condition to trigger on both `schedule` and `workflow_dispatch` events. (`.github/workflows/cicd.yml`, [.github/workflows/cicd.ymlL640-R640](diffhunk://#diff-6727e33ccc9195d67f0786e1384f8f1cdaf4090c3e77547943105bd2b28c99d0L640-R640))
* …
=> Upload netperf results on schedule runs

ebpf-for-windows.sln
The drivers all depend on the generated git_commit_id.h file produced by the setup_build step. Adding a explicit dependency to ensure ordering.
This pull request includes changes to the `ebpf-for-windows.sln` file to add project dependencies to several projects. These changes ensure that the build order respects the dependencies between projects, which is crucial for successful builds.
* [`ebpfcore\EbpfCore.vcxproj`](diffhunk://#diff-d00efcb84ca2af40bde26b29fa41062f1b0b2c305e9b3513fd60f6049826f0bcR89-R95): Added dependency on project `{231EE32B-EBA4-4FE5-A55B-DB18F539D403}`.
* [`netebpfext\sys\netebpfext.vcxproj`](diffhunk://#diff-d00efcb84ca2af40bde26b29fa41062f1b0b2c305e9b3513fd60f6049826f0bcR89-R95): Added dependency on project `{231EE32B-EBA4-4FE5-A55B-DB18F539D403}`.
* …
=> Add dependency for git_commit_id.h

libs/runtime/ebpf_error.c
windows_error_to_ebpf_result was renamed to
win32_error_code_to_ebpf_result moved to ebpf_utilities.h back in 2022 but this comment was missed.
No impact.
No impact.
No impact.
=> Correct obsolete comment

netebpfext/net_ebpf_ext_sock_addr.c
Fix an AV in netebpfext. In `_net_ebpf_ext_purge_blocked_connect_contexts()`, `connection_context` entry is accessed after it has been freed.
Existing CICD.
No
No
=> Fix AV in netebpfext

include/ebpf_nethooks.h, netebpfext/net_ebpf_ext_program_info.h, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, scripts/execute_ebpf_cicd_tests.ps1, tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c, tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c, tests/bpf2c_tests/expected/sockops_dll.c, tests/bpf2c_tests/expected/sockops_raw.c, tests/bpf2c_tests/expected/sockops_sys.c, tests/end_to_end/helpers.h, tests/netebpfext_unit/netebpfext_unit.cpp, tests/sample/cgroup_sock_addr2.c, tests/sample/sockops.c, tests/socket/socket_tests.cpp, tests/socket/socket_tests_common.h
This fixes #3742.
This PR overrides the global helper function `bpf_get_current_pid_tgid` in the sock_ops hook. The WFP flow established layer classify callback provides the process Id for the connection being established. This value is cached in the sock_ops context.
This PR also overrides the global helper function `bpf_get_current_pid_tgid` in the sock_addr hook but keeps the legacy `bpf_sock_addr_get_current_pid_tgid` helper for backward compatibility.
Both the overriden helpers use the implicit context feature.
New tests added.
No changes needed.
No changes needed.
=> Override `bpf_get_current_pid_tgid` for sock_ops hook.

docs/GettingStarted.md
- ntosext extensions added in the GettingStarted.md
_Do any existing tests cover this change? Are new tests needed? N/A
_Is there any documentation impact for this change? Yes
_Is there any installer impact for this change? N/A
=> Added ntosext extensions in the GettingStarted.md document.

scripts/config_test_vm.psm1
Our CICD was hitting intermittent failures to extract zip files. The error codes generally indicate a corrupted file. This change adds logic to delete and re-try the download and extraction of a downloaded zip file in our test scripts to help reduce failures when this occurs.
Closes #3809
Local execution + CICD
n/a
n/a
=> Add retry logic when scripts fail to extract a zip file

libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_epoch.h, libs/runtime/ebpf_work_queue.c, libs/runtime/ebpf_work_queue.h
Resolves: #2863 
Resolves: #3768 
This pull request introduces several changes to enhance the epoch management system, primarily focusing on CPU activation and deactivation, and ensuring proper work queue assignment. The most important changes include adding new fields to the `ebpf_epoch_cpu_entry_t` structure, defining new functions for CPU activation and deactivation, and modifying existing functions to utilize these new mechanisms.
* [`libs/runtime/ebpf_epoch.c`](diffhunk://#diff-94ff44c39b70c06d386f9ecf50e23a03d48426267b588073db7e54b55a31c59dR54-R66): Added new fields `active` and `work_queue_assigned` to the `ebpf_epoch_cpu_entry_t` structure to track CPU activity and work queue assignment.
* [`libs/runtime/ebpf_epoch.c`](diffhunk://#diff-94ff44c39b70c06d386f9ecf50e23a03d48426267b5880 …
=> Support dynamically adding and removing CPUs from epoch tracking

libs/runtime/ebpf_epoch.c
This pull request includes two changes to the `libs/runtime/ebpf_epoch.c` file that address assertion behavior and epoch handling in the eBPF runtime.
Assertion behavior update:
* Modified the `EBPF_EPOCH_FAIL_FAST` macro to correctly pass the assertion string to `ebpf_assert`. (`libs/runtime/ebpf_epoch.c`)
Epoch handling update:
* Updated the `_ebpf_epoch_messenger_propose_release_epoch` function to use `message->message.propose_epoch.current_epoch` instead of `cpu_entry->current_epoch` for setting the `freed_epoch` field. (`libs/runtime/ebpf_epoch.c`)
CI/CD
No.
No.
=> Set the freed_epoch to current_epoch, not 0

libs/runtime/ebpf_epoch.c
Resolves: #3855
Ensure that the CPU is only activated from the current CPU and never activated from another CPU.
CI/CD
No.
No.
=> Prevent double activation

docs/ReleaseProcess.md
Add an instruction to add a remote to the Microsoft github repo.
doc change.
doc change.
N/A.
=> update release doc.

Directory.Build.props, tests/sample/sample.vcxproj
This pull request introduces changes to streamline the build process by centralizing the Clang executable definition. The main changes include adding a new property for the Clang executable path and updating various build commands to use this new property.
* [`Directory.Build.props`](diffhunk://#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eR36-R38): Added a new property `ClangExec` to define the path to the Clang executable.
* [`tests/sample/sample.vcxproj`](diffhunk://#diff-129f72ff74c074bbf70bb526469ee820be00f3fbea35315b3f0d6bda2e4b1375L175-R175): Updated multiple build commands to use the new `ClangExec` property instead of hardcoding the `clang` executable path. This change affects several custom build steps across different configurations, including `Debug`, …
=> Always use clang from Visual Studio folder

libs/api_common/store_helper_internal.cpp, scripts/config_test_vm.psm1, scripts/execute_ebpf_cicd_tests.ps1, scripts/install_ebpf.psm1, scripts/run_driver_tests.psm1, scripts/setup_ebpf_cicd_tests.ps1, scripts/vm_run_tests.psm1
This PR adds tests to run `api_tests` also as SYSTEM. This allows catching any ebpf store related regressions for services / apps running as SYSTEM.
Existing CICD + new tests
No
No
=> run `api_tests` as system

libs/execution_context/ebpf_maps.c, libs/runtime/ebpf_hash_table.c
This pull request includes several changes to the `libs/runtime/ebpf_hash_table.c` and `libs/execution_context/ebpf_maps.c` files to improve the handling of entry counts in hash tables. The main changes involve ensuring that entry counts are only managed when a maximum entry count is enforced.
* [`libs/runtime/ebpf_hash_table.c`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b256c40db9abc47c2aL58-R59): Modified the `struct _ebpf_hash_table` to ensure `entry_count` is only valid if `max_entry_count` is not `EBPF_HASH_TABLE_NO_LIMIT`.
* [`libs/runtime/ebpf_hash_table.c`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b256c40db9abc47c2aR372-R378): Updated `_ebpf_hash_table_bucket_insert` to increment `entry_count` only if `max_entry_count` is enforced and to …
=> Avoid unneeded atomic operations

installer/ebpf-for-windows.wixproj
This pull request includes a minor update to the `installer/ebpf-for-windows.wixproj` file. The change involves updating the `ProductVersion` property to reflect a new version number.
* [`installer/ebpf-for-windows.wixproj`](diffhunk://#diff-4462afcae70dc1060039e3e56938f7583048ef6f0cf3fe709a32a406958b6297L11-R11): Updated `ProductVersion` from `3.10` to `3.14`.
CI/CD
No.
Yes. Support for 3.14 installer features (like ARM64)
=> Switch WIX installer project to current wix version

libs/runtime/ebpf_hash_table.c, libs/runtime/ebpf_interlocked.c, libs/runtime/ebpf_platform.h
This pull request includes several changes to the `ebpf_hash_table` implementation to improve memory ordering and atomic operations. The most important changes are the introduction of helper functions for reading and writing hash table buckets, and the replacement of existing atomic operations with their "no fence" variants.
Memory ordering improvements:
* [`libs/runtime/ebpf_hash_table.c`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b256c40db9abc47c2aR343-R369): Added `_ebpf_hash_table_get_bucket` and `_ebpf_hash_table_set_bucket` helper functions to ensure correct memory ordering when accessing hash table buckets.
Atomic operations updates:
* [`libs/runtime/ebpf_hash_table.c`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b256c40db9abc47c2aL373-R400): …
=> Enforce memory ordering in RCU aware hash-table

libs/execution_context/ebpf_core.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/runtime/ebpf_hash_table.c, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_random.c, libs/runtime/ebpf_trampoline.c, libs/runtime/unit/platform_unit_test.cpp, tests/end_to_end/test_helper.cpp
This pull request includes several changes focused on improving compatibility and conditional compilation for different architectures, as well as enhancing the initialization and testing processes. The most important changes include updating function calls, adding conditional compilation guards, and modifying initialization procedures.
* [`libs/execution_context/ebpf_core.c`](diffhunk://#diff-865dda5cac7319d91467fb64555d4c45c2b428d6367b44df94f4d13fa56c7ab8L2315-R2317): Updated `va_start` and `va_end` function calls to standard versions. (`[libs/execution_context/ebpf_core.cL2315-R2317](diffhunk://#diff-865dda5cac7319d91467fb64555d4c45c2b428d6367b44df94f4d13fa56c7ab8L2315-R2317)`)
* [`libs/runtime/ebpf_hash_table.c`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b256c40db9a …
=> Wrap platform specific code in approriate #defines

libs/api/bpf_syscall.cpp, libs/api_common/api_common.hpp, libs/api_common/device_helper.hpp, tests/unit/libbpf_test.cpp
bpf(): do not return errors via errno
The Linux ABI returns all syscall errors via the function return value, not
via errno.
Fixes https://github.com/microsoft/ebpf-for-windows/issues/3749
Allow detecting if bpf() command is not implemented
Use SetLastError to indicate to callers that a bpf() command is not 
implemented. This avoids polluting the bpf() return value with platform
specific error returns while still allowing detection of this important
case.
Add forwards and backwards compatibility to bpf() emulation
On Linux, bpf() accepts a bpf_attr which is larger than what the syscall
expects, as long as the unknown fields are all 0. It also accepts a bpf_attr
which is smaller than what it expects, by assuming that all missing fields
are zero.
This allows forwards and backwards …
=> Backwards compatible fixes to bpf() syscall emulation

libs/api/ebpf_api.cpp, tests/unit/libbpf_test.cpp
On Linux, -1 is a commonly used value for "invalid fd". As such it makes more sense to return EBADF instead of EINVAL from object related API when a negative fd is passed.
_get_handle_from_file_descriptor() returns ERROR_INVALID_HANDLE, which turns into EBADF via the various compat layers. We can therefore simply remove the <= 0 check.
=> Return EBADF for negative object fds

libs/api/libbpf_object.cpp, tests/end_to_end/end_to_end.cpp, tests/unit/libbpf_test.cpp
The current implementation of bpf_obj_get doesn't follow libbpf semantics, because it always returns -1 on error, instead of returning the negative error number.
This is especially noticeable when trying to open a non-existant object, which should return -ENOENT.
See https://github.com/libbpf/libbpf/blob/caa17bdcbfc58e68eaf4d017c058e6577606bf56/src/bpf.c#L625-L626
=> Return ENOENT from bpf_obj_get when no pinned object exists

libs/execution_context/ebpf_maps.c, tests/unit/libbpf_test.cpp
Looking up an index which is larger than an array's length currently results in EINVAL. This doesn't match what Linux does, which is to return ENOENT.
Change the behaviour to return ENOENT instead.
=> bpf(): return ENOENT when looking up out-of-bounds index in array

.gitmodules, netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, netebpfext/sys/netebpfext_platform.h, netebpfext/user/netebpfext_platform.h
Issue:
Our KM stress tests revealed an issue in our netebpfext code. There is a single global WFP handle, but multiple threads could use this at the same time (such as two programs attaching in parallel), leading to errors in the WFP APIs.
Fix:
- Add per-provider handles
- Make all WFP engine handles use static sessions (this allows a separate WFP handle to access the same objects, such as the sublayer/callouts)
- Add proper cleanup logic to remove all WFP objects
Closes https://github.com/microsoft/ebpf-for-windows/issues/3607
Existing tests validate this functionality.
None.
None.
=> [netebpfext] Add per-provider WFP handles to avoid improper use from parallel invocations

libs/execution_context/ebpf_program.c, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_platform.h, libs/runtime/unit/platform_unit_test.cpp, tests/end_to_end/helpers.h
Resolves: #3868
This pull request focuses on refactoring the thread affinity handling in the eBPF platform code. The primary changes involve replacing the old thread affinity mechanism with a more robust CPU affinity system using `GROUP_AFFINITY`. Additionally, some unused functions were removed to clean up the codebase.
* [`libs/execution_context/ebpf_program.c`](diffhunk://#diff-6bd70efed6714c9e250113aa729f24539066345c2433fccee1928c62f6657320L2392-R2392): Replaced `ebpf_set_current_thread_affinity` with `ebpf_set_current_thread_cpu_affinity` and updated the type of `old_thread_affinity` to `GROUP_AFFINITY`. [[1]](diffhunk://#diff-6bd70efed6714c9e250113aa729f24539066345c2433fccee1928c62f6657320L2392-R2392) [[2]](diffhunk://#diff-6bd70efed6714c9e250113aa729f24539066345c2433fccee1928c62f665 …
=> Switch to group affinity to work correctly on systems with > 64 CPUs

libs/execution_context/ebpf_maps.c, tests/unit/libbpf_test.cpp
A lookup in an array map yields all zeroes if the index of the array is empty. This makes sense in the general case, but has surprising semantics when applied to nested maps like arrays of arrays. In this case, looking up an empty slot will succeed but the all zero value is interpreted as a zero ID, which causes an error when trying to create a map from that ID.
Follow the Linux semantics which return ENOENT in this special case.
=> Return ENOENT from array maps containing object references

ebpfcore/usersim/EbpfCore_Usersim.vcxproj, ebpfcore/usersim/EbpfCore_Usersim.vcxproj.filters, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_platform.h
This pull request includes several changes to the `libs/runtime/ebpf_platform` files and an update to the `external/usersim` submodule. The most important changes involve modifying the `ebpf_get_current_cpu` function to use a different method for retrieving the current processor number and adding an inline hint to the function declaration.
Changes to `ebpf_get_current_cpu` function:
* [`libs/runtime/ebpf_platform.c`](diffhunk://#diff-9dfbd58f5d316f64d047f68fc95883ef97c3c0b586a6a7e35a6835f3d3f0e4deL65-R65): Modified the `ebpf_get_current_cpu` function to use `cxplat_get_current_processor_number` instead of `KeGetCurrentProcessorNumberEx` and `KeGetProcessorIndexFromNumber`.
* [`libs/runtime/ebpf_platform.h`](diffhunk://#diff-2d8c1d862f7672b2b1bd853a82d62da9a2ce750835eaecca82b992a542dd31a7R2 …
=> Switch to cxplat_get_current_processor_number

docs/BpfSyscallCompatibility.md
As discussed during this weeks triage meeting, I've written up my considerations of how I can do a port of `ebpf-go` to Windows.
Updates #3729
=> Add proposal for ABI compatible bpf() emulation

include/linux/bpf.h, libs/api/bpf_syscall.cpp, tests/unit/libbpf_test.cpp
At this point we also take the first steps to fixing the existing ABI incompatibility. On the Linux side, care was taken to avoid most padding in bpf_attr. By forcing the compiler to refuse implicit padding we get a good heuristic for fields in the incorrect order.
These changes mean that union bpf_attr in linux/bpf.h is not source compatible with the Linux header anymore. It's not possible to be source compatible and ABI compatible at the same time because we're already using Linux type names with ABI incompatible definitions. For example BPF_OBJ_NAME_LEN differs, and the order of fields in struct bpf_prog_info, etc. also does not match.
Change the definition of union bpf_attr to be more convenient to work with. This allows refactoring the macro magic used to check for forwards and …
=> bpf(): make union bpf_attr Linux ABI compatible

libs/api/api_internal.h, libs/api/ebpf_api.cpp, tests/unit/libbpf_test.cpp
On Linux it is valid to pass NULL as next_key for queue type maps, since that map type doesn't really have a key. Return EINVAL instead of aborting the process via an assert.
=> Don't abort program if next_key is NULL in ebpf_map_get_next_key()

include/linux/bpf.h, libs/api/bpf_syscall.cpp, tests/unit/libbpf_test.cpp
Add support for creating nested maps via the bpf() syscall wrapper.
=> bpf(): allow creating nested maps

docs/tutorial.md
Correct the typos from `-section` to `--section`.
=> chore: fix section argument typo

scripts/cleanup_ebpf_cicd_tests.ps1, scripts/common.psm1, scripts/config_test_vm.psm1, scripts/execute_ebpf_cicd_tests.ps1, scripts/install_ebpf.psm1, scripts/setup_ebpf_cicd_tests.ps1
Have the setup, execute and cleanup scripts run as a job with a timeout. Upon timeout a VM checkpoint is taken and an error is returned from the script.
This addresses #3949 by making it easier to debug the next time a hang occurs.
CICD.
N/A.
N/A.
=> Run all scripts as job with timeout.

include/bpf_helpers_platform.h
Compiling against Windows eBPF headers produces object files which are not easily distinguishable from object files compiled against Linux headers. This is a problem for cross-platform tooling which wishes to inspect the contents of an ELF.
Emit a section .ebpf_for_windows with the contents 0x01 into ELFs compiled against the windows headers.
Updates #3956
=> Tag ELF files with platform specific section

.onefuzz/OneFuzzConfig.json
This pull request updates the `TargetBuildBranches` field in the `.onefuzz/OneFuzzConfig.json` file to change the target branch from `feature/security_fix` to `main`.
Configuration updates:
* [`.onefuzz/OneFuzzConfig.json`](diffhunk://#diff-68617b12f58cdcc9c85a499fa6ad5771fa2f572c9ca06bb5470b1e6b3c4e8226L9-R9): Changed the `TargetBuildBranches` field from `feature/security_fix` to `main` in multiple instances. [[1]](diffhunk://#diff-68617b12f58cdcc9c85a499fa6ad5771fa2f572c9ca06bb5470b1e6b3c4e8226L9-R9) [[2]](diffhunk://#diff-68617b12f58cdcc9c85a499fa6ad5771fa2f572c9ca06bb5470b1e6b3c4e8226L86-R86) [[3]](diffhunk://#diff-68617b12f58cdcc9c85a499fa6ad5771fa2f572c9ca06bb5470b1e6b3c4e8226L163-R163) [[4]](diffhunk://#diff-68617b12f58cdcc9c85a499fa6ad5771fa2f572c9ca06bb5470b1e6b3c4e8226L240-R240) …
=> Switch to fuzzing main branch

.github/workflows/cicd.yml
This pull request involves changes to the continuous integration and deployment workflow configuration in the `.github/workflows/cicd.yml` file. The primary change is the removal of a specific job related to uploading performance results to Azure.
Changes to CI/CD workflow:
* Removed the `upload_netperf_results_azure_2022` job, which included configurations for uploading performance results to Azure for Windows 2022 platform.
CI/CD
No.
No.
=> Remove netperf on azure upload attempt as azure VMs have been retired

libs/execution_context/ebpf_maps.c, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_platform.h
This pull request introduces changes to enhance the locking mechanisms in the eBPF platform by adding new functions for acquiring and releasing locks at dispatch level. The key updates include the introduction of new lock functions and modifications to existing functions to utilize these new mechanisms.
* [`libs/runtime/ebpf_platform.c`](diffhunk://#diff-9dfbd58f5d316f64d047f68fc95883ef97c3c0b586a6a7e35a6835f3d3f0e4deR55-R66): Added new functions `ebpf_lock_lock_at_dispatch` and `ebpf_lock_unlock_at_dispatch` for acquiring and releasing locks at dispatch level.
* [`libs/runtime/ebpf_platform.h`](diffhunk://#diff-2d8c1d862f7672b2b1bd853a82d62da9a2ce750835eaecca82b992a542dd31a7R226-R241): Declared the new functions `ebpf_lock_lock_at_dispatch` and `ebpf_lock_unlock_at_dispatch` to provide …
=> Avoid raising and lowering the IRQL if not needed

libs/execution_context/ebpf_maps.c, libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_epoch.h, libs/runtime/unit/platform_unit_test.cpp, libs/shared/ebpf_shared_framework.h
This pull request introduces cache-aligned memory allocation and deallocation functions to improve performance in the `ebpf_epoch` module. The main changes include adding new functions for cache-aligned memory operations and updating existing code to use these new functions.
* Added `ebpf_epoch_allocate_cache_aligned_with_tag` and `ebpf_epoch_free_cache_aligned` functions to handle cache-aligned memory operations. (`libs/runtime/ebpf_epoch.c`, `libs/runtime/ebpf_epoch.h`) [[1]](diffhunk://#diff-94ff44c39b70c06d386f9ecf50e23a03d48426267b588073db7e54b55a31c59dR459-R473) [[2]](diffhunk://#diff-94ff44c39b70c06d386f9ecf50e23a03d48426267b588073db7e54b55a31c59dR492-R509) [[3]](diffhunk://#diff-b2fcc909c78ebd178827ba44c049750e5352ec24c1b0459f96721ac3304a5829R60-R68) …
=> Add support for cache aligned epoch memory and switch maps to use it

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_platform.h, tests/performance/platform.cpp
This pull request includes changes to improve the performance and alignment of the LRU map implementation in the `ebpf_maps.c` file. The most important changes include adding a static assertion for cache alignment and switching the time query function to optimize performance.
Performance improvements:
* [`libs/execution_context/ebpf_maps.c`](diffhunk://#diff-ae8a7da4edcb9e1f7c73d5704cb00d475c4f847515c8d97c08a178a326ccb27cL1204-R1214): Replaced `ebpf_query_time_since_boot(false)` with `KeQueryInterruptTime()` to optimize the time query operation in the `_insert_into_hot_list` function.
Alignment improvements:
* [`libs/execution_context/ebpf_maps.c`](diffhunk://#diff-ae8a7da4edcb9e1f7c73d5704cb00d475c4f847515c8d97c08a178a326ccb27cR169-R170): Added a static assertion to ensure …
=> Speedup LRU by using the faster timestamp API

libs/execution_context/ebpf_core.c
Resolves: #4034
This pull request includes an optimization to the `_ebpf_core_trace_printk` function in the `libs/execution_context/ebpf_core.c` file. The change ensures that if the trace logging provider is not enabled, the function will return early, avoiding unnecessary processing.
Optimization to trace logging:
* [`libs/execution_context/ebpf_core.c`](diffhunk://#diff-865dda5cac7319d91467fb64555d4c45c2b428d6367b44df94f4d13fa56c7ab8R2324-R2328): Added a check to return early if the trace logging provider is not enabled, improving performance by skipping unnecessary operations.
CI/CD
No.
No.
=> Short circuit printk if tracing is not enabled

libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_hash_table.c
This pull request includes an optimization to the `_ebpf_epoch_release_free_list` function in the `libs/runtime/ebpf_epoch.c` file. The change involves prefetching the next entry to be removed, which can improve performance by reducing cache misses.
Performance optimization:
* [`libs/runtime/ebpf_epoch.c`](diffhunk://#diff-94ff44c39b70c06d386f9ecf50e23a03d48426267b588073db7e54b55a31c59dR616-R617): Added a prefetch instruction to the `_ebpf_epoch_release_free_list` function to prefetch the next entry that will be removed after the current one. This aims to improve performance by reducing cache misses.
CI/CD
No.
No.
Before:
```
Timestamp,Test,Average Duration (ns),CPU 0 Duration (ns),CPU 1 Duration (ns),CPU 2 Duration (ns),CPU 3 Duration (ns),CPU 4 Duration (ns),CPU 5 Duration (ns),CPU 6 …
```
=> Speedup walking the free-list

netebpfext/net_ebpf_ext_hook_provider.c
The socket hook takes a lot of stack as the WFP redirect code seems to require a lot of stack. If the eBPF program attached to a socket hook invokes further helper functions that allocate memory, the stack can grow too big and sometimes cause double fault. So increasing the stack expansion limit to 16KB.
CICD is sufficient for this.
No.
No.
=> expand stack to 16KB for sock_addr hook.

.vsconfig, docs/GettingStarted.md, scripts/Setup-DevEnv.ps1
Make it easier to install the necessary Visual Studio components. See https://learn.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019
=> add .vsconfig file

include/bpf_helper_defs.h, include/ebpf_structs.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_general_helpers.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_platform.h, tests/bpf2c_tests/expected/test_utility_helpers_dll.c, tests/bpf2c_tests/expected/test_utility_helpers_raw.c, tests/bpf2c_tests/expected/test_utility_helpers_sys.c, tests/libs/common/common_tests.cpp, tests/performance/platform.cpp, tests/sample/sample_common_routines.h, tests/sample/sample_test_common.h
This PR cherry-picks #4013 from main to release/0.20.
CICD is adequate for testing.
No.
No.
=> Cherry pick changes from main to release/0.20

libs/execution_context/ebpf_core.c, tests/libfuzzer/execution_context/libfuzz_harness.cpp
This pull request introduces new functionality for managing the pinning table in the eBPF core and updates the fuzzing harness to include this functionality. The most important changes include adding functions to initiate and terminate the pinning table and updating the fuzzing harness to call these new functions.
* Added `ebpf_core_initiate_pinning_table()` to allocate the pinning table.
* Added `ebpf_core_terminate_pinning_table()` to free the pinning table.
* Declared the new pinning table functions in `libfuzz_harness.cpp`.
* Updated the `fuzz_wrapper` destructor to call `ebpf_core_terminate_pinning_table()` and `ebpf_core_initiate_pinning_table()`.
CI/CD
No.
No.
=> Check for leaked ref-count when fuzzing

.github/workflows/reusable-build.yml
This pull request includes an update to the `reusable-build.yml` workflow file. The most important change is updating the URL for downloading the `bpf_performance` build artifact to a newer version.
Workflow update:
* [`.github/workflows/reusable-build.yml`](diffhunk://#diff-951765131741a39f193f7387e405bafacb9b9e836a17986e6c7480d6dc448cc3L225-R225): Updated the URL in the `Invoke-WebRequest` command to download `bpf_performance` version 0.11.0 instead of version 0.0.6.
CI/CD
No.
No.
=> Switch to v0.11.0 of BPF performance

libs/execution_context/ebpf_program.c
This pull request includes a change to the `ebpf_program_get_info` function in the `libs/execution_context/ebpf_program.c` file. The change ensures that the `map_ids` array is updated using a volatile user mode pointer to prevent potential issues with compiler optimizations.
* [`libs/execution_context/ebpf_program.c`](diffhunk://#diff-6bd70efed6714c9e250113aa729f24539066345c2433fccee1928c62f6657320L2112-R2113): Modified the `ebpf_program_get_info` function to use `WriteNoFence` for updating the `map_ids` array, ensuring proper handling of volatile user mode pointers.
CI/CD
No.
No.
=> Use volatile write when writing to user buffer

scripts/Update-WdkVersion.ps1, scripts/setup_build/packages.config.template, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj
This pull request introduces a new PowerShell script to automate the update of the Windows Driver Kit (WDK) version across multiple relevant files. The changes include the addition of the script itself, modifications to project files to support the dynamic versioning, and the creation of a template configuration file.
Key changes include:
* [`scripts/Update-WdkVersion.ps1`](diffhunk://#diff-372860234b0e5688890300c9a2da724549ecf1dbe8cc6ffac5994a62724ffbd1R1-R238): Added a script to update the WDK version in specified files, create backups, and roll back changes if errors occur.
* [`scripts/setup_build/packages.config.template`](diffhunk://#diff-ce751f2b2e2510a860e6c1785d2cdd5dcdbdfcfdb0782ccf6ed77af1aa95f587R1-R14): Created a new template file for `packages.config` to use a placeholder for …
=> Script to update WDK version

tests/sample/sample.vcxproj
This pull request includes updates to the `tests/sample/sample.vcxproj` file to ensure that custom build steps are only executed when the platform matches the host platform. This change improves the build configuration by adding an additional condition to the `ItemGroup` elements.
Build configuration improvements:
* [`tests/sample/sample.vcxproj`](diffhunk://#diff-129f72ff74c074bbf70bb526469ee820be00f3fbea35315b3f0d6bda2e4b1375L247-R247): Added condition to check if `'$(Platform)'=='$(HostPlatform)'` in multiple `ItemGroup` elements to ensure custom build steps are only executed when the platform matches the host platform. [[1]](diffhunk://#diff-129f72ff74c074bbf70bb526469ee820be00f3fbea35315b3f0d6bda2e4b1375L247-R247) [[2]](diffhunk://#diff-129f72ff74c074bbf70bb526469ee820be00f3fbea35315b …
=> Don't attempt to cross-compile native images

tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj
This pull request includes changes to the project configuration for ARM64 support.
Project configuration updates:
* [`tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj`](diffhunk://#diff-fc796b56abadfe08981eff727a9493359dbc2084b95990a738e9b0ed83d1f885L19-R25): Updated project configurations to replace ARM with ARM64 for both Debug and Release configurations.
CI/CD
No.
No.
=> Fix incorrect platform reference in kernel_mode_bpf2c.vcxproj

tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj
This pull request includes a change to the `tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj` file to update the import paths for the Windows SDK and WDK properties. The update ensures the paths are correctly formatted to include the platform and version in the appropriate order.
* [`tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj`](diffhunk://#diff-fc796b56abadfe08981eff727a9493359dbc2084b95990a738e9b0ed83d1f885L33-R34): Updated import paths to correctly format the platform and version.
CI/CD
No
No.
=> Fix hard-coded x64 paths

.github/workflows/upload-perf-results.yml
This pull request includes a small change to the `.github/workflows/upload-perf-results.yml` file. The change updates the path to the `check_perf_results.sql` script to ensure it is correctly located.
* [`.github/workflows/upload-perf-results.yml`](diffhunk://#diff-88e0670dc528bb3547c4ca7dfeca2c6f0d0c345cb778802a3eb7d9f2db4be040L105-R105): Updated the path to the `check_perf_results.sql` script from `./scripts/check_perf_results.sql` to `./check_perf_results.sql`.
CI/CD
No.
No.
=> Fix incorrect path to downloaded script

.onefuzz/OneFuzzConfig.json
This pull request includes changes to the `.onefuzz/OneFuzzConfig.json` file, focusing on updating the Azure DevOps (ADO) template configurations. The primary updates involve changing the organization, project, assigned user, area path, and iteration path for the ADO template.
Key changes:
* Updated the `Org` from `mscodehub` to `microsoft` in the ADO template.
* Changed the `Project` from `eBPFForWindows` to `OS`.
* Modified the `AssignedTo` field from a specific user (`alanjo@microsoft.com`) to a general status (`Active`).
* Updated the `AreaPath` to a more specific path: `OS\Core\IO Fabrics\Transports Security and SDN\eBPF`.
* Adjusted the `IterationPath` from `eBPFForWindows` to `OS`.
```
d:\oip>.\oip.exe tko file --config \ebpf-for-windows\.onefuzz\OneFuzzConfig.json
Sample bug GUID …
```
=> Update OneFuzzConfig.json to file in correct ADO project

scripts/setup-ebpf.ps1
Update setup-ebpf.ps1 to also explicitly grant LOCAL SERVICE permission to execute the required debug DLLS. This seems to be necessary to avoid error 1053 when installing on a new system via SSH.
Updates #3872
=> Grant LOCAL SERVICE permission to read and execute debug DLLs

include/ebpf_core_structs.h, include/linux/bpf.h, libs/api/api_internal.h, libs/api/bpf_syscall.cpp, libs/api/ebpf_api.cpp, libs/api/libbpf_object.cpp, libs/api_common/api_common.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_protocol.h, libs/runtime/ebpf_object.h, tests/unit/libbpf_test.cpp
Allow passing a name for maps and programs and allow retrieving it via BPF_OBJ_GET_INFO_BY_FD. This requires a bunch of glue code because the bpf_prog_info, etc. structs are not compatible with Linux.
=> bpf(): improve map and program compatibility

scripts/run_driver_tests.psm1
This change fixes #4114 by specifying the full path to the multi-thread tests. This change also handles the case where the test process failed to start.
Existing CICD is adequate.
No.
No.
=> Check if test process failed to start.

libs/execution_context/ebpf_core.c, tests/libfuzzer/include/fuzz_helper_function.hpp
Resolves: #4017
This pull request removes workarounds that were previously added to handle a bug in the `bpf2c_fuzzer` which caused crashes with null map pointers. These workarounds are no longer necessary as the bug has been fixed.
Key changes:
* Removed null map pointer checks in `_ebpf_core_map_find_element`, `_ebpf_core_map_update_element`, `_ebpf_core_map_delete_element`, `_ebpf_core_map_find_and_delete_element`, `_ebpf_core_tail_call`, `_ebpf_core_ring_buffer_output`, `_ebpf_core_map_push_elem`, `_ebpf_core_map_pop_elem`, and `_ebpf_core_map_peek_elem` functions in `libs/execution_context/ebpf_core.c`. [[1]](diffhunk://#diff-865dda5cac7319d91467fb64555d4c45c2b428d6367b44df94f4d13fa56c7ab8L2202-L2207) [[2]](diffhunk://#diff-865dda5cac7319d91467fb64555d4c45c2b428d6367b44df94f4d13fa56c7 …
=> Remove workaround for test failure

installer/Product.wxs, scripts/setup-ebpf.ps1
Resolves: #3760
This pull request includes a change to the `scripts/setup-ebpf.ps1` file to improve the uninstallation process of the eBPF MSI package. The most important change is the modification of the uninstallation command to use the MSI product code directly.
Improvements to uninstallation process:
* [`scripts/setup-ebpf.ps1`](diffhunk://#diff-6980b71c60f1fdf381b6bfb4fc4ed1f05d1a402be4f41bb919a3df808888c808L38-R39): Changed the uninstallation command to use the MSI product code `{022C44B5-8969-4B75-8DB0-73F98B1BD7DC}` instead of the MSI path, ensuring a more reliable uninstallation process.
CI/CD
No.
No.
=> Uninstall ebpf by product id

docs/DevelopmentGuide.md, docs/GettingStarted.md, scripts/format-code, scripts/format-code.ps1, scripts/generate-commitid.ps1
This fixes #4133 and #4134.
The changes update the clang version in the code format scripts to point to 18.1.8. It also changes the script to generate the git_commit_id.h file to use ascii encoding.
Existing tests cover this change. No new tests are needed.
No.
No.
=> Change clang version to 18.1.8 in formatting script.

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext.h, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_hook_provider.h
This is continuation to #4003 . This change moves the zombie list to each provider context and enables it for retail bits as well.
Existing tests cover this change. No new tests are needed.
No.
No.
=> changes to zombie list.

tests/bpf2c_tests/elf_bpf.cpp, tests/sample/sample.vcxproj, tools/bpf2c/Convert-BpfToNative.ps1.template, tools/bpf2c/bpf2c.cpp
Resolve: #3879
Add option to print verbose verification results on failure.
CI/CD
No.
No.
=> Add --verbose option to bpf2c

libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/api_common/api_common.cpp, libs/api_common/api_common.hpp, libs/api_common/windows_platform_common.cpp, libs/api_common/windows_platform_common.hpp, libs/ebpfnetsh/elf.cpp, libs/service/api_service.cpp, libs/service/verifier_service.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tests/end_to_end/test_helper.cpp
Fixes #3884
This PR also fixes an issue uncovered by adding more SAL annotations.  Specifically, _ebpf_api_elf_verify_program_from_stream() was passing a possibly NULL stats pointer to ebpf_verify_program() which would dereference it and crash.
Added a new unit test to run "show verif" on bindmonitor_bpf2bpf.c which has multiple programs and sections
No impact.
No impact.
=> netsh ebpf show verif should verify all sections

external/Directory.Build.props
Internal tools are failing because not all binaries are built with at least /W3.
This change sets the default warning level in all external projects to /W3.
CI/CD
No.
No.
=> Set /W3 for all external projects

.github/CODEOWNERS, docs/Governance.md
Proposes a new project management policy.
N/A.
This is a documentation only change.
N/A.
=> project milestone issue limit.

docs/eBpfExtensions.md, ebpfapi/Source.def, include/bpf/libbpf.h, include/ebpf_extension.h, include/ebpf_windows.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/ebpf_protocol.h, libs/shared/shared_common.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, tests/end_to_end/helpers.h, tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp, tests/netebpfext_unit/netebpfext_unit.cpp, tests/unit/libbpf_test.cpp
Resolves: #3576 
As requested by @shankarseal this is a breaking change (to keep the change simple) as the ebpf_extension_data_t wasn't following the correct contract for structures exposed to extensions.
This pull request introduces several enhancements and new features to the eBPF program management system, primarily focusing on adding support for program flags and improving the handling of extension data. Below are the most significant changes grouped by theme:
* Added functions to query and set BPF program flags in `libbpf.h` and `libbpf_program.cpp`, allowing for better control over program behavior. [[1]](diffhunk://#diff-51005a88f9d069f59b4799b56c3a9430d710a514feea4ee723e63cddc50edcb2R920-R944) [[2]](diffhunk://#diff-780511a42f3cac926001942e228bf075fec98dafebcbef6f1c6f5ce257068839R7 …
=> Add support for program loading flags - breaking change version

libs/api/Verifier.cpp
Resolves: #4177
This pull request includes an important change to the `libs/api/Verifier.cpp` file to improve error handling when parsing BTF map information and populating the cache.
Error handling improvements:
* [`libs/api/Verifier.cpp`](diffhunk://#diff-c7cabf550a3d7ec7f53d5aaf8ea0e8a77d949e886b3c0f492ebd75228756b40fL159-R163): Added a check to handle cases where a map name is not found in `btf_map_name_to_index`. If a map name is not found, it now throws a `std::runtime_error` with a descriptive message.
CI/CD
No.
No.
=> Detect cases where maps in symbol table and btf differ

ebpfapi/Source.def, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/ebpfnetsh/pins.cpp, libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, libs/runtime/ebpf_pinning_table.c, libs/runtime/ebpf_pinning_table.h, tests/end_to_end/end_to_end.cpp
It's currently not possible to find pinned maps and links. Add a function ebpf_get_next_pinned_object_path which allows doing just that.
The paths are returned in lexicographical order, which allows user space to performa a prefix match on the paths. Behind the scenes this is implemented using a linear scan of the hash table, which has quadratic running time. The same is already the case for finding the next object ID, so going with the more desirable semantics makes sense.
The existing ebpf_get_next_pinned_program_path() is deprecated because it is less flexible than the new function.
Updates https://github.com/microsoft/ebpf-for-windows/issues/4161
=> Add ebpf_get_next_pinned_object_path

scripts/execute_ebpf_cicd_tests.ps1
There are known issues with Netepfext service stop hanging. While we investigate the issues, temporarily disable the service stop to prevent noise in dev work.
Issue tracking Netebpfext service stop hang: #4199
Removes service stop as part of test execution.
n/a
n/a
=> Temporarily skip stopping ebpf services in testing

ebpfapi/Source.def, include/ebpf_api.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/api_common/windows_platform_common.cpp, libs/thunk/mock/mock.cpp, libs/thunk/mock/mock.h, libs/thunk/platform.h, libs/thunk/windows/platform.cpp, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/libs/common/common_tests.h
This PR exports various functions required to make the ebpf-go port work. They fall into the following categories:
* Functions dealing with the osfhandle machinery. There is no easy / reliable way to access the correct ucrt function from Go without re-exporting.
* Functions which mirror existing functionality but return fd_t in some fashion, instead of operating on libbpf objects. This is necessary because the library has different semantics than libbpf.
* Functions to translate between GUID and libbpf enums. These are necessary because the data types in the Go library can not accommodate GUIDs. Hence we need use enums and transparently map to GUID.
Commit messages below
---
Export ebpf_close_fd and ebpf_dup_fd
Export functions used to manipulate fd_t. This makes the use of the UCRT …
=> Export functions necessary for ebpf-go port

.github/workflows/reusable-test.yml, libs/api/ebpf_api.cpp
Resolves: #4218 
Resolves: #4220 
This pull request includes a small change to the `.azure/reusable-test.yml` file. The change sets the `EBPF_ENABLE_WER_REPORT` environment variable to `yes` before running the test command.
* [`.azure/reusable-test.yml`](diffhunk://#diff-dcac258e0d6e06538fee721d1158f5806bd9bfcce3ee3161275761af9c314e80R224): Added `set EBPF_ENABLE_WER_REPORT=yes` to the script section to enable WER (Windows Error Reporting) for eBPF.
CI/CD
No.
No.
=> Enable WER for tests without code coverage

scripts/Set-Version.ps1, scripts/onebranch/post-build.ps1, tools/nuget/ebpf-for-windows.nuspec.in, tools/nuget/nuget.vcxproj, tools/redist-package/ebpf-for-windows-redist.nuspec.in, tools/redist-package/redist-package.vcxproj
This change:
* Modifies the post-build script to copy the unsigned nupkgs to the `packages` subdirectory under `build\bin\<arch>`. This directory is monitored by internal pipelines to publish nuget packages.
* Updates the name of the core package to include the configuration in the generated name, for non-release configurations. eg. `eBPF-for-Windows.x64` for the "NativeOnlyRelease" configuration and `eBPF-for-Windows.x64.NativeOnlyDebug` for the "NativeOnlyDebug" configuration.
* Updates the name of the SDK package to include the architecture in the generated name. Similar to the core package, it may also include the configuration for non-release configurations. eg. `eBPF-for-Windows-Redist.x64` or `eBPF-for-Windows-Redist.x64.NativeOnlyDebug`
Internal pipelines were run and confirmed to …
=> Organize nupkgs for publishing

tools/bpf2c/bpf_code_generator.cpp
Resolves: #4212
In the case of bss sections (with no data), limit the section size to a reasonable value.
CI/CD
No.
No.
=> Limit bss section size to reasonable value

.github/workflows/reusable-build.yml
Switch from version 0.11.0 to version 0.12.0 of BPF performance suite to handle breaking changes in bpf2c.
CI/CD
No.
No.
=> Pickup bpf_performance with post-breaking changes

include/ebpf_structs.h, libs/runtime/ebpf_object.c, tests/end_to_end/netsh_test.cpp, tests/unit/libbpf_test.cpp
Set the value of EBPF_ID_NONE as proposed in #4098. 
Closes #4098.
Changes made to expected output in testcases that expected value of EBPF_ID_NONE to be UINT32_MAX.
NA
NA
=> set EBPF_ID_NONE to 0

tests/stress/um/stress_tests_um.cpp
Resolves: #3720
Test was calling REQUIRE from a non-main thread, which is not permitted by CATCH2. Switch from REQUIRE to an ebpf_assert.
CI/CD
No.
No.
=> Remove REQUIRE from non-main thread

.github/workflows/reusable-build.yml, tests/sample/sample.vcxproj
Use $(ClangExec) in place of clang to select the correct version of Clang.
CI/CD
No.
No.
=> Fix llvm build break on new GitHub runners

ebpfapi/Source.def, include/ebpf_api.h, libs/api/api_internal.h, libs/api/bpf_syscall.cpp, libs/api/ebpf_api.cpp, libs/api_common/api_common.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_core.c
Export a function which allows retrieving the object info along with its type. bpf_obj_get_info_by_fd is almost identical but requires the caller to know the type of the object.
=> Export ebpf_object_get_info_by_fd

libs/thunk/windows/platform.cpp, tests/libs/util/wer_report.hpp
Fix race condition in _invalid_parameter_suppression
Invalid parameter suppression currently sets the global invalid parameter
handler. This means that concurrent execution may lead to executing the
wrong handler.
Instead, always set and restore the thread local handler.
Write debug assertions to stderr before terminating process
Report assertions and errors to standard error before terminating the 
process.
Stop changing the reporting mode in _invalid_parameter_suppression because
the mode is a global setting which shouldn't be changed by a library.
Fixes https://github.com/microsoft/ebpf-for-windows/issues/4207
=> Improve _invalid_parameter_suppression

include/bpf/bpf.h, include/bpf/libbpf.h, include/bpf/libbpf_legacy.h, libs/api/api_internal.h, tests/unit/libbpf_test.cpp
Closes #3684. Removes `@exception` keyword from documentation. Fixes documentation of return values to be negative. Changed wording about return status value to be consistent with Linux libbpf documentation.
Fixed spelling mistakes in a few files.
N/A.
Documentation only change.
N/A.
=> remove @exception from documentation.

Directory.Build.props
Building the sample project fails if the clang path contains a space. Fix this by quoting "$(ClangExec)".
=> sample: fix build when clang path contains space

tools/redist-package/ebpf-for-windows-redist.nuspec.in
Update binary targets in redistributable NuGet package to `lib` directory to avoid NuGet exclusion of `package` directory. For some (undocumented) reason, placing content in a top-level `packages` directory prevents NuGet tooling from extracting that content. As such, the only files that get extracted are the 3 files placed in the package root, per below:
```Powershell
PS C:\> nuget install -Source C:\src\github\ebpf-for-windows\x64\Release eBPF-for-Windows-Redist -Version 0.21.0 -OutputDirectory C:\temp\packages
PS C:\> gci C:\temp\packages\eBPF-for-Windows-Redist.0.21.0 -Recurse
Directory: C:\temp\packages\eBPF-for-Windows-Redist.0.21.0 
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/20/2024 10:42 AM …
```
=> Fix content of redistributable NuGet package not being extracted on install/restore

include/ebpf_nethooks.h, netebpfext/net_ebpf_ext_program_info.h, netebpfext/net_ebpf_ext_sock_addr.c, tests/end_to_end/helpers.h
The `bpf_sock_addr_get_current_pid_tgid()` helper function is obsolete and is no longer needed.  This PR removes the function definition all all references to it in the codebase.
Tested locally.
No additional documentation needed.
No Installer impact.
Fixes #2111
=> Remove obsolete prog-specific helper function

libs/api_common/api_common.cpp, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/service/api_service.cpp, tests/bpftool_tests/bpftool_tests.cpp, tests/unit/libbpf_test.cpp
This PR fixes #4160 by allowing smaller output buffer than the size of the struct for `bpf_obj_get_info_by_fd` API. The changes were made for program, map and link objects. This PR found two incidental issues:
1. In JIT case, the `count_of_maps` for eBPF program object was set to the count of map references in individual instructions, instead of total number of unique maps referred to by the program.
2. The `query_map_definition` invoked `bpf_obj_get_info_by_fd` but did not check if the returned object type was indeed that of a map.
Test cases were added in libbpf unit tests to invoke ``bpf_obj_get_info_by_fd`  with smaller output buffers.
_Is there any …
=> support partial output buffer for get_info API.

libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/unit/execution_context_unit_test.cpp
Cleanup in perf event array map code.
- Comment updates.
- Log exit in ringbuf and perf array ebpf_api.cpp code.
- Confirm cpu id in ioctls.
Follow-up to #4144 as part of #658.
N/A
No impact.
=> Perf event array cleanup.

.vsconfig, scripts/.check-license.ignore, scripts/Setup-DevEnv.ps1
Clang shipping with Visual Studio currently doesn't support the bpf target, see https://github.com/microsoft/ebpf-for-windows/issues/4227 The same goes for clang 19 as distributed by chocolatey.
Install the older clang 18 using chocolatey to at least have a working build. Also prefer the chocolatey clang over Visual Studio clang for now.
=> Install working clang in Setup-DevEnv.ps1

tests/libfuzzer/README.md, tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
With this pull-request we are providing an extra argument to core helper fuzz tests "-helper" that helps fuzz test helper functions specific helper functions.
In LLVM initialize, after processing our custom arg we are working towards remove it before the libfuzzer can process it.
fuzz testing.
Reference -- 
https://llvm.org/docs/LibFuzzer.html
https://github.com/google/fuzzing/blob/master/tutorial/libFuzzerTutorial.md
=> issue1941 - fuzz sock_addr/ops/xdp

tests/libs/util/native_helper.cpp, tests/libs/util/native_helper.hpp, tests/socket/socket_tests.cpp
`socket_tests` uses `native_module_helper_t` to load native images, which internally calls REQUIRE(). In some cases `socket_tests` create `native_module_helper_t` in worker thread also. That causes issue as REQUIRE should not be called from worker threads.
This PR changes logic in native_module_helper_t to call REQUIRE only when it is created in main thread.
Existing CICD
No
No
=> Use SAFE_REQUIRE in native_helper

libs/api/Verifier.cpp, libs/api_common/api_common.cpp, tests/end_to_end/netsh_test.cpp, tests/sample/undocked/map.c
Resolves: #1993 
Pickup latest version of ebpf-verifier with fix for loop termination checks.
Update revert workaround in samples for missing loop support.
Update expected output now that "assume assertions is honored correctly".
CI/CD
No.
No.
=> Pickup version of ebpf-verifier that fixes loops

libs/api/ebpf_api.cpp
Resolves: #4343
If ebpf_map_subscribe fails it should cancel all pending IO and cleanup gracefully.
CI/CD
No.
No.
=> Cleanup map subscription on failure

scripts/run_driver_tests.psm1, tests/end_to_end/helpers.h
The api_tests have been intermittently failing since #4302 was merged. The additional perf buffer stress test is likely taking the test execution time to over the allotted 5 minutes and falsely claiming a hang. Investigation from the generated crash dumps does not indicate any hang. So we are extending the timeout for these tests to 10 minutes.
The first iteration of this PR hit a bug in the execution engine fuzzer, that exposed a regression introduced by #4267 in a test module that caused memory corruption. Fixing that.
Test automation changes.
N/A.
N/A.
=> Extend timeout of api_tests in the CICD task to 10 minutes

tools/nuget/ebpf-for-windows.nuspec.in, tools/redist-package/ebpf-for-windows-redist.nuspec.in, tools/redist-package/ebpf-for-windows-redist.props, tools/redist-package/redist-package.vcxproj
Fix issue where the redistributable NuGet package isn't restored when listed as a package dependency of another package. Eg.
```XML
<group targetFramework="native0.0">
<dependency id="eBPF-for-Windows-Redist" version="0.21.0" />
</group>  
```
This is due to the package not containing any content that targets the `native` target framework moniker (TFM). The package must contain at least one item group that specifies the `native` TFM, otherwise the dependency is silently ignored as the tooling doesn't detect any matching content. While the package does place content under `lib\native`, the `lib` directory is specifically excluded for native packages (see [Creating native packages](https://learn.microsoft.com/en-us/nuget/guides/native-packages)).
Also fix the issue where consumption of the …
=> Fix a few NuGet packaging issues

tools/onebranch/onebranch.vcxproj
Ensure OneBranch builds complete successfully.
The `onebranch.vcxproj` `<PostBuildEvent>` copies binary files to a destination which has `x64` encoded into the path, irrespective of the platform being built. This causes ARM64 binaries to be placed in a directory prefixed with `x64`, and hence, the OneBranch build signing tasks don't find the files, so doesn't sign them. This causes official builds to break due to code signing policy violation.
Fix this by using the `$(Platform)` variable value in destination path instead of `x64`.
Fixes #4371
* Inspection only so far. Local build kicked off.
N/A
N/A
=> Update OneBranch PostBuildEvent to use platform-scoped destination directory

.github/workflows/reusable-build.yml, scripts/validate_redist_nuget_architecture.ps1, tools/redist-package/ebpf-for-windows-redist.nuspec.in
Fixes #4381 
This PR fixes the nupsec for redist package to include the VC redist binaries for correct architecture.
No
No
=> Fix redist nuspec

include/linux/bpf.h, libs/api/api_internal.h, libs/api/bpf_syscall.cpp, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/service/api_service.cpp, tests/end_to_end/end_to_end.cpp, tests/unit/libbpf_test.cpp
The behaviour around verifier logs on Linux is quite subtle and a bit error
prone. One API that makes everything a lot easier is the log_true_size field
which informs the caller how big the provided buffer should be. Implement
support for the field in the bpf() syscall wrapper.
See #4378
=> bpf: support log_true_size for BPF_PROG_LOAD

.github/workflows/reusable-build.yml, tests/sample/undocked/map.c, tools/export_program_info/export_program_info.vcxproj, undocked/tools/export_program_info_sample/export_program_info_sample.vcxproj, wdk.props
Build ARM64 binaries natively on ARM64 runners to allow bpf2c to operate correctly.
CI/CD
No.
No.
=> Build arm64 binaries on arm64 runners

libs/execution_context/ebpf_program.c, libs/runtime/ebpf_object.c, libs/runtime/ebpf_object.h
As described in #4425 some of the fields in the core ebpf object structure don't match the naming conventions.
CI/CD
No.
No.
=> Naming of fields in ebpf_core_object_t is inconstent

.github/workflows/cicd.yml, scripts/config_test_vm.psm1, scripts/install_ebpf.psm1, scripts/setup_ebpf_cicd_tests.ps1
Resolves: #1874
Enable HVCI on the VM when running native only tests.
CI/CD
No.
No.
=> Enable HVCI for native only tests

docs/GettingStarted.md
Fixes: [#4429](https://github.com/microsoft/ebpf-for-windows/issues/4429)
This change adds the `-g` option to the clang compile commands in the `GettingStarted.md` instructions. This option is necessary to include since the generated elf file is subsequently disassembled and verified using `netsh ebpf` commands. The `-g` option includes debug symbols and other debugging information in the generated elf file, which is required for the disassembly and verification process.
No new tests are needed.
This change is solely a documentation impact.
No.
=> Added -g option to clang compile commands

tests/unit/libbpf_test.cpp
Description
This PR enhances the hash_of_map test case in libbpf_test.cpp by adding additional negative tests for inner map lookups. Specifically, it verifies that:
Looking up a non-zero key in the inner map fails as expected.
Looking up a clearly nonexistent key in the inner map also fails as expected.
These checks help ensure the correctness and robustness of map-in-map behavior, particularly for static initializers in native execution mode.
Fixes #3219 
Changes
Updated _hash_of_map_initial_value_test to include:
A lookup with a non-zero key (1) in the inner map, asserting failure and errno == ENOENT.
A lookup with a clearly nonexistent key (12345) in the inner map, asserting failure and errno == ENOENT.
Motivation
These additional tests improve coverage for negative scenarios and help …
=> Add negative lookup tests for inner map in hash_of_map test case

libs/execution_context/unit/execution_context_unit_test.cpp
Moves cleanup of the async queries from the end of the test into a scope guard to ensure cleanup when the fault injection tests inject failures.
Previously when a fault was injected earlier in the test one of the earlier REQUIREs would fail and it wouldn't cleanup the outstanding async queries.
Fixes #4436 
CICD
N/A
N/A
=> Cleanup perf array test async calls on failure.

docs/eBpfExtensions.md, include/ebpf_structs.h, scripts/initialize_ebpf_repo.ps1, tests/unit/libbpf_test.cpp
This fixes #3021 . This adds some documentation on the `ebpf_attach_provider_data_t->link_type` field.
It also expands the string representations of map type and link type and adds unit tests for that.
No new tests are needed.
This is a documentation change.
No installation changes.
=> update extension document and minor changes.

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, libs/runtime/ebpf_platform.h, libs/runtime/kernel/ebpf_platform_kernel.c, libs/runtime/user/ebpf_platform_user.cpp, libs/service/api_service.cpp, libs/service/api_service.h, scripts/check_binary_dependencies_ebpfsvc_exe_regular_debug.txt, tests/end_to_end/end_to_end.cpp, tests/end_to_end/test_helper.cpp, tests/end_to_end/test_helper.hpp
Resolves: #4427
This pull request introduces significant changes to the eBPF platform's code integrity handling and signature verification mechanisms. The updates replace the previous `ebpf_code_integrity_state_t` enumeration with separate boolean flags for Hyper-V Code Integrity and Test Signing states, expand the protocol to query these states, and implement a robust file signature verification process using Windows Trust APIs.
* Replaced `ebpf_code_integrity_state_t` with two boolean flags: `_ebpf_platform_hyper_visor_code_integrity_enabled` and `_ebpf_platform_test_signing_enabled` to track Hyper-V Code Integrity and Test Signing states. [[1]](diffhunk://#diff-865dda5cac7319d91467fb64555d4c45c2b428d6367b44df94f4d13fa56c7ab8L40-R41) …
=> Require Microsoft Corporation eBPF Verification issuer and EKU

docs/GettingStarted.md, docs/NativeCodeGeneration.md, tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp, tests/netebpfext_unit/netebpf_ext_helper.h, tests/netebpfext_unit/netebpfext_unit.cpp
Added concurrency tests for sock ops.
Added calls to flow_context deletion test api that will be added to usersim with [this pr](https://github.com/microsoft/usersim/pull/263).
Currently flow_context deletion is only triggered when client is detached. According to [this page](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nc-fwpsk-fwps_callout_flow_delete_notify_fn0) , flowDeleteFn  is called when flow terminates. This is not being tested.
The added test cases add coverage for deletion of flow context before client detach. 
Closes #2082 
Note: build will fail until the usersim changes get merged.
Tested unit test locally.
NA
NA
=> Add Concurrency tests for sock ops

Directory.Build.props, scripts/setup_build/packages.config, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj, wdk.props
Resolves: #4497 
Update to the latest WDK
CI/CD
No
No.
This pull request updates the Windows SDK and WDK versions across multiple configuration files to ensure compatibility with the latest version. The updates primarily involve changing the version from `10.0.26100.3323` to `10.0.26100.4204`.
* [`scripts/setup_build/packages.config`](diffhunk://#diff-802912bfde6b8ea411619105236cbcca7a2452e26911bc02617e5a4476da2c28L7-R13): Updated all package references for `Microsoft.Windows.SDK.CPP` and `Microsoft.Windows.WDK` to version `10.0.26100.4204`.
* [`tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj`](diffhunk://#diff-fc796b56abadfe08981eff727a9493359dbc2084b95990a738e9b0ed83d1f885L8-R8): Updated the `WDKVersion` property to `10.0.26100.4204`.
* …
=> Update to latest WDK

libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_native.c, libs/runtime/ebpf_hash_table.c, libs/runtime/ebpf_hash_table.h, libs/runtime/ebpf_pinning_table.c, libs/runtime/unit/platform_unit_test.cpp, libs/shared/ebpf_shared_framework.h
This PR fixes #4125 by associating an allocation tag with ebpf hashtable allocation functions.
No new tests are needed.
No impact on documentation.
No installer imapct.
=> use allocate with tags for hash table.

tools/netsh/ebpfnetsh.rc
…gram
This PR fixes the indentation of the pinned parameter help text in the netsh ebpf add program command. The previous formatting was misaligned, making the help output harder to read.
Fixes #4580 
No functional changes, so existing tests remain unaffected.
Improves help text formatting for better readability.
No impact on installation; this is a documentation/UX improvement only.
=> Fix indentation of "pinned" parameter help text in netsh ebpf add program

netebpfext/net_ebpf_ext_sock_ops.c, tests/netebpfext_unit/netebpfext_unit.cpp
- Currently the sock_ops classifyfn invokes the attached bpf program even if FwpsFlowAssociateContext0 has failed. Changed the logic to exit when FwpsFlowAssociateContext0 fails.
- When fault injection is enabled calls to FwpsFlowAssociateContext0 can fail. When this happens a call to test_sock_ops_v4_remove_flow_context will trigger an assert. [This pr](https://github.com/microsoft/usersim/pull/272) in usersim updates remove_flow_context and now it only deletes flow context if it exists. Bumping usersim to include this change
Closes #4584 
CICD
NA
NA
=> Fix sock_ops code flow and test

rpc_interface/rpc_interface.idl
Mark the filename parameter to the RPC method as required (cannot be null).
CI/CD
No.
No.
=> Prevent NULL filename in verify_and_authorize_native_image

scripts/vm_run_tests.psm1
There are a few primary motivations for removing the XDP tests:
1 - The XDP tests have been intermittently failing (See issue #4470).
2 - The XDP tests are utilizing a 'xdp_test' hook, which was created during previously development, but is not the actual production XDP hook, and is not needed.
3 - The XDP test hook should eventually be removed from netebpfext (See issue #2974).
For all of the above reasons, this PR removes the invocation of XDP tests. Note that the rest of the test code and scripts still exist, and can be fully removed when we complete issue #2974.
Removes the XDP tests from our kernel test suite.
n/a
n/a
=> Remove XDP tests

.github/workflows/cicd.yml
Disables regression tests while we make breaking changes prior to the v1.0 release.
Should be followed by a PR for #4664 after these breaking changes and the release are completed.
Closes #4671 
Only prevents regression tests from automatically running for PRs.
N/A
N/A
=> Disable regression tests for breaking changes.

tests/end_to_end/end_to_end.cpp
Fixes #4273 
Using bpf_prog_info for a map related test was causing a type mismatch. Changed info variable to be of type bpf_map_info.
No new tests needed.
No.
No.
=> Fixed pinned_path_count is always 0

ebpfapi/Source.def, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_link.cpp, libs/api/libbpf_program.cpp, libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_link.h, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test_jit.h, libs/execution_context/user/execution_context_user.vcxproj.filters, tests/api_test/api_test.vcxproj, tests/end_to_end/end_to_end.cpp, tests/end_to_end/end_to_end_jit.cpp, tests/end_to_end/helpers.h, tests/end_to_end/netsh_test.cpp, tests/libs/util/native_helper.cpp, tests/unit/libbpf_test_jit.cpp
eBPF for Windows link behavior doesn't match Linux. Linux behavior is that an active link keeps the program object alive, so that the program is only unloaded when the last link is closed.
Resolves: #4135
CI/CD - tests for new behavior
No.
No.
This pull request introduces a new "legacy mode" for eBPF links, which changes how link lifetimes are managed: links marked as legacy will not be automatically detached when the last user-mode reference is closed. This is particularly important for compatibility with legacy APIs and tools. The implementation includes API additions, updates to core link state management, and changes to how links are handled in various attach/detach scenarios.
**Legacy Mode Support for Links**
* Added new API `ebpf_link_mark_as_legacy_mode` to allow marking a link as …
=> Modify link behavior to hold reference on program

.github/workflows/cicd.yml
Extends #4663 to disable scheduled regression tests so scheduled pipelines can also be kept green through our breaking changes.
Completes #4671
Disables tests for breaking changes
N/A
N/A
=> Disable scheduled regression tests

ebpfapi/rpc_client.cpp, ebpfsvc/rpc_util.cpp, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/api/libbpf_link.cpp, libs/api_common/api_common.cpp, libs/api_common/device_helper.cpp, libs/api_common/store_helper_internal.cpp, libs/api_common/windows_platform_common.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_program.c, libs/runtime/ebpf_crypto_hash.c, libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_pinning_table.c, libs/runtime/ebpf_platform.c, libs/runtime/ebpf_trampoline.c, libs/runtime/ebpf_work_queue.c, libs/runtime/kernel/ebpf_platform_kernel.c, libs/runtime/unit/platform_unit_test.cpp, libs/runtime/user/ebpf_platform_user.cpp, libs/runtime/user/kernel_um.cpp, libs/shared/ebpf_serialize.c, libs/shared/ebpf_shared_framework.h, libs/shared/shared_common.c, libs/store_helper/user/ebpf_registry_helper.cpp, libs/ubpf/kernel/ubpf_kernel.c, libs/ubpf/user/ubpf_user.c, tests/end_to_end/helpers.h
Removes the deprecated internal API `ebpf_allocate()` as requested in issue #4674.
- **API Migration**: Replaced all calls to `ebpf_allocate(size)` with `ebpf_allocate_with_tag(size, EBPF_POOL_TAG_DEFAULT)`
- **Function Removal**: Removed the deprecated `ebpf_allocate()` function definition from `ebpf_shared_framework.h`
- **Codebase Wide**: Updated all callers across 29 files to use the non-deprecated API
The changes span across the entire eBPF codebase including:
- API layers (`ebpfapi/`, `libs/api/`)
- Runtime components (`libs/runtime/`, `libs/execution_context/`)
- Shared utilities (`libs/shared/`, `libs/api_common/`)
- Test utilities (`tests/end_to_end/`)
- **Functionality**: No functional changes - all allocations still use the same pool tag (`EBPF_POOL_TAG_DEFAULT`)
- …
=> Remove deprecated internal API ebpf_allocate()

ebpfapi/Source.def, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/ebpfnetsh/programs.cpp
Resolves: #4675 
Modify ebpf_program_atttach* APIs so they can emulate the old libbpf attach (with out links) as well as the new libbpf attach style (with links).
Removed temporary ebpf_link_mark_as_legacy_mode API.
CI/CD
Updated API doxygen.
No.
This pull request refactors the eBPF user-mode API to simplify program attachment workflows and management of link lifetimes. The main change is to make the output link pointer optional in program attach APIs, and to internalize legacy mode handling so callers no longer need to manually mark links as legacy. Several APIs and internal functions are updated to reflect these changes, and related cleanup is performed in both the API and sample code.
* Made the output link pointer (`struct bpf_link** link`) and link file descriptor (`fd_t* link`) …
=> Remove ebpf_link_mark_as_legacy_mode

tests/end_to_end/netsh_test.cpp, tests/end_to_end/netsh_test_helper.h, tests/end_to_end/test_helper.cpp, tests/unit/libbpf_test.cpp, tests/unit/libbpf_test_jit.cpp, tests/unit/libbpf_test_jit.h
Resolves #4261 
Some tests in libbpf_test.cpp and netsh_test.cpp only ran for JIT/Interpreted programs. Some of these tests should also run for native programs so for each applicable test, functionality was expanded so that the test would also run for native eBPF programs. 
No new tests needed.
No.
No.
=> Expanded certain unit tests to run for native programs

.github/workflows/cicd.yml, .github/workflows/reusable-build.yml, docs/remote-vm-setup.md, scripts/common.psm1, scripts/config_test_vm.psm1, scripts/execute_ebpf_cicd_tests.ps1, scripts/install_ebpf.psm1, scripts/setup_ebpf_cicd_tests.ps1, scripts/tracing_utils.psm1, scripts/vm_run_tests.psm1
This PR makes the following changes:
* Change the setup script to enable HVCI _before_ installing duonic. Empirical evidence suggests that duonic installation was failing post enabling HVCI. No causality has been established. This is merely a workaround to make forward progress.
* It sets `fail-fast: false` for the native only tests strategy matrix, so that failure in one flavor does not cancel the other.
* It re-enables XDP tests to be run conditionally.
* Refactor some functions so that setup/execution on local host, VM and remote VM share maximum code.
* Removes some dead code from the scripts.
* Additional logging.
This makes changes to the kernel driver test jobs.
No documentation changes.
No installation changes.
=> Miscellaneous changes to kernel driver test CICD jobs.

ebpfapi/Source.def, include/ebpf_api.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, tests/end_to_end/end_to_end.cpp
Remove deprecated APIs before 1.0 release.
Fixes #4673
Updated tests.
No impact.
No impact.
=> Remove deprecated ebpf_* APIs
