docs/tutorial.md
=> Update verifier to get latest disassembly format

ebpf-for-windows.sln, ebpfapi/ebpfapi.vcxproj, libs/api/ebpf_api.cpp, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_program_types.c, netebpfext/net_ebpf_ext.c, netebpfext/netebpfext.vcxproj, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tools/encode_program_information/encode_program_information.cpp, tools/encode_program_information/encode_program_information.vcxproj, tools/encode_program_information/encode_program_information.vcxproj.filters
Update driver to return encoded program information.
Update ebpf_api to decode program information.
=> Update driver to return ebpf_program_data_t to verifier

include/ebpf_api.h, include/ebpf_program_types.h, libs/api/Verifier.cpp, libs/api/api.vcxproj, libs/api/ebpf_api.cpp, libs/platform/ebpf_platform.h, libs/platform/ebpf_program_types.idl, tests/end_to_end/helpers.h, tools/encode_program_information/encode_program_information.cpp
Switch ebpf_program_type_descriptor_t::platform_specific_data to GUID
=> Switch ebpf_program_type_descriptor_t::platform_specific_data to GUID

.gitignore
Step 1 of making doxygen generate html docs as part of issue #71
=> Added html documentation folder to .gitignore

libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_protocol.h, libs/platform/unit/platform_unit_test.cpp, libs/platform/unit/platform_unit_test.vcxproj, tools/encode_program_information/encode_program_information.cpp
Add missing helper functions
Enforce state machine on ebpf_program_t
=> Add missing helper functions

docs/eBpfFileSystemHookProposal.md
Split source lines to make git diffs easier
Fix editorial nits
Add link to eBPF extensions doc
=> Improve clarity of filesystem proposal doc

README.md, docs/eBpfExtensions.md
Break source lines to make git diffs easier
Add definition of eBPF extension
Add MS-RPCE link
Make project name match the repo name
Various other editorial nits
=> Improve clarify of eBPF extensions doc

docs/DevelopmentGuide.md
=> Add guidance about order of header includes

docs/DevelopmentGuide.md
=> Add guidance to make sure all code is actually built

ebpfsvc/eBPFSvc.vcxproj, include/ebpf_program_types.h, libs/api/Verifier.cpp, libs/api/Verifier.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/windows_helpers.cpp, libs/platform/ebpf_platform.h, libs/platform/ebpf_program_types.c, libs/platform/ebpf_program_types.idl, tests/client/ebpf_client.vcxproj
=> Remove duplicate copy of helper prototypes from verifier

docs/DevelopmentGuide.md
=> Add advice to DevelopmentGuide about not using magic numbers

libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, netebpfext/net_ebpf_ext.c
Synchronize client detach and hook invocation
=> Synchronize client detach and hook invocation

include/ebpf_result.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/api/windows_platform.cpp, libs/api_common/api_common.hpp, libs/execution_context/ebpf_maps.c, libs/platform/ebpf_epoch.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_object.c, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_platform.h, libs/platform/ebpf_program_types.c, libs/platform/ebpf_serialize.c, libs/platform/ebpf_serialize.h, libs/platform/ebpf_trampoline.c, libs/platform/kernel/ebpf_extension_kernel.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_extension_user.c, libs/platform/user/ebpf_handle_user.c, libs/platform/user/ebpf_platform_user.cpp
Add static analysis annotations to the platform functions. 
=> First pass of adding SAL annotations

docs/GettingStarted.md, ebpfcore/ebpf_drv.c, ebpfsvc/svcmain.cpp, tests/libs/util/service_helper.cpp
Fixes #257.
1. Changes the test code and install code to install sbpfsvc as local service.
2. Updates the doc with the sc.exe command to create service as localservice.
3. Updates the SDDL in ebpfcore.sys to include SID for ebpfsvc.
=> Change ebpfsvc to LocalService

Analyze.default.ruleset, external/Analyze.external.ruleset, external/Directory.Build.props, include/ebpf_api.h, libs/api/Verifier.cpp, libs/api/ebpf_api.cpp, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_platform.h, libs/platform/ebpf_serialize.c, libs/platform/ebpf_trampoline.c, libs/platform/kernel/ebpf_extension_kernel.c, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_extension_user.c, libs/platform/user/ebpf_platform_user.cpp, netebpfext/ebpf_ext_attach_provider.c, netebpfext/ebpf_ext_attach_provider.h, tests/end_to_end/netsh_test.cpp, tests/libs/common/common_tests.cpp
Fix warnings due to C6011 - NULL pointer deref
=> Fix warnings due to C6011 - NULL pointer deref

.github/workflows/codeql-analysis.yml
=> Add scheduled CodeQL workflow

libs/platform/ebpf_epoch.c
Fix C6386 warning in ebpf_epoch_initiate
=> Fix C6386 warning in ebpf_epoch_initiate

Analyze.default.ruleset
=> Enable C6385 and C6386 rules

libs/platform/ebpf_serialize.c, tools/port_quota/port_quota.cpp
Fix issues flagged by CodeQL code scan
=> Fix issues flagged by CodeQL code scan

include/ebpf_nethooks.h, tests/sample/bindmonitor.c
=> Update hook prototypes to be usable by eBPF programs for sanity checking

Doxyfile, include/ebpf_nethooks.h, libs/api_common/windows_platform_common.cpp, mainpage.dox
Which will fill in content visible at https://microsoft.github.io/ebpf-for-windows/
Also fill in documentation on fields of some structs.
Fixes #259
=> Add main API reference page

include/ebpf_api.h, include/ebpf_helpers.h
=> Fix doxygen warnings

libs/execution_context/ebpf_link.c, libs/platform/ebpf_platform.h, netebpfext/ebpf_ext_attach_provider.c, netebpfext/ebpf_ext_attach_provider.h, netebpfext/net_ebpf_ext.c, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/ext/drv/test_ext.c
Attach provider gives the supported program type.
Link verifies that program type matches supported program type.
Resolves: #239
=> Verify that program type is supported by attach provider

docs/eBpfFileSystemHookProposal.md
Hello,
we ([Sartura](https://www.sartura.hr/blog/)) have been working with eBPF for some time and are interested in using eBPF for malicious file detection in the future.
The existing proposal for the FS filter hook looks like it will enable such a use case, so listing it in the proposal explicitly as an example scenario might be useful as it seems to be a common use case for FS filters.
Regards,
Juraj
=> Add signature based malware detection scenario to FS filter hook proposal

libs/execution_context/ebpf_core.c
Change bpf_map_update_elem to return result of insertion
Partially resolves: #357 
Will add an option to support flags in a second PR.
=> Change bpf_map_update_elem to return result of insertion

libs/execution_context/ebpf_program.c
Pull latest ubpf from upstream.
Fixup contract change with ubpf_exec.
=> Pull latest ubpf

include/ebpf_program_types.h, libs/execution_context/ebpf_core.c, libs/platform/ebpf_serialize.c, libs/platform/unit/platform_unit_test.cpp, tests/sample/ext/drv/sample_ext.c, tools/encode_program_info/encode_program_info.cpp
Prerequisite to resolve: #344 
=> Add code to propagate flags for helper functions.

libs/execution_context/ebpf_maps.c
Fix leak of ebpf_core_map_t.name.value
=> Fix leak of ebpf_core_map_t.name.value

libs/execution_context/ebpf_program.c
=> ebpf_program_t.links should be initialized

libs/platform/ebpf_epoch.c, libs/platform/kernel/ebpf_platform_kernel.c
=> fix epoch bug

libs/platform/ebpf_epoch.c
Partition epoch free list by CPU.
Resolves: #404
=> Partition epoch free list by CPU

libs/execution_context/ebpf_maps.c, libs/platform/ebpf_epoch.c, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp
PR feedback from #418 
Previous PR was closed before all feedback was fixed.
=> PR feedback from #418

include/ebpf_helpers.h, include/ebpf_result.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/platform/ebpf_state.c, libs/platform/ebpf_state.h, libs/platform/kernel/platform_kernel.vcxproj, libs/platform/kernel/platform_kernel.vcxproj.filters, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/platform_user.vcxproj, libs/platform/user/platform_user.vcxproj.filters, libs/service/api_service.cpp, tests/sample/tail_call.c, tests/sample/tail_call_bad.c, tests/unit/libbpf_test.cpp
Add support for stack unwind on success. 
Depends on: https://github.com/iovisor/ubpf/pull/88
=> Add support for stack unwind on success. Depends on PR #88 in uBPF

libs/platform/ebpf_epoch.c
Fix regression from commit: [b917cc5ba8c9166bc6383b2a3e0f41457bbb9978](https://github.com/microsoft/ebpf-for-windows/commit/b917cc5ba8c9166bc6383b2a3e0f41457bbb9978)
Bad merge rolled back a previous fix of this issue.
=> Fix bug in epoch rundown and flush timer

.github/workflows/build.yml, libs/platform/ebpf_epoch.c
=> Workaround for issue where ProcDump64 swallows return codes.

libs/platform/ebpf_epoch.c
Revert untested changes to epbf_epoch.c
=> Revert untested changes to epbf_epoch.c

libs/ebpfnetsh/ebpfnetsh.vcxproj, libs/ebpfnetsh/ebpfnetsh.vcxproj.filters, libs/ebpfnetsh/maps.cpp, libs/ebpfnetsh/maps.h, tests/end_to_end/netsh_test.cpp, tools/netsh/ebpfnetsh.rc, tools/netsh/resource.h
Also updates the "show programs" test to actually verify the output for a program.
=> Add netsh command to show maps

libs/platform/ebpf_epoch.c
ebpf_epoch: _ebpf_flush_timer_set should be per-CPU
=> ebpf_epoch: _ebpf_flush_timer_set should be per-CPU

ebpfapi/ebpfapi.vcxproj, ebpfcore/EbpfCore.vcxproj, ebpfsvc/eBPFSvc.vcxproj, netebpfext/netebpfext.vcxproj, tools/netsh/ebpfnetsh.vcxproj
This PR unblocked failure to build from VS that some folks have encountered.
=> Set ps unrestricted

ebpfapi/Source.def, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_internal.h, libs/api/libbpf_link.cpp, libs/api/libbpf_map.cpp, libs/api/libbpf_program.cpp, libs/api_common/api_common.hpp, tests/end_to_end/end_to_end.cpp, tests/unit/libbpf_test.cpp
Fixes #372
Addresses several leftover TODO comments referencing issue 81.
One is left for Anurag to do.
Also fixes bug where errno was not being set to correct errno values by libbpf apis
=> Add bpf_link_detach and bpf_link__fd APIs

.github/workflows/driver_test.yml
Testing adding a new dependent workflow.
=> Adding dependent workflow to run after build

tests/sample/ext/app/sample_ext_app.cpp
https://github.com/Alan-Jowett/ebpf-for-windows/pull/new/issue370
Resolves: #370
=> Run utility helper tests in both interpret and jit modes

.github/workflows/driver_test.yml
=> Remove dependency on run-tests.bat

tests/sample/sample_common_routines.h
=> Fix unreliable test

.github/workflows/driver_test.yml
Cache symbols of drivers loaded on kernel CI/CD machine
Partially addresses: #530 
=> Cache symbols of drivers loaded on kernel CI/CD machine

netebpfext/net_ebpf_ext_drv.c
First unregister for callouts, then unregister the provider.
Resolves: #531 
=> First unregister for callouts, then unregister the provider

libs/platform/ebpf_pinning_table.c
=> Provide blurb to explain how pinning table works

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/driver_test.yml
Remove unneeded download of boost.
=> Remove unneeded manual download of boost

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_link.h, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h
Fail link initialize if loading extension fails
Resolves: #537
=> Fail link initialize if loading extension fails

.github/workflows/build.yml, .github/workflows/driver_test.yml
=> Only run performance tests on release

.github/workflows/codeql-analysis.yml
CodeQl pipeline should run daily, not on every PR.
=> CodeQl pipeline should run daily, not on every PR

ebpfapi/ebpfapi.vcxproj, ebpfsvc/eBPFSvc.vcxproj, libs/api/api.vcxproj, libs/api_common/api_common.vcxproj, libs/ebpfnetsh/ebpfnetsh.vcxproj, libs/execution_context/user/execution_context_user.vcxproj, libs/platform/user/platform_user.vcxproj, libs/service/service.vcxproj, libs/ubpf/user/ubpf_user.vcxproj, rpc_interface/rpc_interface.vcxproj, scripts/setup_build/setup_build.vcxproj, tests/api_test/api_test.vcxproj, tests/client/ebpf_client.vcxproj, tests/libs/common/common_tests.vcxproj, tests/libs/util/test_util.vcxproj, tests/performance/performance.vcxproj, tests/sample/ext/app/sample_ext_app.vcxproj, tests/sample/ext/drv/sample_ext.vcxproj, tests/sample/ext/drv/sample_ext.vcxproj.filters, tests/sample/sample.vcxproj, tests/sample/sample.vcxproj.filters, tests/unit/test.vcxproj, tests/xdp/xdp_tests.vcxproj, tools/dnsflood/dnsflood.vcxproj, tools/elfhelper/elfhelper.vcxproj, tools/encode_program_info/encode_program_info.vcxproj, tools/netsh/ebpfnetsh.vcxproj, tools/port_leak/port_leak.vcxproj, tools/port_quota/port_quota.vcxproj
Disable /ZI and incremental linking
Resolves: #545 
=> Disable /ZI and incremental linking

.gitignore, ebpfapi/ebpfapi.vcxproj, ebpfcore/EbpfCore.vcxproj, ebpfsvc/eBPFSvc.vcxproj, netebpfext/netebpfext.vcxproj, scripts/setup_build/setup_build.vcxproj, tools/netsh/ebpfnetsh.vcxproj
=> Move generated include to include

libs/api/ebpf_api.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_protocol.h, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_pinning_table.h
=> Switch ebpf_pinning_table_get_next_name to use ebpf_utf8_string_t

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
=> Switch to clang 10 in CI/CD

tests/sample/sample.vcxproj
This happened due to a bad merge.
=> Remove duplicate entry in sample.vcxproj

.github/workflows/driver_test.yml, docs/SelfHostedRunnerSetup.md
This PR is an experiment to test building on the self-hosted runner, to see if the KM test correctly reports the status to github,
=> Add kernel test as part of PR checks

ebpfcore/ebpf_drv.c, libs/api_common/api_common.hpp, tests/end_to_end/test_helper.cpp
Addresses part of issue #595
A more comprehensive fix is left for a separate PR.
This PR fixes some bad error messages from "bpftool prog list", "bpftool map list", and "bpftool link list".
=> Simple error code conversion fixes

ebpfapi/Source.def, include/ebpf_api.h, include/ebpf_structs.h, libs/api/ebpf_api.cpp, libs/api_common/windows_platform_common.cpp, libs/api_common/windows_platform_common.hpp, libs/ebpfnetsh/links.cpp, libs/ebpfnetsh/programs.cpp, libs/execution_context/ebpf_link.c, libs/service/windows_platform_service.hpp, tests/end_to_end/netsh_test.cpp
* Add program type to netsh "show programs" output
* Add attach type to netsh "show links" output
=> Add program type and attach type to netsh output

ebpfapi/Source.def, include/bpf_helper_defs.h, include/ebpf_structs.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_map.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_general_helpers.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp
Add support for BPF_MAP_TYPE_QUEUE
Resolves: #567 Support for bpf_map_lookup_and_delete_elem helper and API.
=> Add support for bpf_map_lookup_and_delete_elem & BPF_MAP_TYPE_QUEUE

libs/platform/ebpf_bitmap.c
Provide more details on how ebpf_bitmap_t works.
=> Provide more details on how ebpf_bitmap_t works.

include/ebpf_nethooks.h
This PR adds BPF_FUNC_* enums for csum_diff() and xdp_adjust_head() helper functions
=> Add BPF_FUNC* enums for csum_diff() and xdp_adjust_head() helper functions

ebpfapi/Source.def, include/bpf/bpf.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_program.c, libs/execution_context/ebpf_program.h, libs/execution_context/ebpf_protocol.h, libs/platform/ebpf_platform.h, libs/platform/kernel/ebpf_platform_kernel.c, libs/platform/user/ebpf_platform_user.cpp, tests/unit/libbpf_test.cpp, tools/bpftool/bpftool.vcxproj
Also fixes a build dependency from bpftool to force ebpfapi to be built first
Fixes #379
=> Add libbpf bpf_prog_bind_map() API

docs/vm-setup.md
=> Add documentation on how to debug the kernel of a VM

include/ebpf_nethooks.h, netebpfext/net_ebpf_ext_xdp.c, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/netsh_test.cpp, tests/sample/droppacket.c, tests/unit/libbpf_test.cpp
=> add ingress interface index to xdp context.

libs/execution_context/ebpf_program.c
=> Update external/ubpf to latest

ebpf-for-windows.sln, libs/api/crab_verifier_wrapper.hpp, libs/api_common/ebpf_verifier_wrapper.hpp, libs/ebpfnetsh/elf.cpp, tests/end_to_end/netsh_test.cpp
=> Update to latest verifier code

include/ebpf_structs.h
=> Add doxygen comments on all map types and map options

tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/sample/decap_permit_packet.c, tests/sample/droppacket.c, tests/sample/encap_reflect_packet.c, tests/sample/reflect_packet.c, tests/sample/sample.vcxproj
This fixes #681 and performs some other test clean ups.
=> decap ip-in-ip.

docs/GettingStarted.md
This PR fixed issue https://github.com/microsoft/ebpf-for-windows/issues/683
=> updated version of Spectre-mitigated libs for GettingStarted.md

docs/GettingStarted.md
This PR updated GettingStarted doc based on the conversations of https://github.com/microsoft/ebpf-for-windows/issues/687
=> More improvements on GettingStarted.md

ebpfapi/Source.def, include/bpf/libbpf.h, include/ebpf_api.h, libs/api/ebpf_api.cpp, libs/api/libbpf_program.cpp, libs/api_common/api_common.hpp, tests/unit/libbpf_test.cpp
This is a prerequisite for one of the other issues assigned to me for this month.
Fixes #186
=> Add bpf_load_program, bpf_load_program_xattr APIs

scripts/deploy-ebpf.ps1, tests/sample/ext/app/sample_ext_app.cpp, tests/sample/ext/drv/sample_ext.c, tests/sample/ext/drv/sample_ext.h, tests/sample/ext/drv/sample_ext_drv.c, tests/sample/ext/inc/sample_ext_ioctls.h, tests/sample/ext/inc/sample_ext_program_info.h, tests/sample/test_sample_ebpf.c
* Hard code the extension name in only one place
* Change "Test" to "Sample" in various comments
=> Minor cleanup in sample extension

docs/GettingStarted.md
Currently clicking on the link gives a 404 error, which this PR fixes.
=> Fix broken link to InstallEbpf.md

tests/bpf2c_tests/Makefile, tests/bpf2c_tests/bpf2c_tests.vcxproj, tests/bpf2c_tests/bpf2c_tests.vcxproj.filters, tests/sample/sample.vcxproj.filters, tools/bpf2c/bpf2c.vcxproj, tools/bpf2c/bpf2c.vcxproj.filters, tools/bpf2c/bpf_code_generator.cpp, tools/bpf2c/bpf_code_generator.h, tools/bpf2c/btf.h, tools/bpf2c/btf_parser.cpp, tools/bpf2c/btf_parser.h
Parse BTF data if present and emit #line directives.
=> Parse BTF data if present and emit #line directives

libs/execution_context/ebpf_program.c, tests/api_test/api_test.cpp, tests/end_to_end/end_to_end.cpp
Add test to trigger division by zero handler.
Resolves: #668 
=> Add test to trigger division by zero handler

docs/GettingStarted.md
Update getting started guide to resolve VS2022 conflict.
Resolves: #761 
=> Update getting started guide to resolve VS2022 conflict

.github/workflows/driver_test_vm.yml, docs/SelfHostedRunnerSetup.md, scripts/config_test_vm.psm1, scripts/run_tests.psm1, scripts/setup_ebpf_cicd_tests.ps1, scripts/vm_run_tests.psm1
=> Collect and upload kernel crash dumps.

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml
Copied mostly from msquic. Happy to make any edits you'd like.
=> Proposal for Issue Template

tools/bpf2c/bpf_code_generator.cpp
Annotate prolog lines with #line directive.
Resolves: #812 
=> Annotate prolog lines with #line directive

.github/workflows/build.yml, .github/workflows/driver_test_vm.yml, .github/workflows/scorecards-analysis.yml
=> Cherry-pick dependabot prs

tools/bpf2c/bpf_code_generator.cpp
Fail code generation if the relocation for an EBPF_CLS_LD instruction points to a non-map.
Positive case covered by existing tests.
No.
Fixes: #855
=> Fail code generation for EBPF_CLS_LD with non-map relocation

.github/workflows/scorecards-analysis.yml
Reverts microsoft/ebpf-for-windows#845
=> Revert "Bump ossf/scorecard-action from 1.0.3 to 1.0.4"

tests/api_test/api_test.cpp, tests/libs/util/service_helper.cpp
This PR removes `printf` statements from `service_install_helper`. These printf statements mess with the kernel test scripts and cause false positives.
Also fixes an failing test which was caught due to these changes.
Existing test will cover this change.
NA
=> clean up printf statements from service_install_helper

README.md
Fix the code coverage badge on the README.md
None.
N/A
=> Fix code coverage badge in README.md

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml, scripts/config_test_vm.psm1, scripts/execute_ebpf_cicd_tests.ps1, scripts/run_driver_tests.psm1, scripts/vm_run_tests.psm1
Some tests are only executed inside self-hosted runner VMs. Code coverage for these is lost.
This is a new test.
Docs update.
=> Capture code coverage inside VM and upload

ebpfapi/Source.def, include/ebpf_api.h, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/execution_context/ebpf_maps.c, tests/end_to_end/helpers.h, tests/unit/libbpf_test.cpp
Add tests for operations on queues, and fix bugs caught by the tests.
And remove some unused code
Fixes #980 
None needed.
=> Fix push/pop APIs on queues

docs/InstallEbpf.md, libs/api/libbpf_program.cpp, scripts/deploy-ebpf.ps1, scripts/run_driver_tests.psm1, scripts/run_tests.bat
* Make KM runner execute bpftool tests
* Make the run_tests.bat script also execute bpftool tests
* Make deploy-ebpf.ps1 -t copy all files needed for testing
This PR updates tests.
This PR also updates a doc.
=> Update test scripts

scripts/Convert-BpfToNative.ps1, tests/end_to_end/test_helper.cpp
PR feedback from the previous review.
CI/CD
No.
=> PR feedback from #994

.github/workflows/cicd.yml, .github/workflows/ossar-scan.yml, Directory.Build.props
Use the OSSAR action to verify binaries are built with correct compiler / linker options.
CI/C
No.
=> Integrate OSSAR (Open Source Static Analysis Runner)

.github/codecov.yml, .github/workflows/cicd.yml
Switch fuzzing from running on regular build to running on address sanitizer build.
CI/CD
No.
Resolves: #1034
=> Switch fuzzing to run on sanitizer build

libs/execution_context/ebpf_native.c, scripts/Convert-BpfToNative.ps1, tests/end_to_end/end_to_end.cpp, tests/end_to_end/test_helper.cpp, tests/end_to_end/test_helper.hpp, tests/libs/util/CMakeLists.txt, tests/libs/util/ioctl_helper.cpp, tests/libs/util/ioctl_helper.h, tests/libs/util/test_util.vcxproj, tests/sample/sample.vcxproj, tests/sample/unsafe/invalid_helpers.c, tests/sample/unsafe/invalid_maps1.c, tests/sample/unsafe/invalid_maps2.c, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj
This PR adds negative native module tests:
1. Negative tests for invalid IOCTLs from UM.
2. Negative tests for loading invalid programs.
Also fixes a bug caught by the new tests.
Added new tests.
NA
=> Add negative native module tests

libs/platform/ebpf_epoch.c, libs/platform/ebpf_epoch.h, libs/platform/ebpf_ring_buffer.c, libs/platform/ebpf_ring_buffer.h, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp, tests/libs/util/test_util.vcxproj, tests/libs/util/wer_report.hpp, tests/unit/CMakeLists.txt, tests/unit/test.vcxproj, tests/unit/test.vcxproj.filters, tests/unit/wer_report_test_wrapper.cpp
Add additional test coverage based on codecov data.
New test.
No.
=> Add coverage in bitmap, epoch, and ringbuffer.

libs/api/bpf_syscall.cpp, tests/unit/libbpf_test.cpp
Fixes #1021
Full code coverage for bpf_syscall.cpp
N/A
=> Add more bpf() api tests

docs/vm-setup.md
Fix a simple typo.
No binary impact
This is a doc change
=> Fix documentation typo

tests/end_to_end/test_helper.cpp
This PR adds a minor tweak in `test_helper` as follows:
Currently `ebpf_is_preemptible()` always returns `true` for user mode. This causes a code path to be skipped in native module code when running the unit tests. Changing to flip the value returned by this API whenever a native module is loaded. This is cause this to return TRUE for some native test cases and FALSE for some, ensuring both the code paths are covered in tests.
Existing tests cover this.
NA
=> Test helper tweaks

tests/bpf2c_tests/elf_bpf.cpp, tools/bpf2c/bpf2c.cpp
Add tests for various command-line options for bpf2.c
CI/CD
No.
Resolves: #1050
=> Add tests for bpf2c CLI interface

.github/workflows/reusable-build.yml
Pick up the latest verifier and revert /W4 /WX on external projects.
CI/CD
No
=> Pickup latest ebpf-verifier

netebpfext/net_ebpf_ext_hook_provider.c
This PR fixes a regression caused by PR #1078
NA
NA
=> Fix regression from PR# 1078

netebpfext/net_ebpf_ext_hook_provider.c
NmrProviderDetachClientComplete frees the provider binding context, but _net_ebpf_extension_detach_client_completion uses it after calling NmrProviderDetachClientComplete.
CI/CD. Driver verifier.
No.
Resolves: #1087
=> Save pointer to IO_WORKITEM before completing detach

.github/workflows/cicd.yml, .github/workflows/reusable-cmake-build.yml, CMakeLists.txt, cmake/process_bpf_source_file.cmake, cmake/settings.cmake, libs/api/CMakeLists.txt, libs/service/CMakeLists.txt, rpc_interface/CMakeLists.txt, scripts/CMakeLists.txt, scripts/Convert-BpfToNative.ps1, scripts/setup_build/CMakeLists.txt, tests/CMakeLists.txt, tests/bpf2c_tests/CMakeLists.txt, tests/bpf2c_tests/elf_bpf.cpp, tests/bpftool_tests/CMakeLists.txt, tests/cilium/CMakeLists.txt, tests/fuzz/CMakeLists.txt, tests/sample/CMakeLists.txt, tests/sample/ext/CMakeLists.txt, tests/sample/ext/app/CMakeLists.txt, tests/sample/ext/drv/CMakeLists.txt, tests/sample/sample.vcxproj, tests/sample/unsafe/CMakeLists.txt, tests/socket/CMakeLists.txt, tests/unit/CMakeLists.txt, tools/bpf2c/CMakeLists.txt
Add cmakefiles for remaining projects. Fixes #1052 .
Local build.
None.
=> Add cmakefiles for remaining projects

docs/debugging.md
Fixes #1151
Referenced file moved directories but doc wasn't updated at that time.
N/A
This is a doc update.
=> Fix broken doc link

scripts/create_bpf2c_corpus.bat, tests/libfuzzer/bpf2c/bpf2c_fuzzer.vcxproj
=> Make absolute path

.github/workflows/cicd.yml, Directory.Build.props, ebpfapi/ebpfapi.vcxproj, tools/bpf2c/bpf2c.vcxproj
Add correct libraries for sanitizer build.
CI/CD
No.
=> Add libsancov.lib when building fuzzer

tests/end_to_end/test_helper.cpp
Recently a change was done in `GlueDeviceIoControl` to use the same local copy of buffer for both input and output.
This is somehow causing the async test cases to fail (multiple current open PRs are failing due to this). 
Modifying the original change to not apply for async IOCTLs.
Existing tests cover the changes.
NA
Fixes #1201
=> Revert a IOCTL change done for async operations.

libs/execution_context/ebpf_core.c
Block IOCTLs that aren't supported due to system configuration.
CI/CD
No.
Resolves: #1131
=> Check if the mode is supported prior to permitting an IOCTL

scripts/install-ebpf.bat
This PR fix https://github.com/microsoft/ebpf-for-windows/issues/1217. 
Run "install-bpf.bat" to install runtime services only.
Run "install-bpf.bat /t" to install runtime services and SampleEbpfExt service.
There's no changes for `uninstall-ebpf.bat` because the script will ignore errors if SampleEbpfExt service is not installed.
No.
=> Add /t option for install-ebpf.bat

netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_hook_provider.h, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c
=> Use EX_RUNDOWN_REF for netebpfext rundown.

scripts/config_test_vm.psm1, scripts/run_driver_tests.psm1
Following changes are made to the driver test PS scripts:
- Fix the path to ETW trace output file.
- Set environment variables to generate WER report.
CI.
N/A
=> Fix test automation

include/ebpf_store_helper.h, include/ebpf_windows.h, libs/api_common/store_helper_internal.cpp
This is related to changes for #223 . The changes had a mistake in registry read logic due to which program types with multiple attach types were failing to load.
Manually ran driver tests.
N/A.
=> Fix store read logic.

docs/InstallEbpf.md, docs/ReleaseProcess.md
Update install instructions to allow using released MSI
Fixes #1149 
Manual
This PR contains doc updates.
=> Update install instructions to allow using released MSI

libs/execution_context/ebpf_program.c
Clean up ebpf_program.c
Fixes #339
Existing tests suffice.  No binary impact.
No impact.
=> Clean up ebpf_program.c

include/ebpf_api.h, libs/api/Verifier.cpp, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api_common/windows_platform_common.cpp, tests/end_to_end/helpers.h
Add noexcept keyword to various internal APIs
No changes needed
No changes needed
=> Add noexcept keyword to various internal APIs

.github/workflows/reusable-build.yml, docs/ReleaseProcess.md, scripts/deploy-ebpf.ps1, tools/nuget/ebpf-for-windows.nuspec
Bump version to 0.3.0 so we can issue a new pre-release
CI/CD
No impact
=> Bump version to 0.3.0

libs/api/ebpf_api.cpp, tests/end_to_end/end_to_end.cpp, tests/sample/bad_map_name.c
Fixes #1312
Added new test in this PR
No impact
=> Fix handling of long map names

libs/platform/ebpf_epoch.c
Move the check for preemptible state (aka IRQL) outside of lock (which raises to dispatch in kernel).
Move the code to set the CPU affinity outside of the lock.
Existing tests.
No.
Resolves: #1348
=> Move preemptible check outside of spinlock region

netebpfext/user/netebpfext_user.vcxproj, netebpfext/user/netebpfext_user.vcxproj.filters, netebpfext/user/nmr_impl.cpp, netebpfext/user/nmr_impl.h, netebpfext/user/nmr_um.cpp, tests/netebpfext_unit/netebpfext_unit.cpp
Refactor NMR user mode to be thread-safe.
NetEbpfExt user mode tests.
No.
=> Refactor NMR user mode to be thread safe

libs/execution_context/ebpf_native.c, libs/platform/user/ebpf_platform_user.cpp, netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext_xdp.c, netebpfext/user/fwp_um.cpp, netebpfext/user/fwp_um.h, netebpfext/user/kernel_um.cpp, netebpfext/user/kernel_um.h, netebpfext/user/ndis.h, netebpfext/user/ndis_um.cpp, netebpfext/user/netebpfext_user.vcxproj, netebpfext/user/netebpfext_user.vcxproj.filters, netebpfext/user/nmr_impl.cpp, netebpfext/user/nmr_impl.h, netebpfext/user/nmr_um.cpp, tests/netebpfext_unit/netebpf_ext_helper.h, tests/netebpfext_unit/netebpfext_unit.cpp, tests/xdp/xdp_tests.cpp
This test successfully reproduced in user-mode the bug that #1378 fixes.
(This PR currently includes the PR 1378 changes.)
This adds a test.
No impact.
=> Add a unit test that tests classify_packet in user mode

libs/ebpfnetsh/programs.cpp
Fixes #1295
Replace calls to bpf_object__for_each_safe() with tracking objects in the app as recommended by the deprecation message.
No impact.
=> Clean up the deprecated netsh use of bpf_object__for_each_safe()

CONTRIBUTING.md, docs/InstallEbpf.md, images/install-ebpf-for-windows.ps1, tests/unit/CMakeLists.txt, tools/bpf2c/CMakeLists.txt
Remove trailing whitespace in committed files.
CI/CD
No.
=> Remove trailing whitespace in committed files

ebpfcore/ebpf_drv.c
If submitting an async request fails, release the ref count acquired before submitting it.
CI/CD
No.
Resolves: #1324
=> Fix leak of reference on WDFREQUEST

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml
Create or update an issue if a push or scheduled CI/CD run fails.
CI/CD
No.
=> Create or update issue on workflow failure

docs/SelfHostedRunnerSetup.md, scripts/config_test_vm.psm1, scripts/install_ebpf.psm1
Update eBPF installation script to enable KMDF verifier and pool tag tracking.
No.
No.
=> Enable KMDF tag tracking.

tools/netsh/dllmain.c
=> Add workaround for netsh regression

.github/workflows/reusable-build.yml, scripts/deploy-ebpf.ps1, tools/nuget/ebpf-for-windows.nuspec
Bump version number to do a pre-release
Covered by CI/CD
N/A
=> Bump version to 0.4.0

docs/ReleaseProcess.md, docs/tutorial.md, resource/ebpf_version.h
Bump version to 0.5.0 for a new pre-release
Existing tests
No impact
=> Bump version to 0.5.0

docs/DevelopmentGuide.md
Resolves: #1476 
Remove reference to broken link in Development.md
N/A
N/A
=> Remove reference to broken link

docs/InstallEbpf.md
Added clarification in the documentation.
Step by step execution.
=> Added clarifications to `InstallEpf.md`

.github/workflows/reusable-build.yml
=> Updated deprecated GitHub actions

libs/execution_context/unit/execution_context_unit_test.cpp
Resolves: #1518 
The test was not correctly handling unwinding the async state on failure, which results in an assert when this step fails.
CI/CD
No.
=> Correctly unwind async state on failure

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml, libs/platform/CMakeLists.txt, libs/platform/user/ebpf_low_memory_test.cpp, libs/platform/user/ebpf_low_memory_test.h, libs/platform/user/ebpf_platform_user.cpp, libs/platform/user/platform_user.vcxproj, libs/platform/user/platform_user.vcxproj.filters, scripts/Test-LowMemory.ps1, scripts/setup_build/setup_build.vcxproj, tests/end_to_end/end_to_end.cpp, tests/end_to_end/test_helper.cpp, tests/end_to_end/test_helper.hpp, tests/libs/common/common_tests.vcxproj, tests/libs/common/passed_test_log.h, tests/libs/util/wer_report.hpp, tests/unit/test.vcxproj
Partially resolves: #1481 
Emulate driver verifier low memory systematic simulation for user mode tests.
N/A
No.
=> Emulate driver verifier systematic low memory mode

tests/end_to_end/test_helper.cpp
Resolves: #1657
If ebpf_api_close_handle fails, the duplicate_handles_table_t will deadlock due to failure to release the lock. Switch to std::mutex + std::unique_lock to prevent deadlocks.
CI/CD
No.
=> Switch to std::unique_lock to prevent deadlocks

libs/execution_context/ebpf_native.c
Closes #1586.
This PR addresses unifying eBPF native module's multiple bool state flags, in order to provide more clarity.
=> Implement native module states

.github/workflows/autoupdate.yaml
Try enabling auto-updating of PR's marked for auto-merge when the main branch is updated.
Fixes #1562
Manual.
No impact.
=> Auto-update PR's that have auto-merge set

tests/fuzz/execution_context.cpp
Closes #1709 
This PR's changes:
- Localized memory limitation within the fuzz loop Vs whole process.
- Added container size checks, which caused ASAN to output "*AddressSanitizer failed to allocate 0x10000 (65536) bytes of memory at address 0xXXXXXXXX (error code: 1455)"*.
CI/CD pipeline.
None.
=> Fix container size-check issue. Rescoped memory limitation.

external/Analyze.external.ruleset, include/elfio_wrapper.hpp, libs/api/Verifier.cpp, libs/api/crab_verifier_wrapper.hpp, libs/api_common/ebpf_verifier_wrapper.hpp, tests/bpf2c_tests/expected/map_dll.c, tests/bpf2c_tests/expected/map_raw.c, tests/bpf2c_tests/expected/map_sys.c, tests/sample/map.c, tools/bpf2c/bpf_code_generator.cpp
Pull in the latest versions of ebpf-verifier, elfio, and dependent submodules.
CI/CD
No.
=> Update ebpf-verifier to latest

.github/workflows/nuget_update.yaml
Automatically create PRs to update nuget packages to latest.
CI/CD
No.
=> Automatically update nuget packages

libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_native.c, libs/platform/ebpf_async.c, libs/platform/ebpf_epoch.c, libs/platform/ebpf_hash_table.c, libs/platform/ebpf_pinning_table.c, libs/platform/ebpf_platform.h, libs/platform/ebpf_state.c, libs/platform/unit/platform_unit_test.cpp, tests/performance/ExecutionContext.cpp, tests/performance/platform.cpp
Merge the storage for LRU data with value data stored in hash table.
CI/CD
No.
Resolves: #557
=> LRU improvement's part 1

tests/sample/sample.vcxproj, tools/bpf2c/Convert-BpfToNative.ps1.template
Build sample drivers and user mode components in parallel. 
Move each bpf2c build to its own folder.
CI/CD
No.
=> Speed up build of sample folder

libs/execution_context/ebpf_maps.c, libs/platform/ebpf_hash_table.c, tests/performance/ExecutionContext.cpp
Implement multi-generational LRU.
CI/CD
No.
Resolves: #1721
=> Implement multi-generational LRU

libs/api_common/store_helper_internal.cpp, libs/api_common/windows_platform_common.cpp, libs/ebpfnetsh/elf.cpp, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_platform_user.cpp, libs/platform/user/kernel_um.cpp, libs/platform/user/platform_user.vcxproj.filters, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, tests/end_to_end/test_helper.cpp
First round of memory leak fixes in ebpfapi and unit_tests.
CI/CD
No.
=> First round of memory leak fixes in ebpfapi

include/linux/bpf.h, libs/api/bpf_syscall.cpp, libs/execution_context/ebpf_program.c, tests/unit/libbpf_test.cpp
#1825 got merged before all feedback was addressed. This PR addresses that feedback.
Resolves: #1839
CI/CD
No.
=> PR feedback from https://github.com/microsoft/ebpf-for-windows/pull/1825

.github/workflows/reusable-build.yml, .github/workflows/reusable-cmake-build.yml
Resolves: #1837
Remove dependency on dawidd6/action-download-artifact action.
CI/Cd
No.
=> Remove dawidd6/action-download-artifact

CONTRIBUTING.md, docs/AutomatedTests.md
Add overview of types of tests that exist today.
N/A
This is a doc change.
=> Add doc about automated tests

installer/Product.wxs, tools/export_program_info/main.cpp
Fixes issue with eBPF store clear/setup and add logs to `export_program_info.exe` for troubleshooting.
Manual
No change.
=> Fix eBPF store clear/setup and add logs to `export_program_info.exe`

docs/EpochBasedMemoryManagement.md
Resolves: #1552
Document epoch-based memory management.
Doc only change.
Doc only change.
=> Document epoch based memory management

libs/api/ebpf_api.cpp
Resolves: #1996
ParsePEFromFile can throw std::bad_alloc. Catch and handle the exception in _ebpf_enumerate_native_sections.
CI/CD + low memory testing.
No.
=> Catch std::bad_alloc from ParsePEFromFile

docs/GettingStarted.md
Fix bullet formatting on `GettingStarted.md`.
=> Fix bullet formatting in docs.

scripts/generate_expected_bpf2c_output.ps1, tests/bpf2c_tests/elf_bpf.cpp, tests/bpf2c_tests/expected/bpf_dll.c, tests/bpf2c_tests/expected/bpf_raw.c, tests/bpf2c_tests/expected/droppacket_unsafe_dll.c, tests/bpf2c_tests/expected/droppacket_unsafe_raw.c, tests/bpf2c_tests/expected/droppacket_unsafe_sys.c, tests/bpf2c_tests/expected/invalid_helpers_dll.c, tests/bpf2c_tests/expected/invalid_helpers_raw.c, tests/bpf2c_tests/expected/invalid_helpers_sys.c, tests/bpf2c_tests/expected/invalid_maps1_dll.c, tests/bpf2c_tests/expected/invalid_maps1_raw.c, tests/bpf2c_tests/expected/invalid_maps1_sys.c, tests/bpf2c_tests/expected/invalid_maps2_dll.c, tests/bpf2c_tests/expected/invalid_maps2_raw.c, tests/bpf2c_tests/expected/invalid_maps2_sys.c, tests/bpf2c_tests/expected/invalid_maps3_dll.c, tests/bpf2c_tests/expected/invalid_maps3_raw.c, tests/bpf2c_tests/expected/invalid_maps3_sys.c, tests/bpf2c_tests/expected/printk_unsafe_dll.c, tests/bpf2c_tests/expected/printk_unsafe_raw.c, tests/bpf2c_tests/expected/printk_unsafe_sys.c
Resolves: #2026
Update scripts to generate custom and unsafe program expected output.
CI/CD
No.
=> Update scripts\generate_expected_bpf2c_output.ps1 to generate custom and unsafe programs.

installer/Product.wxs
Closes #2065 
Add missing `libbpf` includes, included a few `.o` programs, uniformed source formatting.
MSI installation.
n.a.
=> Add missing libbpf includes.

libs/execution_context/ebpf_link.c, tests/end_to_end/helpers.h
Implement feedback from PR #2062 that was not addressed before the PR was merged.
CI/CD
No.
=> Feedback from PR #2062

.github/workflows/cicd.yml, .github/workflows/scorecards-analysis.yml
Required to address issue #2076
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Testing using CI/CD since this only changes CI/CD config.
No impact.
=> Add merge_queue support in CI/CD

scripts/vm_run_tests.psm1
This PR ensures that the ```scripts\vm_run_tests.psm1``` script checks for the presence of the 'Standard User' user account on the first vm and if found, deletes it prior to (re)creating it (on the first vm).
1.  Manually create the 'Standard User' user account on the first vm and ensure that the ```scripts\vm_run_tests.psm1``` script does not prematurely terminate with the '... user exists' error for this user account and instead is able to detect its presence and delete it prior to its re-creation.
No documentation changes required.
Fixes #2112
=> Connect-Redirect test setup - Delete standard user account before its recreation.

.github/workflows/cicd.yml, libs/api/Verifier.cpp, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/unit/platform_unit_test.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h
This PR:
1. enables "leak_detection" for `fault_injection` test case for `unit_tests.exe`
2. Fixes test bugs to allow leak_detection to work.
3. Fixes leaks found in product code.
This PR adds leak_detection test.
NA
=> Enable leak_detection for "fault_injection" test case.

tests/unit/libbpf_test.cpp
Switch to using bpf_link_ptr to ensure that the bpf_link object is always deleted.
This fixes one of the issues causing #2180 
CI/CD + fault injection.
No.
=> Fix leak of bpf_link objects on fault injection

libs/execution_context/ebpf_program.c
Ensure valid ref-count prior to accessing extension provider's data.  Not doing so was causing ```ebpfcore.sys``` to crash under multi-threaded stress tests.
Ran the multi-threaded stress test with the following arguments (runs for a minimum of 30 minutes):
```ebpf_stress_tests_km -jtt=32 -jtd=1800 -jer=true -jerd=250 load_attach_detach_unload_random_v4_test```
_Note: This is a new test application currently in a Draft PR (https://github.com/microsoft/ebpf-for-windows/pull/2240)_
No documentation changes required.
Fixes #2254
=> Ensure refcounts for extension provider data access

.github/workflows/cicd.yml, libs/ebpfnetsh/programs.cpp, tests/end_to_end/end_to_end.cpp, tests/end_to_end/test_helper.cpp
Fixes part of #2180
This PR fixes some of the memory leaks discovered by `fault_injection_full` test case.
Existing tests
NA
=> Fix memory leaks

scripts/deploy-ebpf.ps1.in
Added port_leak.exe and port_leak.pdb in deploy-ebpf.ps1 script.
=> Add port_leak.exe and port_leak.pdb in deploy-ebpf.ps1 script

libs/ebpfnetsh/programs.cpp, libs/ebpfnetsh/tokens.h, tests/end_to_end/netsh_test.cpp, tools/netsh/ebpfnetsh.rc
Add compartment parameter to "netsh ebpf add program"
Fixes #2185
Added new test.
Updated netsh help output.
=> Add compartment support to netsh ebpf add program

docs/NativeCodeGeneration.md
Updated the doc with 
1. the new fields added in the program_entry_t
2. the usage of the hash upon reattachment of the program.
_Do any existing tests cover this change? No
_Is there any documentation impact for this change? 
This PR addresses the update for the field introduced in #2252. 
Overall read the document from a new user perspective.
=> NativeCodeGeneration.md: Doc update with hash information

docs/ReleaseProcess.md
This PR updates the release process steps.
Release 0.8.0
`ReleaseProcess.md`
=> Update release steps.

.github/workflows/reusable-test.yml, scripts/Test-FaultInjection.ps1
Add verbose logging for fault injection to log every test case.
CI/CD
No.
=> Verbose logging for fault injection

cmake/process_bpf_source_file.cmake, docs/NativeCodeGeneration.md, scripts/build_custom_sample_programs.ps1, tests/sample/sample.vcxproj, tools/bpf2c/Convert-BpfToNative.ps1.template, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj
Provide option to Convert-BpfToNative.ps1 to pass resource file for use when generating .sys file.
CI/CD
Added documentation to the script.
=> Provide option to version info in generated .sys file

tests/connect_redirect/connect_redirect_tests.cpp, tests/end_to_end/end_to_end.cpp, tests/libs/common/common_tests.h, tests/socket/socket_tests.cpp
This reverts commit 6c025904b34e3a02315eca150910e7ab2491631a.  (PR #2226)
Existing CICD
NA
=> Revert PR #2226

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_native.c, libs/execution_context/ebpf_program.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/platform/ebpf_handle.h, libs/platform/ebpf_object.c, libs/platform/ebpf_object.h, libs/platform/ebpf_pinning_table.c, libs/platform/kernel/ebpf_handle_kernel.c, libs/platform/unit/platform_unit_test.cpp, libs/platform/user/ebpf_handle_user.c, tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp, tests/performance/ExecutionContext.cpp
Add instrumentation to track down use after free bugs.
CI/CD
See ebpf_object.h
=> Add object history tracking instrumentation

tests/bpf2c_tests/expected/map_dll.c, tests/bpf2c_tests/expected/map_raw.c, tests/bpf2c_tests/expected/map_sys.c, tests/sample/map.c
Fixes #1715
Remove workaround now that verifier is fixed.
No impact.
=> Revert bpf_printk thunk

libs/execution_context/ebpf_program.c
Fixes #2474
`program->links` in ebpfcore should always be accessed within a lock. There is one place where this list is accessed without lock, and that can cause use after free due to race conditions.
Fix is to always access `program->links` under lock.
Exising tests and stress tests.
NA
=> Access "program->links" under lock

Directory.Build.props, libs/platform/user/platform_user.vcxproj, tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj
Fix build errors with Visual Studio 17.6.0
Install Visual Studio 17.6.0
Build
No impact
=> Fix build errors with Visual Studio 17.6.0

libs/execution_context/ebpf_native.c
This change-set is primarily the result of a code analysis of `ebpfcore` to ensure that all code paths that touch epoch managed objects are protected by the `epoch_enter /  epoch_exit` sandwich.  Almost all code path were found to be epoch aware, barring one instance where it was explicitly avoided (due to OS callbacks into epoch aware `ebpfcore` entry points) and another where it was not really required.
This PR adds comments for the former and adds the sandwich (with comments) for the latter.
Successful (debug and release) passes of:
- `.api_test.exe` (With the regression tests commented out given their known failures on local setups)
- `.\ebpf_stress_tests_km -tt=32 -td=2 -er=true -erd=250` (All tests pass)
Fixes #2228
=> Add epoch sandwich and related comments.

tests/stress/km/stress_tests_km.cpp
This PR fixes the root cause where a race between two competing creator threads could end up calling `bpf_object__load()` on the same 'opened' program object due the highly parallelized nature of the 'open' and 'load' program operations.  This leads to a situation where the second call to `bpf_object__load()` (called by the losing creator thread) returns an error on detecting that the program object is already loaded. This causes the test to fail as well (a false positive). 
The fix ensures that the 'winning' creator thread now sets a (lock protected) flag after a successful `bpf_object__load()` call which is then checked by subsequent creator threads prior to calling `bpf_object__load()` for the same 'opened' program object.
Ensure a 60-minute successful test run:
- …
=> Fix double-load issue

.github/workflows/reusable-test.yml, scripts/Run-Test.ps1, scripts/setup_build/setup_build.vcxproj, scripts/setup_build/setup_build.vcxproj.filters
Gather a crash dump if the test ends and the exe is still running.
CI/CD
No.
=> Add step to gather dumps for any process launched from working folder.

.github/workflows/cicd.yml
change schedule time for CICD daily run. This will be running at 1 AM PST every day 
N/A
N/A
=> change schedule times

docs/TroubleshootingGuide.md
Updated the TSG doc as per the Traces in the latest binaries, after the fix of
https://github.com/microsoft/ebpf-for-windows/pull/2434/files
https://github.com/microsoft/ebpf-for-windows/pull/2628/files
_Do any existing tests cover this change? N/A
=> Updated TSG doc with latest traces

.github/pull_request_template.md
Update the github PR template to ask if any installer files are affected by a change.
This serves as a reminder to not forget updating installer files.
No impact.
No impact.
=> Add installer section to PR template

.github/workflows/reusable-build.yml, scripts/Fetch-LatestArtifacts.ps1, scripts/deploy-ebpf.ps1.in
Download the latest bpf_perfromance artifacts and include them in the build artifacts.
CI/Cd
No.
No.
=> Download latest successful bpf_performance build

libs/execution_context/ebpf_program.c
The function _ebpf_program_test_run_work_item was calling ebpf_should_yield_processor on each invocation instead of on each batch, significantly skewing the measurement of the BPF programs.
CI/CD
No.
No.
Note:
This reduces the baseline cost of a BPF call via BPF_PROG_TEST_RUN from 52ns -> 35ns, but has no impact on non-test workloads.
=> Only call ebpf_should_yield_processor every batch_size invocations

netebpfext/net_ebpf_ext.c, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_hook_provider.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, netebpfext/sys/net_ebpf_ext_drv.c
This PR adds additional traces where required and some related code clean-up.
CI/CD
No installation impact.
Fixes: #2719
=> Add missing traces in NetEbpfExt

libs/execution_context/ebpf_program.c
Switching from modulus to == 0 reduces the overhead b6 6ns.
CI/CD
No.
No.
=> Remove expensive div rax,r14

scripts/Fetch-LatestArtifacts.ps1
Resolves: #2810
If the repo that artifacts are being pulled from has multiple scheduled workflows, this script can pick the wrong workflow and fail to download the artifacts. The fix is to locally filter the returned list of workflow runs and match on name.
CI/CD
No.
No.
=> Workaround issue in GitHub actions REST API

.github/workflows/cicd.yml, .github/workflows/reusable-build.yml, docs/AutomatedTests.md, ebpfcore/ebpf_drv.c, scripts/config_test_vm.psm1, scripts/execute_ebpf_cicd_tests.ps1, scripts/run_driver_tests.psm1, scripts/vm_run_tests.psm1
Partially addresses: https://github.com/microsoft/ebpf-for-windows/issues/1915
Refactor execute_ebpf_cicd_tests to accept test suite name.
Add "Stress" as test suite.
Run bpf_performance_runner with options.
CI/CD
No.
No.
=> Bpf performance run

libs/runtime/unit/platform_unit_test.cpp
Add tests to verify that the ebpf_random_uint32 produces numbers that are sufficiently random.
No.
No.
No.
=> Check for dominant frequency in random number generators

docs/ReleaseProcess.md
Updated the list of files to be released.
v0.11.0 release process.
`ReleaseProcess.md`
n.a.
=> Update Release documentation.

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml, .github/workflows/upload-perf-results.yml
Azure login failed:
```
Using OIDC authentication...
Error:  Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable. Please make sure to give write permissions to id-token in the workflow.
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Error: : AADSTS50027: JWT token is invalid or malformed.
Trace ID: 84c7cc76-fbfe-47cb-8f3f-e6e12a061300
Correlation ID: 49856b98-e850-43e0-b9[11](https://github.com/microsoft/ebpf-for-windows/actions/runs/6232847098/job/16918197871#step:5:12)-888769705abc
```
Adding the required permission.
CI/CD - Scheduled run (post merge).
No.
No.
=> Add required permission to log into Azure

README.md
Add performance badge to README file
Fixes #2933
Viewed result on github
This is a doc change.
No impact.
Resolves: #2840
=> Add performance badge to README file

.github/CODEOWNERS, docs/Governance.md
Document project roles and responsibilities
Fixes #2934
No impact
No impact.
=> Document roles and responsibilities

libs/execution_context/ebpf_maps.c
Resolves:
https://github.com/microsoft/ebpf-for-windows/issues/2818
Map-in-map and program-in-map have an unnecessary spin-lock around finding entries in the map. The spin-lock was needed under a previous map paradigm, but is no longer needed after switching to weak-references in the object table as it permits try/acquire semantics on ref-counts.
CI/CD
No.
No.
Before:
```
C:\perf>Release\bpf_performance_runner.exe -i tests.yml -e .sys -t "bpf_tail_call"
Timestamp,Test,Average Duration (ns),CPU 0 Duration (ns),CPU 1 Duration (ns),CPU 2 Duration (ns),CPU 3 Duration (ns),CPU 4 Duration (ns),CPU 5 Duration (ns)
2023-10-02T23:43:08-0800,bpf_tail_call,12097,11998,12032,12110,12131,12125,12189
```
After:
```
C:\perf>Release\bpf_performance_runner.exe -i tests.yml -e .sys -t "bpf_tail_call" …
```
=> Remove spurious locks in object map path

libs/runtime/ebpf_epoch.c
This PR adds a missing null pointer check.
CI/CD
Issue exposed by existing test,  new test not needed.
Fixes #2947
=> Check for valid work queue ptr prior to usage

libs/api/Verifier.cpp, libs/api/ebpf_api.cpp
This PR adds some minor traces in ebpfapi.
CICD
No
No.
=> Add tracing in ebpfapi

libs/runtime/unit/platform_unit_test.cpp
Resolves: #3006 
During fault injection, the test code fails to release the ref-count, causing the object tracking into an unbounded wait while waiting for all objects to be released.
CI/CD
No.
No.
=> Fix failure during fault injection

.github/workflows/reusable-build.yml
Pickup latest release of bpf_performance to measure map of map and additional helpers.
CI/CD
No.
No.
=> Switch to bpf_performance v0.0.4

docs/GettingStarted.md, tests/api_test/api_test.cpp
Addresses #2758.
No new tests needed.
This is a documentation change.
No changes required for installation.
=> Fix api_test documentation.

.github/workflows/reusable-build.yml
Pull artifacts from the v0.0.6 release of microsoft/bpf_performance 
CI/CD
No.
No.
=> Bump bpf_performance to v0.0.6

docs/isa-support.rst
Doc updates since bpf_conformance submodule has now been updated to the latest bpf_conformance build.
No impact.
No impact.
=> Update isa-support per latest bpf_conformance updates

ebpfapi/Source.def, libs/api/api_internal.h, libs/api/ebpf_api.cpp, libs/api/libbpf_map.cpp, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/ebpf_protocol.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/runtime/ebpf_object.c, tests/unit/libbpf_test.cpp
Resolves: #2080
Implement the following libbpf APIs:
bpf_map_delete_batch
bpf_map_lookup_and_delete_batch
bpf_map_lookup_batch
bpf_map_update_batch
CI/CD + new tests.
No.
No.
=> Add support for bpf_map_*_batch APIs

.github/workflows/cicd.yml, .github/workflows/reusable-build.yml
Permit calling .github/workflows/reusable-build.yml from other repos.
CI/CD
No.
No.
=> Enable build cross repo

tests/api_test/api_test.cpp
Fixes #3254
**Issue:**
This is a race condition with the preceding test (`close_unload_test()`). This is a 100% repro when only these 2 tests are locally run on a Release build.
The reason for failure of regression test is that the test calls `bpf_object__close()` at the end, and then validates that no entry exists in the ID table. This all works fine, but the test preceding the regression test (`close_unload_test()`) deliberately skips cleaning up the prog array map, expecting the cleanup to happen automatically (and any failure to do so is expected to be caught when the tests end and driver is stopped).
Since the prog array map is not explicitly cleaned from user mode, the cleanup happens in a worker thread in ebpfcore, hence the last reference on the ID entries of program objects is …
=> Fix flaky API regression test.

docs/GettingStarted.md, installer/ebpf-for-windows.wixproj, installer/packages.config
Fixes #3299 
Fixes [CVE-2024-24810](https://nvd.nist.gov/vuln/detail/CVE-2024-24810#:~:text=WiX%20toolset%20lets%20developers%20create,with%20the%20WiX%20installer%20framework), discovered on 02/06/2024, as per https://wixtoolset.org/news/2024/02/06/wix-v4.0.4-available/.
CI/CD - Local
`GettingStarted.md`
Update Wix Toolset to v3.14.0.
=> Fix CVE-2024-24810

.github/workflows/cicd-release-validation.yml, .github/workflows/perf.yml, .github/workflows/upload-perf-results.yml
Resolves: #3297 
Pin azure/login action by commit id
CI/CD
No.
No.
=> Pin Azure Login action by commit id

docs/Governance.md
Introducing special labels to prioritize issues.
N/A.
This is a documentation only change.
N/A.
=> issue priorities.

docs/Governance.md, docs/ReleaseProcess.md
Update the release process to clarify certain ambiguities around release and servicing process, including version updates and tag creation. This update nullifies the issue #3302.
N/A.
This is a documentation only change.
N/A.
=> Update the release process.

docs/GettingStarted.md, installer/ebpf-for-windows.wixproj, installer/packages.config
Fixes #3405
Fixes [CVE 2024 29188](https://nvd.nist.gov/vuln/detail/CVE-2024-29188), discovered on 03/24/2024.
CI/CD - Local
`GettingStarted.md`
Update Wix Toolset to v3.14.1.
=> Fix CVE 2024 29188

docs/InstallEbpf.md, scripts/config_test_vm.psm1, scripts/deploy-ebpf.ps1.in, scripts/setup-ebpf.ps1
Closes #2422
This PR updates the manual installation process described in `InstallEbpf.md`, by introducing all the artifact updates since the last change and by leveraging the MSI to install eBPF for windows.
Additionally, it updates the VC++ Redist downloaded version in `scripts/config_test_vm.psm1` to v17.
Local and Local VM
`InstallEbpf.md`
Yes, manual installation option.
=> Update manual deploy process.

.github/workflows/cicd-release-validation.yml, docs/GettingStarted.md, installer/ebpf-for-windows.wixproj, installer/packages.config, scripts/install_ebpf.psm1
Includes:
PR #3393 (Release validation CICD fix)
PR #3400 (Release validation CICD fix)
PR #3406 (Security fix)
CICD
n/a
n/a
=> Release 0.15.0 fixes

libs/api_common/windows_platform_common.cpp
Fixes #3409 .
Fault injection test.
No.
No.
=> fix mem leak.

docs/eBpfExtensions.md, include/ebpf_structs.h, include/ebpf_windows.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/runtime/unit/platform_unit_test.cpp, libs/shared/ebpf_shared_framework.h, libs/shared/shared_common.c, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, undocked/tests/sample/ext/drv/sample_ext.c, undocked/tests/sample/ext/inc/sample_ext_program_info.h
This fixes #3420.
This PR addresses few of the missing cases in #3326 .
CI.
Made one change.
No changes.
=> Few fixes to the extension header changes.

docs/eBpfExtensions.md, include/ebpf_structs.h, include/ebpf_windows.h, libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_link.c, libs/execution_context/unit/execution_context_unit_test.cpp, libs/runtime/unit/platform_unit_test.cpp, libs/shared/ebpf_shared_framework.h, libs/shared/shared_common.c, netebpfext/net_ebpf_ext_bind.c, netebpfext/net_ebpf_ext_sock_addr.c, netebpfext/net_ebpf_ext_sock_ops.c, netebpfext/net_ebpf_ext_xdp.c, tests/end_to_end/end_to_end.cpp, tests/end_to_end/helpers.h, undocked/tests/sample/ext/drv/sample_ext.c, undocked/tests/sample/ext/inc/sample_ext_program_info.h
=> Cherry pick PR #3422

.github/workflows/cicd.yml, .github/workflows/reusable-test.yml
There was a bug in the previous PR. The allocator_may_return_null=1 option is a AddressSanitizer option and not an libfuzzer option. Switch to pass the setting to AddressSanitizer instead of libfuzzer.
CI/CD
No.
No.
=> Set allocator_may_return_null=1 as an environment variable

libs/execution_context/ebpf_link.c, libs/execution_context/ebpf_program.c, libs/shared/shared_common.c
- Revert overly strict check in link attach to provider (#3495)
- Fixes for memory leaks and crashes (#3485)
=> Cherry pick PR #3495 and #3485.

docs/isa-support.rst
Fix formatting issues in isa-support.rst that can be seen at https://github.com/microsoft/ebpf-for-windows/blob/main/docs/isa-support.rst
The corrected version can be seen at https://github.com/dthaler/ebpf-for-windows/blob/isa-support/docs/isa-support.rst
* Fix display of link at top of file
* Fix display of three columns
* Remove obsolete sentence about atomics from the bottom of the file
No impact
This is a doc-only change
No impact
=> Fix formatting issues in isa-support.rst

docs/Governance.md
Proposes changes to issue prioritization policy.
N/A.
Yes.
N/A.
=> proposed changes to issue prioritization.

libs/execution_context/ebpf_program.c, libs/service/api_service.cpp, libs/ubpf/kernel/ubpf_kernel.c, libs/ubpf/user/ubpf_user.c
Pickup the newest version of uBPF and fix breaking changes.
CI/CD
No.
No.,
=> Pickup latest ubpf and fix breaking contract changes

libs/execution_context/ebpf_program.c
This pull request includes a change to the `_ebpf_program_type_specific_program_information_detach_provider(void* client_bin` function in the `libs/execution_context/ebpf_program.c` file. The change adds a conditional statement to prevent a potential deadlock situation. This is achieved by checking if the program is visible to any other threads before waiting for any threads executing in the current epoch to complete. The deadlock could occur when the detach callback is called inside an epoch, which is now prevented by this added check.
CI/CD
No.
No.
=> Add workaround for NmrRegisterClient calling detach

libs/execution_context/ebpf_core.c, libs/execution_context/ebpf_maps.c, libs/execution_context/ebpf_maps.h, libs/execution_context/unit/execution_context_unit_test.cpp, libs/runtime/ebpf_ring_buffer.h, tests/stress/km/stress_tests_km.cpp
Just fixing typos caught along the way.
=> chore: rename epbf to ebpf typo

installer/Product.wxs, installer/ebpf-for-windows.wixproj, scripts/check_msi_installation_files_nativeonly_release.txt, tests/end_to_end/netsh_test.cpp
Cherry pick #3623.
* skip test
* fix test
* update tests to accept both old and new values
* include vc redist in MSI
=> Multiple MSVC related fixes (#3623)

libs/execution_context/ebpf_native.c, tests/bpf2c_tests/expected/atomic_instruction_others_dll.c, tests/bpf2c_tests/expected/atomic_instruction_others_raw.c, tests/bpf2c_tests/expected/atomic_instruction_others_sys.c, tools/bpf2c/bpf_code_generator.cpp
Resolves: #3655
Pick up the latest ebpf-verifier version and fix a bug exposed by the updated bpf_conformance tests.
CI/CD
No.
No.
=> Fix bpf conformance failure

.github/workflows/release-scheduler.yml
Update version to latest
Change policy from audit to block per harden-runner recommendation
No impact.
No impact.
=> Update harden-runner for release scheduler

libs/runtime/ebpf_hash_table.c
This pull request includes significant changes to the `libs/runtime/ebpf_hash_table.c` file, primarily focusing on improving the way keys are compared in the hash table. The changes involve the introduction of new comparison methods for different types of keys and a wrapper function to select the best comparison method based on the key size and extract function.
Key comparison improvements:
* [`_ebpf_hash_table_compare_integer_keys`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b256c40db9abc47c2aL158-R227): A new function that compares keys assuming they are integers. It handles different key sizes and returns a comparison result based on the values of the keys.
* [`_ebpf_hash_table_compare_extracted_keys`](diffhunk://#diff-6c24a75cf729f18fc4eb4459a9eb23a3561b8192157748b2 …
=> Special case integer key sizes

docs/GettingStarted.md, docs/InstallEbpf.md, docs/tutorial.md
This PR contains documentation updates related to xdp_test program type. 
It also adds pointers to xdp-for-windows external extension to use for XDP.
_Do any existing tests cover this change? N/A Are new tests needed? N/A
_Is there any documentation impact for this change? Yes
_Is there any installer impact for this change? No
=> Documentation update with xdp_test

scripts/Setup-DevEnv.ps1
Fix a missing " which breaks executing the setup script. cc @Alan-Jowett.
It'd be nice to lint for this somehow, but I don't know how.
=> Fix Setup-DevEnv.ps1

.azure/OneBranch.PullRequest.yml, .azure/reusable-build.yml, .azure/reusable-test.yml, .onefuzz/OneFuzzConfig.json, scripts/onebranch/onefuzz-prep.ps1
Upstream the ADO pipeline for building the internal branch of eBPF for Windows.
Internal CI/CD
No.
No.
=> Add ADO pipelines

scripts/onebranch/post-build.ps1, tools/onebranch/onebranch.vcxproj
Update onebranch scripts.
CI.
N/A.
N/A.
=> update onebranch scripts.

.github/workflows/reusable-test.yml
This pull request includes a small change to the `.github/workflows/reusable-test.yml` file. The change adds a new step to print CPU information.
* [`.github/workflows/reusable-test.yml`](diffhunk://#diff-e386584fe70c301924ab6a8d4656b54ef92ed1961e6eb6f77c155be3475615f6R92-R96): Added a step to print CPU information using PowerShell.
CI/CD
No.
No.
=> Add step to log CPU info

.azure/OneBranch.PullRequest.yml, docs/ReleaseProcess.md
Remove spurious end of line white space.
N/A - Doc only change
N/A
N/A
=> Cleanup spurious white-space

libs/runtime/ebpf_epoch.c, libs/runtime/ebpf_epoch.h, libs/runtime/ebpf_work_queue.c, libs/runtime/ebpf_work_queue.h
Revert epoch code to last known good state. This reverts:
https://github.com/microsoft/ebpf-for-windows/pull/3771
https://github.com/microsoft/ebpf-for-windows/pull/3850
https://github.com/microsoft/ebpf-for-windows/pull/3854
CI/CD
No.
No.
=> Revert CPU activation code until issues are resolved

scripts/setup-ebpf.ps1
Work around a permissions problem where the debug runtime DLLs in System32 are not accessible to the ebpfsvc.exe service running as Local Service.
Updates #3872
=> scripts: copy VC runtime debug DLLs into installation folder

.github/workflows/release-scheduler.yml
PR updates `release-scheduler` template with checkbox for SPGO data
NA
No
No
=> Update `release-scheduler` template with checkbox for SPGO data

libs/runtime/ebpf_ring_buffer.c
This pull request includes an optimization to the `ebpf_ring_buffer_output` function in the `libs/runtime/ebpf_ring_buffer.c` file. The change aims to improve performance by checking the available space in the ring buffer before acquiring a lock.
Optimization to ring buffer output:
* [`libs/runtime/ebpf_ring_buffer.c`](diffhunk://#diff-bf6e569a8d57eb9f398cbd998dfea55358d269dc4128cc699ba3587e0064e441R138-R145): Added a check to determine if there is enough space in the ring buffer before acquiring the lock, which helps avoid unnecessary locking and improves performance when the consumer is not consuming fast enough.
CI/CD
No.
No.
=> Speedup case where ringbuf is full

.azure/OneBranch.PullRequest.yml, .azure/reusable-build.yml, .azure/reusable-test.yml
Update ADO scripts to build ARM64 native only.
ADO CI/CD
No.
No.
=> Build native-only arm64

tests/end_to_end/helpers.h, tests/end_to_end/test_helper.cpp, tests/unit/libbpf_test.cpp
Resolves: #4096
Fix test bug where link type was not set.
CI/CD
No.
No.
=> Update _single_instance_hook to set link type

tests/socket/socket_tests.cpp
Resolves: #4196
Catch2 doesn't permit calling require from any thread except for the main thread. To work around this, introduced "SAFE_REQUIRE" that calls REQUIRE if on the main thread or throws an exception.
CI/CD
No.
No.
=> Don't call require from non-main thread

.azure/OneBranch.PullRequest.yml, .azure/reusable-build.yml, Directory.Build.props, tests/sample/sample.vcxproj
Fix build issue in Azure pipeline.
Pull from the internal nuget feed.
Select the correct version of Clang + headers.
Azure pipeline builds
No.
No.
=> Switch to nuget feed for llvm

libs/execution_context/ebpf_native.c
Resolves: #4243
Version check was comparing wrong fields. Check correct version fields.
CI/CD
No.
No.
=> Fix version check

docs/eBpfExtensions.md, include/ebpf_structs.h, tests/unit/libbpf_test.cpp
Added BPF_PROG_TYPE and BPF_ATTACH_TYPE values for ntos and netevent extensions
NA
Added some info in eBpfExtensions.md.
NA
=> Added enum values for extensions

.github/workflows/reusable-build.yml
Update `bpf_performance` version to 0.13.0
Existing CICD
No
No
=> update bpf_performance version

README.md, docs/SelfHostedRunnerSetup.md, docs/vm-setup.md
This fixes #2888 by updating the self-hosted runner documentation, by referencing to the current scripts to configure a runner for CICD kernel tests with a nested tested VM.
N/A.
This is a documentation change.
N/A.
=> doc update.

libs/api/ebpf_api.cpp, scripts/run_driver_tests.psm1, tests/api_test/api_test.cpp, tests/end_to_end/helpers.h
This PR cherry-picks the following PRs from main.
#4347 
#4348 
#4350 
Test and automation were modified.
N/A.
N/A.
=> Cherry pick from main

.azure/OneBranch.PullRequest.yml, .azure/reusable-build.yml, .azure/reusable-test.yml, .github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/codecov.yml, .github/dependabot.yml, .github/workflows/check_wdk.yml, .github/workflows/cicd-release-validation.yml, .github/workflows/cicd.yml, .github/workflows/dependency-review.yml, .github/workflows/netperf.yml, .github/workflows/nuget_update.yaml, .github/workflows/ossar-scan.yml, .github/workflows/perf.yml, .github/workflows/release-scheduler.yml, .github/workflows/reusable-build.yml, .github/workflows/reusable-test.yml, .github/workflows/scorecards-analysis.yml, .github/workflows/update-docs.yml, .github/workflows/upload-perf-results.yml, .github/workflows/validate-yaml.yml, .pre-commit-config.yaml, .yamllint.yml, manifests/Kubernetes/ebpf-for-windows-daemonset.yaml
* Add validate-yaml workflow and .yamllint file that configures it
* Fix all errors and warnings reported by the workflow
* Incorporate changes from PR #4359
Fixes #4358
CI/CD
No impact.
No impact.
=> Add CI/CD workflow to validate YAML files

.github/workflows/cicd-release-validation.yml
More fixes for cicd release YML tracked by #4358.
CI/CD.
nNA.
N/A.
=> fixing configuration for driver_native_only_tests.

ebpfcore/EbpfCore.vcxproj, libs/execution_context/ebpf_native.c
Resolves: #4373
Capture the path of the module during NMR attach for improved debugging.
CI/CD
No.
No.
=> Capture native image name during attach

scripts/setup_build/packages.config, tools/bpf2c/templates/kernel_mode_bpf2c.vcxproj, tools/bpf2c/templates/user_mode_bpf2c.vcxproj, wdk.props
Resolves: #4296
Pickup the latest WDK
CI/CD
No.
No.
=> Update WDK from 10.0.26100.2454 to 10.0.26100.3323

.github/workflows/reusable-build.yml, scripts/validate_redist_nuget_architecture.ps1, tools/redist-package/ebpf-for-windows-redist.nuspec.in
This is a manual CP of PR #4382 to `release/0.21` branch.
No
No.
=> [release/0.21] Fix redist nuspec

.github/workflows/cicd.yml, scripts/common.psm1
Fixes #4188 
This PR updates the regression tests to run against 0.21.0 release.
This PR updates tests.
No
No
=> Update regression tests

libs/api/Verifier.cpp, libs/api/api_internal.h, libs/api_common/api_common.cpp, libs/api_common/api_common.hpp, libs/api_common/windows_platform_common.hpp, libs/service/verifier_service.cpp, tests/end_to_end/end_to_end.cpp, tests/libfuzzer/execution_context/libfuzz_harness.cpp, tests/unit/libbpf_test.cpp
Pick latest verifier and fix breaks from https://github.com/vbpf/prevail/commit/1d03b8ce8c809219417f61be9194c629a9410d2e
CI/CD
No.
No.
=> Pick latest verifier

.github/workflows/cicd.yml, tests/end_to_end/netsh_test.cpp
Run the unit tests on an ARM64 runner
CI/CD
No.
No.
=> Arm64 test

.github/workflows/check-pr.yml
This PR introduces a new workflow to check if the PR description refers to a valid issue.
If not found, it adds a comment.
CI.
None.
None.
=> Workflow to check PRs.

scripts/config_test_vm.psm1, scripts/onebranch/post-build.ps1
Strip whitespace from end of lines.
CI/CD
No.
No.
=> Strip white space from end of lines

libs/runtime/ebpf_error.c, tests/end_to_end/netsh_test.cpp
=> Fix failures caused by VS 2022 v17.14.7

.github/pull_request_template.md, .github/workflows/check-pr-fork.yml, .github/workflows/check-pr-local.yml, .github/workflows/check-pr.yml
Creates two pipelines to check PRs from upstream repo and forked repos for reference to valid issues.
CI/CD.
None.
None.
=> support both local and fork repos.

libs/execution_context/ebpf_link.c
Resolves: #4687 
When iterating through list of links to detach, it was first releasing the reference on the object then getting the next one. Releasing the last reference resulted in the object ID being invalidated, breaking iteration.
The solution is to delay removing the ref-count until after the next object is referenced.
CI/CD
No.
No.
This pull request improves the memory management and stability of the `ebpf_link_terminate()` function by ensuring that object references are released safely during link enumeration. The most important change is the introduction of a `previous_object` variable to prevent accessing freed memory when iterating over eBPF link objects.
**Memory management and resource safety:**
* Modified `ebpf_link_terminate()` in `ebpf_link.c` to use a `previous_object` …
=> Fix iteration of loop objects

.github/workflows/check-pr-fork.yml, .github/workflows/check-pr-local.yml
Due to the incorrect file name in YML the check PR workflow was silently failing so far. This PR fixes this.
N/A.
N/A.
N/A
=> fix incorrect file name.

include/ebpf_nethooks.h, netebpfext/net_ebpf_ext_sock_addr.c, tests/connect_redirect/connect_redirect_tests.cpp, tests/netebpfext_unit/netebpfext_unit.cpp, tests/sample/cgroup_count_connect4.c, tests/sample/cgroup_count_connect6.c, tests/sample/cgroup_mt_connect4.c, tests/sample/cgroup_mt_connect6.c, tests/sample/cgroup_sock_addr.c, tests/sample/process_start_key.c, tests/sample/thread_start_time.c, tests/socket/socket_tests.cpp, tests/stress/km/stress_tests_km.cpp
Fixes #4676
Existing tests do cover this change.
Updated include/ebpf_nethooks.h
No installer change.
=> Change BPF_SOCK_ADDR_VERDICT_PROCEED to BPF_SOCK_ADDR_VERDICT_PROCEED_SOFT
